    (:derived (inconsistent) 
        (or (WetDrone cb) (Drone cb) (WetDrone ee) (WetDrone da) (Drone ee) (Drone da))
    )

    (:derived (KBquery_WetDrone ?x)
        (or
            (inconsistent) 
            (and (= ?x ad) (and (WetDrone ad) (or (Drone ad) (WetDrone ad)))
            (and (= ?x ca) (and (WetDrone ca) (or (Drone ca) (WetDrone ca)))
            (and (= ?x ab) (and (WetDrone ab) (or (WetDrone ab) (Drone ab)))
            (and (= ?x de) (and (WetDrone de) (or (WetDrone de) (Drone de)))
            (and (= ?x bd) (and (WetDrone bd) (or (WetDrone bd) (Drone bd)))
            (and (= ?x ce) (and (WetDrone ce) (or (WetDrone ce) (Drone ce)))
            (and (= ?x ba) (and (WetDrone ba) (or (WetDrone ba) (Drone ba)))
            (and (= ?x ae) (and (WetDrone ae) (or (Drone ae) (WetDrone ae)))
            (and (= ?x aa) (and (WetDrone aa) (or (WetDrone aa) (Drone aa)))
            (and (= ?x bc) (and (WetDrone bc) (or (Drone bc) (WetDrone bc)))
            (and (= ?x dd) (and (WetDrone dd) (or (WetDrone dd) (Drone dd)))
            (and (= ?x dc) (and (WetDrone dc) (or (WetDrone dc) (Drone dc)))
            (and (= ?x ed) (and (WetDrone ed) (or (WetDrone ed) (Drone ed)))
            (and (= ?x bb) (and (WetDrone bb) (or (Drone bb) (WetDrone bb)))
            (and (= ?x ec) (and (WetDrone ec) (or (Drone ec) (WetDrone ec)))
            (and (= ?x cd) (and (WetDrone cd) (or (WetDrone cd) (Drone cd)))
            (and (= ?x db) (and (WetDrone db) (or (Drone db) (WetDrone db)))
            (and (= ?x ac) (and (WetDrone ac) (or (Drone ac) (WetDrone ac)))
            (and (= ?x be) (and (WetDrone be) (or (WetDrone be) (Drone be)))
            (and (= ?x ea) (and (WetDrone ea) (or (Drone ea) (WetDrone ea)))
            (and (= ?x da) (false)
            (and (= ?x eb) (and (WetDrone eb) (or (Drone eb) (WetDrone eb)))
            (and (= ?x cc) (and (WetDrone cc) (or (WetDrone cc) (Drone cc)))
            (and (= ?x cb) (false)
            (and (= ?x ee) (false)
        )
    )

