(define (domain robot)
	(:predicates
(KBquery_AboveOf0 ?x)
(KBquery_AboveOf1 ?x)
(KBquery_AboveOf2 ?x)
(KBquery_AboveOf3 ?x)
(KBquery_AboveOf4 ?x)
(KBquery_AboveOf5 ?x)
(KBquery_AboveOf6 ?x)
(KBquery_BelowOf1 ?x)
(KBquery_BelowOf2 ?x)
(KBquery_BelowOf3 ?x)
(KBquery_BelowOf4 ?x)
(KBquery_BelowOf5 ?x)
(KBquery_BelowOf6 ?x)
(KBquery_BelowOf7 ?x)
(KBquery_Column0 ?x)
(KBquery_Column1 ?x)
(KBquery_Column2 ?x)
(KBquery_Column3 ?x)
(KBquery_Column4 ?x)
(KBquery_Column5 ?x)
(KBquery_Column6 ?x)
(KBquery_Columns ?x)
(KBquery_LeftOf1 ?x)
(KBquery_LeftOf2 ?x)
(KBquery_LeftOf3 ?x)
(KBquery_LeftOf4 ?x)
(KBquery_LeftOf5 ?x)
(KBquery_LeftOf6 ?x)
(KBquery_LeftOf7 ?x)
(KBquery_RightOf0 ?x)
(KBquery_RightOf1 ?x)
(KBquery_RightOf2 ?x)
(KBquery_RightOf3 ?x)
(KBquery_RightOf4 ?x)
(KBquery_RightOf5 ?x)
(KBquery_RightOf6 ?x)
(KBquery_Row0 ?x)
(KBquery_Row1 ?x)
(KBquery_Row2 ?x)
(KBquery_Row3 ?x)
(KBquery_Row4 ?x)
(KBquery_Row5 ?x)
(KBquery_Row6 ?x)
(KBquery_Rows ?x)
		(Columns ?x)
		(Rows ?x)
		(Column0 ?x)
		(Column1 ?x)
		(Column2 ?x)
		(Column3 ?x)
		(Column4 ?x)
		(Column5 ?x)
		(Column6 ?x)
		(RightOf0 ?x)
		(RightOf1 ?x)
		(RightOf2 ?x)
		(RightOf3 ?x)
		(RightOf4 ?x)
		(RightOf5 ?x)
		(RightOf6 ?x)
		(LeftOf1 ?x)
		(LeftOf2 ?x)
		(LeftOf3 ?x)
		(LeftOf4 ?x)
		(LeftOf5 ?x)
		(LeftOf6 ?x)
		(LeftOf7 ?x)
		(Row0 ?x)
		(Row1 ?x)
		(Row2 ?x)
		(Row3 ?x)
		(Row4 ?x)
		(Row5 ?x)
		(Row6 ?x)
		(AboveOf0 ?x)
		(AboveOf1 ?x)
		(AboveOf2 ?x)
		(AboveOf3 ?x)
		(AboveOf4 ?x)
		(AboveOf5 ?x)
		(AboveOf6 ?x)
		(BelowOf1 ?x)
		(BelowOf2 ?x)
		(BelowOf3 ?x)
		(BelowOf4 ?x)
		(BelowOf5 ?x)
		(BelowOf6 ?x)
		(BelowOf7 ?x)
	)
	(:action moveRight
		:parameters (?x)
		:precondition (and (KBquery_Columns ?x))
		:effect (and 
			(when (KBquery_RightOf0 ?x)
				(and (RightOf1 ?x))
				)
			(when (KBquery_RightOf1 ?x)
				(and (RightOf2 ?x))
				)
			(when (KBquery_RightOf2 ?x)
				(and (RightOf3 ?x))
				)
			(when (KBquery_RightOf3 ?x)
				(and (RightOf4 ?x))
				)
			(when (KBquery_RightOf4 ?x)
				(and (RightOf5 ?x))
				)
			(when (KBquery_RightOf5 ?x)
				(and (RightOf6 ?x))
				)
			(when (KBquery_LeftOf1 ?x)
				(and (LeftOf2 ?x)
				(not (LeftOf1 ?x)))
				)
			(when (KBquery_LeftOf2 ?x)
				(and (LeftOf3 ?x)
				(not (LeftOf2 ?x)))
				)
			(when (KBquery_LeftOf3 ?x)
				(and (LeftOf4 ?x)
				(not (LeftOf3 ?x)))
				)
			(when (KBquery_LeftOf4 ?x)
				(and (LeftOf5 ?x)
				(not (LeftOf4 ?x)))
				)
			(when (KBquery_LeftOf5 ?x)
				(and (LeftOf6 ?x)
				(not (LeftOf5 ?x)))
				)
			(when (KBquery_LeftOf6 ?x)
				(and (LeftOf7 ?x)
				(not (LeftOf6 ?x)))
				)
			(when (KBquery_Column0 ?x)
				(and (Column1 ?x)
				(not (Column0 ?x)))
				)
			(when (KBquery_Column1 ?x)
				(and (Column2 ?x)
				(not (Column1 ?x)))
				)
			(when (KBquery_Column2 ?x)
				(and (Column3 ?x)
				(not (Column2 ?x)))
				)
			(when (KBquery_Column3 ?x)
				(and (Column4 ?x)
				(not (Column3 ?x)))
				)
			(when (KBquery_Column4 ?x)
				(and (Column5 ?x)
				(not (Column4 ?x)))
				)
			(when (KBquery_Column5 ?x)
				(and (Column6 ?x)
				(not (Column5 ?x)))
				)
			(when (and (KBquery_RightOf0 ?x) (KBquery_LeftOf1 ?x))
				(and (Column1 ?x))
				)
			(when (and (KBquery_RightOf1 ?x) (KBquery_LeftOf2 ?x))
				(and (Column2 ?x))
				)
			(when (and (KBquery_RightOf2 ?x) (KBquery_LeftOf3 ?x))
				(and (Column3 ?x))
				)
			(when (and (KBquery_RightOf3 ?x) (KBquery_LeftOf4 ?x))
				(and (Column4 ?x))
				)
			(when (and (KBquery_RightOf4 ?x) (KBquery_LeftOf5 ?x))
				(and (Column5 ?x))
				)
			(when (and (KBquery_RightOf5 ?x) (KBquery_LeftOf6 ?x))
				(and (Column6 ?x))
				)
		))
	(:action moveLeft
		:parameters (?x)
		:precondition (and (KBquery_Columns ?x))
		:effect (and 
			(when (KBquery_LeftOf2 ?x)
				(and (LeftOf1 ?x))
				)
			(when (KBquery_LeftOf3 ?x)
				(and (LeftOf2 ?x))
				)
			(when (KBquery_LeftOf4 ?x)
				(and (LeftOf3 ?x))
				)
			(when (KBquery_LeftOf5 ?x)
				(and (LeftOf4 ?x))
				)
			(when (KBquery_LeftOf6 ?x)
				(and (LeftOf5 ?x))
				)
			(when (KBquery_LeftOf7 ?x)
				(and (LeftOf6 ?x))
				)
			(when (KBquery_RightOf1 ?x)
				(and (RightOf0 ?x)
				(RightOf1 ?x))
				)
			(when (KBquery_RightOf2 ?x)
				(and (RightOf1 ?x)
				(RightOf2 ?x))
				)
			(when (KBquery_RightOf3 ?x)
				(and (RightOf2 ?x)
				(RightOf3 ?x))
				)
			(when (KBquery_RightOf4 ?x)
				(and (RightOf3 ?x)
				(RightOf4 ?x))
				)
			(when (KBquery_RightOf5 ?x)
				(and (RightOf4 ?x)
				(RightOf5 ?x))
				)
			(when (KBquery_RightOf6 ?x)
				(and (RightOf5 ?x)
				(RightOf6 ?x))
				)
			(when (KBquery_Column1 ?x)
				(and (Column0 ?x)
				(not (Column1 ?x)))
				)
			(when (KBquery_Column2 ?x)
				(and (Column1 ?x)
				(not (Column2 ?x)))
				)
			(when (KBquery_Column3 ?x)
				(and (Column2 ?x)
				(not (Column3 ?x)))
				)
			(when (KBquery_Column4 ?x)
				(and (Column3 ?x)
				(not (Column4 ?x)))
				)
			(when (KBquery_Column5 ?x)
				(and (Column4 ?x)
				(not (Column5 ?x)))
				)
			(when (KBquery_Column6 ?x)
				(and (Column5 ?x)
				(not (Column6 ?x)))
				)
			(when (and (KBquery_RightOf1 ?x) (KBquery_LeftOf2 ?x))
				(and (Column0 ?x))
				)
			(when (and (KBquery_RightOf2 ?x) (KBquery_LeftOf3 ?x))
				(and (Column1 ?x))
				)
			(when (and (KBquery_RightOf3 ?x) (KBquery_LeftOf4 ?x))
				(and (Column2 ?x))
				)
			(when (and (KBquery_RightOf4 ?x) (KBquery_LeftOf5 ?x))
				(and (Column3 ?x))
				)
			(when (and (KBquery_RightOf5 ?x) (KBquery_LeftOf6 ?x))
				(and (Column4 ?x))
				)
			(when (and (KBquery_RightOf6 ?x) (KBquery_LeftOf7 ?x))
				(and (Column5 ?x))
				)
		))
	(:action moveUp
		:parameters (?x)
		:precondition (and (KBquery_Rows ?x))
		:effect (and 
			(when (KBquery_AboveOf0 ?x)
				(and (AboveOf1 ?x))
				)
			(when (KBquery_AboveOf1 ?x)
				(and (AboveOf2 ?x))
				)
			(when (KBquery_AboveOf2 ?x)
				(and (AboveOf3 ?x))
				)
			(when (KBquery_AboveOf3 ?x)
				(and (AboveOf4 ?x))
				)
			(when (KBquery_AboveOf4 ?x)
				(and (AboveOf5 ?x))
				)
			(when (KBquery_AboveOf5 ?x)
				(and (AboveOf6 ?x))
				)
			(when (KBquery_BelowOf1 ?x)
				(and (BelowOf2 ?x)
				(not (BelowOf1 ?x)))
				)
			(when (KBquery_BelowOf2 ?x)
				(and (BelowOf3 ?x)
				(not (BelowOf2 ?x)))
				)
			(when (KBquery_BelowOf3 ?x)
				(and (BelowOf4 ?x)
				(not (BelowOf3 ?x)))
				)
			(when (KBquery_BelowOf4 ?x)
				(and (BelowOf5 ?x)
				(not (BelowOf4 ?x)))
				)
			(when (KBquery_BelowOf5 ?x)
				(and (BelowOf6 ?x)
				(not (BelowOf5 ?x)))
				)
			(when (KBquery_BelowOf6 ?x)
				(and (BelowOf7 ?x)
				(not (BelowOf6 ?x)))
				)
			(when (KBquery_Row0 ?x)
				(and (Row1 ?x)
				(not (Row0 ?x)))
				)
			(when (KBquery_Row1 ?x)
				(and (Row2 ?x)
				(not (Row1 ?x)))
				)
			(when (KBquery_Row2 ?x)
				(and (Row3 ?x)
				(not (Row2 ?x)))
				)
			(when (KBquery_Row3 ?x)
				(and (Row4 ?x)
				(not (Row3 ?x)))
				)
			(when (KBquery_Row4 ?x)
				(and (Row5 ?x)
				(not (Row4 ?x)))
				)
			(when (KBquery_Row5 ?x)
				(and (Row6 ?x)
				(not (Row5 ?x)))
				)
			(when (and (KBquery_AboveOf0 ?x) (KBquery_BelowOf1 ?x))
				(and (Row1 ?x))
				)
			(when (and (KBquery_AboveOf1 ?x) (KBquery_BelowOf2 ?x))
				(and (Row2 ?x))
				)
			(when (and (KBquery_AboveOf2 ?x) (KBquery_BelowOf3 ?x))
				(and (Row3 ?x))
				)
			(when (and (KBquery_AboveOf3 ?x) (KBquery_BelowOf4 ?x))
				(and (Row4 ?x))
				)
			(when (and (KBquery_AboveOf4 ?x) (KBquery_BelowOf5 ?x))
				(and (Row5 ?x))
				)
			(when (and (KBquery_AboveOf5 ?x) (KBquery_BelowOf6 ?x))
				(and (Row6 ?x))
				)
		))
	(:action moveDown
		:parameters (?x)
		:precondition (and (KBquery_Rows ?x))
		:effect (and 
			(when (KBquery_BelowOf2 ?x)
				(and (BelowOf1 ?x))
				)
			(when (KBquery_BelowOf3 ?x)
				(and (BelowOf2 ?x))
				)
			(when (KBquery_BelowOf4 ?x)
				(and (BelowOf3 ?x))
				)
			(when (KBquery_BelowOf5 ?x)
				(and (BelowOf4 ?x))
				)
			(when (KBquery_BelowOf6 ?x)
				(and (BelowOf5 ?x))
				)
			(when (KBquery_BelowOf7 ?x)
				(and (BelowOf6 ?x))
				)
			(when (KBquery_AboveOf1 ?x)
				(and (AboveOf0 ?x)
				(not (AboveOf1 ?x)))
				)
			(when (KBquery_AboveOf2 ?x)
				(and (AboveOf1 ?x)
				(not (AboveOf2 ?x)))
				)
			(when (KBquery_AboveOf3 ?x)
				(and (AboveOf2 ?x)
				(not (AboveOf3 ?x)))
				)
			(when (KBquery_AboveOf4 ?x)
				(and (AboveOf3 ?x)
				(not (AboveOf4 ?x)))
				)
			(when (KBquery_AboveOf5 ?x)
				(and (AboveOf4 ?x)
				(not (AboveOf5 ?x)))
				)
			(when (KBquery_AboveOf6 ?x)
				(and (AboveOf5 ?x)
				(not (AboveOf6 ?x)))
				)
			(when (KBquery_Row1 ?x)
				(and (Row0 ?x)
				(not (Row1 ?x)))
				)
			(when (KBquery_Row2 ?x)
				(and (Row1 ?x)
				(not (Row2 ?x)))
				)
			(when (KBquery_Row3 ?x)
				(and (Row2 ?x)
				(not (Row3 ?x)))
				)
			(when (KBquery_Row4 ?x)
				(and (Row3 ?x)
				(not (Row4 ?x)))
				)
			(when (KBquery_Row5 ?x)
				(and (Row4 ?x)
				(not (Row5 ?x)))
				)
			(when (KBquery_Row6 ?x)
				(and (Row5 ?x)
				(not (Row6 ?x)))
				)
			(when (and (KBquery_AboveOf1 ?x) (KBquery_BelowOf2 ?x))
				(and (Row0 ?x))
				)
			(when (and (KBquery_AboveOf2 ?x) (KBquery_BelowOf3 ?x))
				(and (Row1 ?x))
				)
			(when (and (KBquery_AboveOf3 ?x) (KBquery_BelowOf4 ?x))
				(and (Row2 ?x))
				)
			(when (and (KBquery_AboveOf4 ?x) (KBquery_BelowOf5 ?x))
				(and (Row3 ?x))
				)
			(when (and (KBquery_AboveOf5 ?x) (KBquery_BelowOf6 ?x))
				(and (Row4 ?x))
				)
			(when (and (KBquery_AboveOf6 ?x) (KBquery_BelowOf7 ?x))
				(and (Row5 ?x))
				)
		))

)
