(define (problem BLOCKS-4-2)
(:domain BLOCKS)
(:objects B D A C - block pr2 - robot)
(:INIT (CLEAR A) (CLEAR C) (CLEAR D) (ONTABLE A) (ONTABLE B) (ONTABLE D)
 (ON C B))
(:goal (AND (ON A B) (ON B C) (ON C D)))
)
