(define (problem BLOCKS-6-0)
(:domain BLOCKS)
(:objects B E A C D F - block pr2 - robot)
(:INIT (CLEAR D) (CLEAR F) (ONTABLE C) (ONTABLE B) (ON D A) (ON A C) (ON F E)
 (ON E B) (HANDEMPTY))
(:goal (AND (ON C B) (ON B A) (ON A E) (ON E F) (ON F D)))
)
