(define (problem pipes_problem)
	(:domain pipes)
	(:objects aa ab ac ad ae af ag ah ai aj ba bb bc bd be bf bg bh bi bj ca cb cc cd ce cf cg ch ci cj da db dc dd de df dg dh di dj ea eb ec ed ee ef eg eh ei ej fa fb fc fd fe ff fg fh fi fj ga gb gc gd ge gf gg gh gi gj ha hb hc hd he hf hg hh hi hj ia ib ic id ie if ig ih ii ij ja jb jc jd je jf jg jh ji jj auv tankBA tankAH tankDF tankJB valveCC valveCE valveEB valveEG valveGG valveIB pipeAD pipeBD pipeCD pipeCF pipeCG pipeCH pipeCI pipeDB pipeDI pipeEF pipeEH pipeEI pipeFB pipeFI pipeGB pipeGC pipeGD pipeGE pipeGF pipeGH pipeGI wallED wallHA
)
	(:init
		(nextTo aa ab)
		(nextTo aa ba)
		(nextTo ab ac)
		(nextTo ba ca)
		(nextTo ac ad)
		(nextTo ca da)
		(nextTo ad ae)
		(nextTo da ea)
		(nextTo ae af)
		(nextTo ea fa)
		(nextTo af ag)
		(nextTo fa ga)
		(nextTo ag ah)
		(nextTo ga ha)
		(nextTo ah ai)
		(nextTo ha ia)
		(nextTo ai aj)
		(nextTo ia ja)
		(nextTo ba bb)
		(nextTo ab bb)
		(nextTo bb bc)
		(nextTo bb cb)
		(nextTo bc bd)
		(nextTo cb db)
		(nextTo bd be)
		(nextTo db eb)
		(nextTo be bf)
		(nextTo eb fb)
		(nextTo bf bg)
		(nextTo fb gb)
		(nextTo bg bh)
		(nextTo gb hb)
		(nextTo bh bi)
		(nextTo hb ib)
		(nextTo bi bj)
		(nextTo ib jb)
		(nextTo ca cb)
		(nextTo ac bc)
		(nextTo cb cc)
		(nextTo bc cc)
		(nextTo cc cd)
		(nextTo cc dc)
		(nextTo cd ce)
		(nextTo dc ec)
		(nextTo ce cf)
		(nextTo ec fc)
		(nextTo cf cg)
		(nextTo fc gc)
		(nextTo cg ch)
		(nextTo gc hc)
		(nextTo ch ci)
		(nextTo hc ic)
		(nextTo ci cj)
		(nextTo ic jc)
		(nextTo da db)
		(nextTo ad bd)
		(nextTo db dc)
		(nextTo bd cd)
		(nextTo dc dd)
		(nextTo cd dd)
		(nextTo dd de)
		(nextTo dd ed)
		(nextTo de df)
		(nextTo ed fd)
		(nextTo df dg)
		(nextTo fd gd)
		(nextTo dg dh)
		(nextTo gd hd)
		(nextTo dh di)
		(nextTo hd id)
		(nextTo di dj)
		(nextTo id jd)
		(nextTo ea eb)
		(nextTo ae be)
		(nextTo eb ec)
		(nextTo be ce)
		(nextTo ec ed)
		(nextTo ce de)
		(nextTo ed ee)
		(nextTo de ee)
		(nextTo ee ef)
		(nextTo ee fe)
		(nextTo ef eg)
		(nextTo fe ge)
		(nextTo eg eh)
		(nextTo ge he)
		(nextTo eh ei)
		(nextTo he ie)
		(nextTo ei ej)
		(nextTo ie je)
		(nextTo fa fb)
		(nextTo af bf)
		(nextTo fb fc)
		(nextTo bf cf)
		(nextTo fc fd)
		(nextTo cf df)
		(nextTo fd fe)
		(nextTo df ef)
		(nextTo fe ff)
		(nextTo ef ff)
		(nextTo ff fg)
		(nextTo ff gf)
		(nextTo fg fh)
		(nextTo gf hf)
		(nextTo fh fi)
		(nextTo hf if)
		(nextTo fi fj)
		(nextTo if jf)
		(nextTo ga gb)
		(nextTo ag bg)
		(nextTo gb gc)
		(nextTo bg cg)
		(nextTo gc gd)
		(nextTo cg dg)
		(nextTo gd ge)
		(nextTo dg eg)
		(nextTo ge gf)
		(nextTo eg fg)
		(nextTo gf gg)
		(nextTo fg gg)
		(nextTo gg gh)
		(nextTo gg hg)
		(nextTo gh gi)
		(nextTo hg ig)
		(nextTo gi gj)
		(nextTo ig jg)
		(nextTo ha hb)
		(nextTo ah bh)
		(nextTo hb hc)
		(nextTo bh ch)
		(nextTo hc hd)
		(nextTo ch dh)
		(nextTo hd he)
		(nextTo dh eh)
		(nextTo he hf)
		(nextTo eh fh)
		(nextTo hf hg)
		(nextTo fh gh)
		(nextTo hg hh)
		(nextTo gh hh)
		(nextTo hh hi)
		(nextTo hh ih)
		(nextTo hi hj)
		(nextTo ih jh)
		(nextTo ia ib)
		(nextTo ai bi)
		(nextTo ib ic)
		(nextTo bi ci)
		(nextTo ic id)
		(nextTo ci di)
		(nextTo id ie)
		(nextTo di ei)
		(nextTo ie if)
		(nextTo ei fi)
		(nextTo if ig)
		(nextTo fi gi)
		(nextTo ig ih)
		(nextTo gi hi)
		(nextTo ih ii)
		(nextTo hi ii)
		(nextTo ii ij)
		(nextTo ii ji)
		(nextTo ja jb)
		(nextTo aj bj)
		(nextTo jb jc)
		(nextTo bj cj)
		(nextTo jc jd)
		(nextTo cj dj)
		(nextTo jd je)
		(nextTo dj ej)
		(nextTo je jf)
		(nextTo ej fj)
		(nextTo jf jg)
		(nextTo fj gj)
		(nextTo jg jh)
		(nextTo gj hj)
		(nextTo jh ji)
		(nextTo hj ij)
		(nextTo ji jj)
		(nextTo ij jj)
		(nextTo aa bb)
		(nextTo ab bc)
		(nextTo ac bd)
		(nextTo ad be)
		(nextTo ae bf)
		(nextTo af bg)
		(nextTo ag bh)
		(nextTo ah bi)
		(nextTo ai bj)
		(nextTo ab ba)
		(nextTo ac bb)
		(nextTo ad bc)
		(nextTo ae bd)
		(nextTo af be)
		(nextTo ag bf)
		(nextTo ah bg)
		(nextTo ai bh)
		(nextTo aj bi)
		(nextTo ba cb)
		(nextTo bb cc)
		(nextTo bc cd)
		(nextTo bd ce)
		(nextTo be cf)
		(nextTo bf cg)
		(nextTo bg ch)
		(nextTo bh ci)
		(nextTo bi cj)
		(nextTo bb ca)
		(nextTo bc cb)
		(nextTo bd cc)
		(nextTo be cd)
		(nextTo bf ce)
		(nextTo bg cf)
		(nextTo bh cg)
		(nextTo bi ch)
		(nextTo bj ci)
		(nextTo ca db)
		(nextTo cb dc)
		(nextTo cc dd)
		(nextTo cd de)
		(nextTo ce df)
		(nextTo cf dg)
		(nextTo cg dh)
		(nextTo ch di)
		(nextTo ci dj)
		(nextTo cb da)
		(nextTo cc db)
		(nextTo cd dc)
		(nextTo ce dd)
		(nextTo cf de)
		(nextTo cg df)
		(nextTo ch dg)
		(nextTo ci dh)
		(nextTo cj di)
		(nextTo da eb)
		(nextTo db ec)
		(nextTo dc ed)
		(nextTo dd ee)
		(nextTo de ef)
		(nextTo df eg)
		(nextTo dg eh)
		(nextTo dh ei)
		(nextTo di ej)
		(nextTo db ea)
		(nextTo dc eb)
		(nextTo dd ec)
		(nextTo de ed)
		(nextTo df ee)
		(nextTo dg ef)
		(nextTo dh eg)
		(nextTo di eh)
		(nextTo dj ei)
		(nextTo ea fb)
		(nextTo eb fc)
		(nextTo ec fd)
		(nextTo ed fe)
		(nextTo ee ff)
		(nextTo ef fg)
		(nextTo eg fh)
		(nextTo eh fi)
		(nextTo ei fj)
		(nextTo eb fa)
		(nextTo ec fb)
		(nextTo ed fc)
		(nextTo ee fd)
		(nextTo ef fe)
		(nextTo eg ff)
		(nextTo eh fg)
		(nextTo ei fh)
		(nextTo ej fi)
		(nextTo fa gb)
		(nextTo fb gc)
		(nextTo fc gd)
		(nextTo fd ge)
		(nextTo fe gf)
		(nextTo ff gg)
		(nextTo fg gh)
		(nextTo fh gi)
		(nextTo fi gj)
		(nextTo fb ga)
		(nextTo fc gb)
		(nextTo fd gc)
		(nextTo fe gd)
		(nextTo ff ge)
		(nextTo fg gf)
		(nextTo fh gg)
		(nextTo fi gh)
		(nextTo fj gi)
		(nextTo ga hb)
		(nextTo gb hc)
		(nextTo gc hd)
		(nextTo gd he)
		(nextTo ge hf)
		(nextTo gf hg)
		(nextTo gg hh)
		(nextTo gh hi)
		(nextTo gi hj)
		(nextTo gb ha)
		(nextTo gc hb)
		(nextTo gd hc)
		(nextTo ge hd)
		(nextTo gf he)
		(nextTo gg hf)
		(nextTo gh hg)
		(nextTo gi hh)
		(nextTo gj hi)
		(nextTo ha ib)
		(nextTo hb ic)
		(nextTo hc id)
		(nextTo hd ie)
		(nextTo he if)
		(nextTo hf ig)
		(nextTo hg ih)
		(nextTo hh ii)
		(nextTo hi ij)
		(nextTo hb ia)
		(nextTo hc ib)
		(nextTo hd ic)
		(nextTo he id)
		(nextTo hf ie)
		(nextTo hg if)
		(nextTo hh ig)
		(nextTo hi ih)
		(nextTo hj ii)
		(nextTo ia jb)
		(nextTo ib jc)
		(nextTo ic jd)
		(nextTo id je)
		(nextTo ie jf)
		(nextTo if jg)
		(nextTo ig jh)
		(nextTo ih ji)
		(nextTo ii jj)
		(nextTo ib ja)
		(nextTo ic jb)
		(nextTo id jc)
		(nextTo ie jd)
		(nextTo if je)
		(nextTo ig jf)
		(nextTo ih jg)
		(nextTo ii jh)
		(nextTo ij ji)

		(WP aa)
		(WP ab)
		(WP ac)
		(WP ad)
		(WP ae)
		(WP af)
		(WP ag)
		(WP ah)
		(WP ai)
		(WP aj)
		(WP ba)
		(WP bb)
		(WP bc)
		(WP bd)
		(WP be)
		(WP bf)
		(WP bg)
		(WP bh)
		(WP bi)
		(WP bj)
		(WP ca)
		(WP cb)
		(WP cc)
		(WP cd)
		(WP ce)
		(WP cf)
		(WP cg)
		(WP ch)
		(WP ci)
		(WP cj)
		(WP da)
		(WP db)
		(WP dc)
		(WP dd)
		(WP de)
		(WP df)
		(WP dg)
		(WP dh)
		(WP di)
		(WP dj)
		(WP ea)
		(WP eb)
		(WP ec)
		(WP ed)
		(WP ee)
		(WP ef)
		(WP eg)
		(WP eh)
		(WP ei)
		(WP ej)
		(WP fa)
		(WP fb)
		(WP fc)
		(WP fd)
		(WP fe)
		(WP ff)
		(WP fg)
		(WP fh)
		(WP fi)
		(WP fj)
		(WP ga)
		(WP gb)
		(WP gc)
		(WP gd)
		(WP ge)
		(WP gf)
		(WP gg)
		(WP gh)
		(WP gi)
		(WP gj)
		(WP ha)
		(WP hb)
		(WP hc)
		(WP hd)
		(WP he)
		(WP hf)
		(WP hg)
		(WP hh)
		(WP hi)
		(WP hj)
		(WP ia)
		(WP ib)
		(WP ic)
		(WP id)
		(WP ie)
		(WP if)
		(WP ig)
		(WP ih)
		(WP ii)
		(WP ij)
		(WP ja)
		(WP jb)
		(WP jc)
		(WP jd)
		(WP je)
		(WP jf)
		(WP jg)
		(WP jh)
		(WP ji)
		(WP jj)



		(Pipe pipeAD)
		(Pipe pipeBD)
		(PipeFailure pipeCD)
		(Pipe pipeCF)
		(Pipe pipeCG)
		(Pipe pipeCH)
		(Pipe pipeCI)
		(Pipe pipeDB)
		(Pipe pipeDI)
		(Pipe pipeEF)
		(Pipe pipeEH)
		(Pipe pipeEI)
		(Pipe pipeFB)
		(Pipe pipeFI)
		(PipeFailure pipeGB)
		(Pipe pipeGC)
		(Pipe pipeGD)
		(Pipe pipeGE)
		(Pipe pipeGF)
		(Pipe pipeGH)
		(Pipe pipeGI)

		(locatedAt pipeAD ad)
		(locatedAt pipeBD bd)
		(locatedAt pipeCD cd)
		(locatedAt pipeCF cf)
		(locatedAt pipeCG cg)
		(locatedAt pipeCH ch)
		(locatedAt pipeCI ci)
		(locatedAt pipeDB db)
		(locatedAt pipeDI di)
		(locatedAt pipeEF ef)
		(locatedAt pipeEH eh)
		(locatedAt pipeEI ei)
		(locatedAt pipeFB fb)
		(locatedAt pipeFI fi)
		(locatedAt pipeGB gb)
		(locatedAt pipeGC gc)
		(locatedAt pipeGD gd)
		(locatedAt pipeGE ge)
		(locatedAt pipeGF gf)
		(locatedAt pipeGH gh)
		(locatedAt pipeGI gi)



		
		(Tank tankBA)
		(Tank tankAH)
		(Tank tankDF)
		(Tank tankJB)

		(locatedAt tankBA ba)
		(locatedAt tankBA bb)
		(locatedAt tankBA ca)
		(locatedAt tankBA cb)
		(locatedAt tankAH ah)
		(locatedAt tankAH bh)
		(locatedAt tankDF df)
		(locatedAt tankJB jb)
		(locatedAt tankJB jc)
		(locatedAt tankJB jd)
		
		(Robot auv)
		(robotAt auv aa)

		(Valve valveCC)
		(Valve valveCE)
		(Valve valveEB)
		(Valve valveEG)
		(Valve valveGG)
		(Valve valveIB)

		(OpenValve valveCC)
		(OpenValve valveCE)
		(OpenValve valveEB)
		(OpenValve valveEG)
		(OpenValve valveGG)
		(OpenValve valveIB)

		(locatedAt valveCC cc)
		(locatedAt valveCE ce)
		(locatedAt valveEB eb)
		(locatedAt valveEG eg)
		(locatedAt valveGG gg)
		(locatedAt valveIB ib)

		(Wall wallED)
		(Wall wallHA)

		(locatedAt wallED ed)
		(locatedAt wallED ee)
		(locatedAt wallED fe)
		(locatedAt wallED ff)
		(locatedAt wallHA ha)
		(locatedAt wallHA hb)
		(locatedAt wallHA hc)
		(locatedAt wallHA hd)
		(locatedAt wallHA he)
		(locatedAt wallHA hf)
		(locatedAt wallHA hg)
		(locatedAt wallHA hh)

		
		(connectedTo pipeAD pipeBD)
		(connectedTo pipeBD pipeCD)
		(connectedTo tankAH pipeCH)
		(connectedTo tankBA valveCC)
		(connectedTo valveCC pipeCD)
		(connectedTo pipeCD valveCE)
		(connectedTo valveCE pipeCF)
		(connectedTo pipeCF pipeCG)
		(connectedTo pipeCG pipeCH)
		(connectedTo pipeCH pipeCI)	
		(connectedTo tankBA pipeDB)
		(connectedTo pipeCF tankDF)
		(connectedTo pipeCI pipeDI)
		(connectedTo pipeDB valveEB)
		(connectedTo tankDF pipeEF)
		(connectedTo pipeDI pipeEI)
		(connectedTo pipeEF valveEG)
		(connectedTo valveEG pipeEH)
		(connectedTo pipeEH pipeEI)
		(connectedTo valveEB pipeFB)
		(connectedTo pipeEI pipeFI)
		(connectedTo pipeFB pipeGB)
		(connectedTo pipeFI pipeGI)
		(connectedTo pipeGB pipeGC)
		(connectedTo pipeGC pipeGD)
		(connectedTo pipeGD pipeGE)
		(connectedTo pipeGE pipeGF)
		(connectedTo pipeGF valveGG)
		(connectedTo valveGG pipeGH)
		(connectedTo pipeGH pipeGI)
		(connectedTo pipeGB valveIB)
		(connectedTo valveIB tankJB)

		

	)
	(:goal (and
		(forall (?wp) (or 
			(not (mko (WPConnectedToFailure ?wp)))
			(hasPicture auv ?wp)
			)
		)
		(not (exists (?wp) (and 
			(mko (WPTank ?wp))
			(mko (WPConnectedToFailure ?wp))
		))
		)
	)
	)
)