(define (domain pipes)
(:requirements :strips :equality :disjunctive-preconditions :derived-predicates :negative-preconditions :conditional-effects :existential-preconditions)
(:constants
  aa ab ac ad ae af ag auv ba bb bc bd be bf bg ca cb cc cd ce cf cg da db dc dd de df dg ea eb ec ed ee ef eg fa fb fc fd fe ff fg ga gb gc gd ge gf gg mineef pipebg pipecc pipecd pipecg pipede pipedf pipeee pipefc pipefd pipegb pipegc wallab wallbb wallcb walldb walldc walldd - object)
(:predicates
  (nextto ?wpA ?wpB - object)
  (haspicture ?auv ?wp - object)
  (robotat ?auv ?wp - object)
  (rock ?x - object)
  (mediumriskpipe ?x - object)
  (mine ?x - object)
  (pipe ?x - object)
  (protectedstructure ?x - object)
  (robot ?x - object)
  (rustypipe ?x - object)
  (unsupportedpipe ?x - object)
  (wp ?x - object)
  (connectedto ?x ?y - object)
  (locatedat ?x ?y - object)
  (DATALOG_RISK ?x0 - object)
  (DATALOG_PIPE ?x0 - object)
  (DATALOG_WP ?x0 - object)
  (DATALOG_ROBOTAT ?x0 ?x1 - object)
  (DATALOG_RUSTYPIPEORUNSUPPORTEDPIPE ?x0 - object)
  (DATALOG_HASOBJECTSOMERUSTYPIPEORUNSUPPORTEDPIPE ?x0 - object)
  (DATALOG_HASOBJECTSOMEPIPEANDCONNECTEDTOSOMELOCATEDATSOMEINVERSEHASPICTURESOMEROBOT ?x0 - object)
  (DATALOG_CONNECTEDTOSOMELOCATEDATSOMEINVERSEHASPICTURESOMEROBOT ?x0 - object)
  (DATALOG_HASOBJECTSOMEPIPE ?x0 - object)
  (DATALOG_MEDIUMRISK ?x0 - object)
  (DATALOG_CONNECTEDTOSOMERUSTYPIPE ?x0 - object)
  (DATALOG_LOCATEDAT ?x0 ?x1 - object)
  (DATALOG_ROBOT ?x0 - object)
  (DATALOG_MINEORPROTECTEDSTRUCTURE ?x0 - object)
  (DATALOG_INVERSEROBOTATSOMEROBOT ?x0 - object)
  (DATALOG_HASOBJECTSOMEMEDIUMRISKPIPE ?x0 - object)
  (DATALOG_INCONSISTENT)
  (DATALOG_FORBIDDENWP ?x0 - object)
  (DATALOG_MEDIUMRISKPIPE ?x0 - object)
  (DATALOG_COVERED ?x0 - object)
  (DATALOG_CONNECTEDTO ?x0 ?x1 - object)
  (DATALOG_INVERSEHASPICTURESOMEROBOT ?x0 - object)
  (DATALOG_HASOBJECT ?x0 ?x1 - object)
  (DATALOG_LOCATEDATSOMEINVERSEHASPICTURESOMEROBOT ?x0 - object)
  (DATALOG_HIGHRISK ?x0 - object)
  (DATALOG_HASOBJECTSOMEROCK ?x0 - object)
  (DATALOG_HASOBJECTSOMEMINEORPROTECTEDSTRUCTURE ?x0 - object)
  (DATALOG_PIPEANDCONNECTEDTOSOMELOCATEDATSOMEINVERSEHASPICTURESOMEROBOT ?x0 - object)
  (AUX0 ?x0 - object ?y0 - object)
  (AUX1 ?x0 - object ?y0 - object)
  (AUX2 ?x0 - object ?y0 - object)
  (AUX3 ?x0 - object ?y0 - object)
  (AUX4 ?x0 - object ?y0 - object)
  (AUX5 ?x0 - object ?y0 - object)
  (AUX6 ?x0 - object ?y0 - object)
  (AUX7 ?y0 - object)
  (AUX8 ?x0 - object ?y0 - object)
  (AUX9 ?x0 - object ?y0 - object)
  (AUX10 ?x0 - object ?y0 - object)
  (AUX11 ?x0 - object ?y0 - object)
  (AUX12 ?x0 - object)
  (AUX13 ?x0 - object)
  (AUX14 ?x0 - object)
  (AUX15 ?x0 - object)
  (AUX16 ?x0 - object)
  (AUX17 ?x0 - object)
  (AUX18 ?wpA - object ?wpB - object)
  (AUX19 ?wp - object))
(:derived (DATALOG_HASOBJECTSOMERUSTYPIPEORUNSUPPORTEDPIPE ?x0 - object)
          (exists (?y0 - object) (AUX0 ?x0 ?y0)))
(:derived (DATALOG_HASOBJECTSOMEPIPEANDCONNECTEDTOSOMELOCATEDATSOMEINVERSEHASPICTURESOMEROBOT ?x0 - object)
          (exists (?y0 - object) (AUX1 ?x0 ?y0)))
(:derived (DATALOG_CONNECTEDTOSOMELOCATEDATSOMEINVERSEHASPICTURESOMEROBOT ?x0 - object)
          (exists (?y0 - object) (AUX2 ?x0 ?y0)))
(:derived (DATALOG_HASOBJECTSOMEPIPE ?x0 - object)
          (exists (?y0 - object) (AUX3 ?x0 ?y0)))
(:derived (DATALOG_CONNECTEDTOSOMERUSTYPIPE ?x0 - object)
          (exists (?y0 - object) (AUX4 ?x0 ?y0)))
(:derived (DATALOG_INVERSEROBOTATSOMEROBOT ?x0 - object)
          (exists (?y0 - object) (AUX5 ?x0 ?y0)))
(:derived (DATALOG_HASOBJECTSOMEMEDIUMRISKPIPE ?x0 - object)
          (exists (?y0 - object) (AUX6 ?x0 ?y0)))
(:derived (DATALOG_INCONSISTENT)
          (exists (?y0 - object) (AUX7 ?y0)))
(:derived (DATALOG_FORBIDDENWP ?x0 - object)
          (and (DATALOG_HASOBJECTSOMEMINEORPROTECTEDSTRUCTURE ?x0) (DATALOG_WP ?x0)))
(:derived (DATALOG_INVERSEHASPICTURESOMEROBOT ?x0 - object)
          (exists (?y0 - object) (AUX8 ?x0 ?y0)))
(:derived (DATALOG_HASOBJECT ?x0 ?x1 - object)
          (DATALOG_LOCATEDAT ?x1 ?x0))
(:derived (DATALOG_LOCATEDATSOMEINVERSEHASPICTURESOMEROBOT ?x0 - object)
          (exists (?y0 - object) (AUX9 ?x0 ?y0)))
(:derived (DATALOG_HIGHRISK ?x0 - object)
          (and (DATALOG_HASOBJECTSOMERUSTYPIPEORUNSUPPORTEDPIPE ?x0) (DATALOG_WP ?x0)))
(:derived (DATALOG_HASOBJECTSOMEROCK ?x0 - object)
          (exists (?y0 - object) (AUX10 ?x0 ?y0)))
(:derived (DATALOG_HASOBJECTSOMEMINEORPROTECTEDSTRUCTURE ?x0 - object)
          (exists (?y0 - object) (AUX11 ?x0 ?y0)))
(:derived (DATALOG_PIPEANDCONNECTEDTOSOMELOCATEDATSOMEINVERSEHASPICTURESOMEROBOT ?x0 - object)
          (and (DATALOG_CONNECTEDTOSOMELOCATEDATSOMEINVERSEHASPICTURESOMEROBOT ?x0) (DATALOG_PIPE ?x0)))
(:derived (DATALOG_RISK ?x0 - object)
          (or (DATALOG_COVERED ?x0) (DATALOG_HIGHRISK ?x0) (DATALOG_MEDIUMRISK ?x0)))
(:derived (DATALOG_PIPE ?x0 - object)
          (or (DATALOG_MEDIUMRISKPIPE ?x0) (pipe ?x0) (rustypipe ?x0) (unsupportedpipe ?x0)))
(:derived (DATALOG_WP ?x0 - object)
          (or (exists (?y0 - object) (DATALOG_LOCATEDAT ?y0 ?x0)) (exists (?y0 - object) (DATALOG_ROBOTAT ?y0 ?x0)) (DATALOG_FORBIDDENWP ?x0) (DATALOG_RISK ?x0) (wp ?x0)))
(:derived (DATALOG_ROBOTAT ?x0 ?x1 - object)
          (or (DATALOG_ROBOTAT ?x0 ?x1) (robotat ?x0 ?x1)))
(:derived (DATALOG_RUSTYPIPEORUNSUPPORTEDPIPE ?x0 - object)
          (or (rustypipe ?x0) (unsupportedpipe ?x0)))
(:derived (DATALOG_MEDIUMRISK ?x0 - object)
          (or (AUX12 ?x0) (AUX13 ?x0)))
(:derived (DATALOG_LOCATEDAT ?x0 ?x1 - object)
          (or (DATALOG_HASOBJECT ?x1 ?x0) (locatedat ?x0 ?x1)))
(:derived (DATALOG_ROBOT ?x0 - object)
          (or (exists (?y0 - object) (DATALOG_ROBOTAT ?x0 ?y0)) (robot ?x0)))
(:derived (DATALOG_MINEORPROTECTEDSTRUCTURE ?x0 - object)
          (or (mine ?x0) (protectedstructure ?x0)))
(:derived (DATALOG_MEDIUMRISKPIPE ?x0 - object)
          (or (AUX14 ?x0) (mediumriskpipe ?x0)))
(:derived (DATALOG_COVERED ?x0 - object)
          (or (AUX15 ?x0) (AUX16 ?x0) (AUX17 ?x0)))
(:derived (DATALOG_CONNECTEDTO ?x0 ?x1 - object)
          (or (DATALOG_CONNECTEDTO ?x1 ?x0) (connectedto ?x0 ?x1)))
(:derived (AUX0 ?x0 - object ?y0 - object)
          (and (DATALOG_HASOBJECT ?x0 ?y0) (DATALOG_RUSTYPIPEORUNSUPPORTEDPIPE ?y0)))
(:derived (AUX1 ?x0 - object ?y0 - object)
          (and (DATALOG_HASOBJECT ?x0 ?y0) (DATALOG_PIPEANDCONNECTEDTOSOMELOCATEDATSOMEINVERSEHASPICTURESOMEROBOT ?y0)))
(:derived (AUX2 ?x0 - object ?y0 - object)
          (and (DATALOG_CONNECTEDTO ?x0 ?y0) (DATALOG_LOCATEDATSOMEINVERSEHASPICTURESOMEROBOT ?y0)))
(:derived (AUX3 ?x0 - object ?y0 - object)
          (and (DATALOG_HASOBJECT ?x0 ?y0) (DATALOG_PIPE ?y0)))
(:derived (AUX4 ?x0 - object ?y0 - object)
          (and (DATALOG_CONNECTEDTO ?x0 ?y0) (rustypipe ?y0)))
(:derived (AUX5 ?x0 - object ?y0 - object)
          (and (DATALOG_ROBOT ?y0) (DATALOG_ROBOTAT ?y0 ?x0)))
(:derived (AUX6 ?x0 - object ?y0 - object)
          (and (DATALOG_HASOBJECT ?x0 ?y0) (DATALOG_MEDIUMRISKPIPE ?y0)))
(:derived (AUX7 ?y0 - object)
          (and (DATALOG_FORBIDDENWP ?y0) (DATALOG_INVERSEROBOTATSOMEROBOT ?y0)))
(:derived (AUX8 ?x0 - object ?y0 - object)
          (and (DATALOG_ROBOT ?y0) (haspicture ?y0 ?x0)))
(:derived (AUX9 ?x0 - object ?y0 - object)
          (and (DATALOG_INVERSEHASPICTURESOMEROBOT ?y0) (DATALOG_LOCATEDAT ?x0 ?y0)))
(:derived (AUX10 ?x0 - object ?y0 - object)
          (and (DATALOG_HASOBJECT ?x0 ?y0) (rock ?y0)))
(:derived (AUX11 ?x0 - object ?y0 - object)
          (and (DATALOG_HASOBJECT ?x0 ?y0) (DATALOG_MINEORPROTECTEDSTRUCTURE ?y0)))
(:derived (AUX12 ?x0 - object)
          (and (DATALOG_HASOBJECTSOMEMEDIUMRISKPIPE ?x0) (DATALOG_WP ?x0)))
(:derived (AUX13 ?x0 - object)
          (and (DATALOG_HASOBJECTSOMEPIPE ?x0) (DATALOG_HASOBJECTSOMEROCK ?x0) (DATALOG_WP ?x0)))
(:derived (AUX14 ?x0 - object)
          (and (DATALOG_CONNECTEDTOSOMERUSTYPIPE ?x0) (DATALOG_PIPE ?x0)))
(:derived (AUX15 ?x0 - object)
          (and (DATALOG_HIGHRISK ?x0) (DATALOG_INVERSEHASPICTURESOMEROBOT ?x0)))
(:derived (AUX16 ?x0 - object)
          (and (DATALOG_INVERSEHASPICTURESOMEROBOT ?x0) (DATALOG_MEDIUMRISK ?x0)))
(:derived (AUX17 ?x0 - object)
          (and (DATALOG_HASOBJECTSOMEPIPEANDCONNECTEDTOSOMELOCATEDATSOMEINVERSEHASPICTURESOMEROBOT ?x0) (DATALOG_MEDIUMRISK ?x0)))
(:derived (AUX18 ?wpA - object ?wpB - object)
          (or (nextto ?wpA ?wpB) (nextto ?wpB ?wpA)))
(:derived (AUX19 ?wp - object)
          (or (DATALOG_COVERED ?wp) (not (DATALOG_RISK ?wp))))
(:action Move
  :parameters (?auv ?wpA ?wpB - object)
  :precondition (and (AUX18 ?wpA ?wpB) (robotat ?auv ?wpA) (not (DATALOG_INCONSISTENT)))
  :effect (and (not (robotat ?auv ?wpA)) (robotat ?auv ?wpB)))
(:action takePicture
  :parameters (?auv ?wp - object)
  :precondition (and (robotat ?auv ?wp) (not (DATALOG_INCONSISTENT)))
  :effect (and (haspicture ?auv ?wp)))
)