(define (problem pipes_problem)
	(:domain pipes)
	(:objects aa ab ac ad ba bb bc bd ca cb cc cd da db dc dd auv valveAC valveDC valveEF valveGC)
	(:init
		(nextTo aa ab)
		(nextTo aa ba)
		(nextTo ab ac)
		(nextTo ba ca)
		(nextTo ac ad)
		(nextTo ca da)
		(nextTo ba bb)
		(nextTo ab bb)
		(nextTo bb bc)
		(nextTo bb cb)
		(nextTo bc bd)
		(nextTo cb db)
		(nextTo ca cb)
		(nextTo ac bc)
		(nextTo cb cc)
		(nextTo bc cc)
		(nextTo cc cd)
		(nextTo cc dc)
		(nextTo da db)
		(nextTo ad bd)
		(nextTo db dc)
		(nextTo bd cd)
		(nextTo dc dd)
		(nextTo cd dd)
		(nextTo aa bb)
		(nextTo ab bc)
		(nextTo ac bd)
		(nextTo ab ba)
		(nextTo ac bb)
		(nextTo ad bc)
		(nextTo ba cb)
		(nextTo bb cc)
		(nextTo bc cd)
		(nextTo bb ca)
		(nextTo bc cb)
		(nextTo bd cc)
		(nextTo ca db)
		(nextTo cb dc)
		(nextTo cc dd)
		(nextTo cb da)
		(nextTo cc db)
		(nextTo cd dc)

		(robotAt auv aa)
		(open valveAC)
		(open valveDC)

		(locatedAt valveAC ac)
		(locatedAt valveDC dc)
	)
	(:goal (and
		(forall (?wp) (or 
			(not (KBquery_connectedToFailure ?wp))  
			(hasPicture auv ?wp)
			)
		)
		(not (exists (?wp) (and 
			(KBquery_WPTank ?wp) 
			(KBquery_connectedToFailure ?wp)
		))
		)
	)
	)
)
