(define (problem pipes_problem)
	(:domain pipes)
	(:objects aa ab ac ad ba bb bc bd ca cb cc cd da db dc dd auv pipeBA pipeBB pipeCB pipeDB pipeEB pipeED pipeFD tankFA tankFC tankFE tankLarge valveBD valveEA valveEC valveEE valveGD wall wall2 wall3 valveGG valveEI tankFG tankCI pipeHD pipeHE pipeHG pipeHH pipeIH pipeJH pipeHI pipeHJ pipeGI pipeFI pipeDI
)
	(:init
		(nextTo aa ab)
		(nextTo aa ba)
		(nextTo ab ac)
		(nextTo ba ca)
		(nextTo ac ad)
		(nextTo ca da)
		(nextTo ba bb)
		(nextTo ab bb)
		(nextTo bb bc)
		(nextTo bb cb)
		(nextTo bc bd)
		(nextTo cb db)
		(nextTo ca cb)
		(nextTo ac bc)
		(nextTo cb cc)
		(nextTo bc cc)
		(nextTo cc cd)
		(nextTo cc dc)
		(nextTo da db)
		(nextTo ad bd)
		(nextTo db dc)
		(nextTo bd cd)
		(nextTo dc dd)
		(nextTo cd dd)
		(nextTo aa bb)
		(nextTo ab bc)
		(nextTo ac bd)
		(nextTo ab ba)
		(nextTo ac bb)
		(nextTo ad bc)
		(nextTo ba cb)
		(nextTo bb cc)
		(nextTo bc cd)
		(nextTo bb ca)
		(nextTo bc cb)
		(nextTo bd cc)
		(nextTo ca db)
		(nextTo cb dc)
		(nextTo cc dd)
		(nextTo cb da)
		(nextTo cc db)
		(nextTo cd dc)

		(Pipe pipeBA)
		(Pipe pipeBB)
		(Pipe pipeDB)
		(PipeFailure pipeCB)
		(Robot auv)
		(Tank tankLarge)
		(Valve valveBD)
		(WP aa)
		(WP ab)
		(WP ac)
		(WP ad)
		(WP ba)
		(WP bb)
		(WP bc)
		(WP bd)
		(WP ca)
		(WP cb)
		(WP cc)
		(WP cd)
		(WP da)
		(WP db)
		(WP dc)
		(WP dd)

		(robotAt auv aa)
		(OpenValve valveBD)
		(locatedAt valveBD bd)


		
		(connectedTo pipeBA pipeBB)
		(connectedTo pipeBB pipeCB)
		(connectedTo pipeBB valveBD)
		(connectedTo pipeDB pipeCB)
		(connectedTo valveBD tankLarge)



		(locatedAt pipeBA ba)
		(locatedAt pipeBB bb)
		(locatedAt pipeCB cb)
		(locatedAt pipeDB db)

		(Wall wall)
		(locatedAt wall ac)
		(locatedAt wall bc)
		(locatedAt wall cc)
		(locatedAt wall dc)

		(Wall wall2)

		(Wall wall3)




		

	)
	(:goal (and
		(forall (?wp) (or 
			(not (mko (WPConnectedToFailure ?wp)))
			(hasPicture auv ?wp)
			)
		)
		(not (exists (?wp) (and 
			(mko (WPTank ?wp))
			(mko (WPConnectedToFailure ?wp))
		))
		)
	)
	)
)
