(define (domain queens)
	(:requirements :strips :equality :disjunctive-preconditions :derived-predicates :negative-preconditions :conditional-effects :existential-preconditions)

(:predicates 
    (false)
    (true)
    (inconsistent)
	(Queen ?x)
  (Figure ?x)
	(rightdiagonal ?x ?y)
	(backdiagonal ?x ?y)
	(inline ?x ?y)
  (horinline ?x ?y)
  (verinline ?x ?y)
  (KBquery_Queen ?x)
  (KBquery_inline ?x ?y)
  (KBquery_Figure ?x)
)

    (:derived (true)
        (not (false))
    )

    (:derived (inconsistent) 
        (false)
    )

    (:derived (KBquery_Queen ?x)
        (or

            (and (= ?x aa) (Queen aa))
            (and (= ?x ab) (Queen ab))
            (and (= ?x ac) (Queen ac))
            (and (= ?x ad) (Queen ad))
            (and (= ?x ae) (Queen ae))
            (and (= ?x af) (Queen af))
            (and (= ?x ag) (Queen ag))
            (and (= ?x ah) (Queen ah))
            (and (= ?x ba) (Queen ba))
            (and (= ?x bb) (Queen bb))
            (and (= ?x bc) (Queen bc))
            (and (= ?x bd) (Queen bd))
            (and (= ?x be) (Queen be))
            (and (= ?x bf) (Queen bf))
            (and (= ?x bg) (Queen bg))
            (and (= ?x bh) (Queen bh))
            (and (= ?x ca) (Queen ca))
            (and (= ?x cb) (Queen cb))
            (and (= ?x cc) (Queen cc))
            (and (= ?x cd) (Queen cd))
            (and (= ?x ce) (Queen ce))
            (and (= ?x cf) (Queen cf))
            (and (= ?x cg) (Queen cg))
            (and (= ?x ch) (Queen ch))
            (and (= ?x da) (Queen da))
            (and (= ?x db) (Queen db))
            (and (= ?x dc) (Queen dc))
            (and (= ?x dd) (Queen dd))
            (and (= ?x de) (Queen de))
            (and (= ?x df) (Queen df))
            (and (= ?x dg) (Queen dg))
            (and (= ?x dh) (Queen dh))
            (and (= ?x ea) (Queen ea))
            (and (= ?x eb) (Queen eb))
            (and (= ?x ec) (Queen ec))
            (and (= ?x ed) (Queen ed))
            (and (= ?x ee) (Queen ee))
            (and (= ?x ef) (Queen ef))
            (and (= ?x eg) (Queen eg))
            (and (= ?x eh) (Queen eh))
            (and (= ?x fa) (Queen fa))
            (and (= ?x fb) (Queen fb))
            (and (= ?x fc) (Queen fc))
            (and (= ?x fd) (Queen fd))
            (and (= ?x fe) (Queen fe))
            (and (= ?x ff) (Queen ff))
            (and (= ?x fg) (Queen fg))
            (and (= ?x fh) (Queen fh))
            (and (= ?x ga) (Queen ga))
            (and (= ?x gb) (Queen gb))
            (and (= ?x gc) (Queen gc))
            (and (= ?x gd) (Queen gd))
            (and (= ?x ge) (Queen ge))
            (and (= ?x gf) (Queen gf))
            (and (= ?x gg) (Queen gg))
            (and (= ?x gh) (Queen gh))
            (and (= ?x ha) (Queen ha))
            (and (= ?x hb) (Queen hb))
            (and (= ?x hc) (Queen hc))
            (and (= ?x hd) (Queen hd))
            (and (= ?x he) (Queen he))
            (and (= ?x hf) (Queen hf))
            (and (= ?x hg) (Queen hg))
            (and (= ?x hh) (Queen hh))

        )
    )

    (:derived (KBquery_Figure ?x)
        (or

            (and (= ?x aa) (Queen aa))
            (and (= ?x ab) (Queen ab))
            (and (= ?x ac) (Queen ac))
            (and (= ?x ad) (Queen ad))
            (and (= ?x ae) (Queen ae))
            (and (= ?x af) (Queen af))
            (and (= ?x ag) (Queen ag))
            (and (= ?x ah) (Queen ah))
            (and (= ?x ba) (Queen ba))
            (and (= ?x bb) (Queen bb))
            (and (= ?x bc) (Queen bc))
            (and (= ?x bd) (Queen bd))
            (and (= ?x be) (Queen be))
            (and (= ?x bf) (Queen bf))
            (and (= ?x bg) (Queen bg))
            (and (= ?x bh) (Queen bh))
            (and (= ?x ca) (Queen ca))
            (and (= ?x cb) (Queen cb))
            (and (= ?x cc) (Queen cc))
            (and (= ?x cd) (Queen cd))
            (and (= ?x ce) (Queen ce))
            (and (= ?x cf) (Queen cf))
            (and (= ?x cg) (Queen cg))
            (and (= ?x ch) (Queen ch))
            (and (= ?x da) (Queen da))
            (and (= ?x db) (Queen db))
            (and (= ?x dc) (Queen dc))
            (and (= ?x dd) (Queen dd))
            (and (= ?x de) (Queen de))
            (and (= ?x df) (Queen df))
            (and (= ?x dg) (Queen dg))
            (and (= ?x dh) (Queen dh))
            (and (= ?x ea) (Queen ea))
            (and (= ?x eb) (Queen eb))
            (and (= ?x ec) (Queen ec))
            (and (= ?x ed) (Queen ed))
            (and (= ?x ee) (Queen ee))
            (and (= ?x ef) (Queen ef))
            (and (= ?x eg) (Queen eg))
            (and (= ?x eh) (Queen eh))
            (and (= ?x fa) (Queen fa))
            (and (= ?x fb) (Queen fb))
            (and (= ?x fc) (Queen fc))
            (and (= ?x fd) (Queen fd))
            (and (= ?x fe) (Queen fe))
            (and (= ?x ff) (Queen ff))
            (and (= ?x fg) (Queen fg))
            (and (= ?x fh) (Queen fh))
            (and (= ?x ga) (Queen ga))
            (and (= ?x gb) (Queen gb))
            (and (= ?x gc) (Queen gc))
            (and (= ?x gd) (Queen gd))
            (and (= ?x ge) (Queen ge))
            (and (= ?x gf) (Queen gf))
            (and (= ?x gg) (Queen gg))
            (and (= ?x gh) (Queen gh))
            (and (= ?x ha) (Queen ha))
            (and (= ?x hb) (Queen hb))
            (and (= ?x hc) (Queen hc))
            (and (= ?x hd) (Queen hd))
            (and (= ?x he) (Queen he))
            (and (= ?x hf) (Queen hf))
            (and (= ?x hg) (Queen hg))
            (and (= ?x hh) (Queen hh))

        )
    )

    (:derived (KBquery_Inline ?x ?y)
        (or

            (and (= ?y aa) (= ?x aa))
            (and (= ?y ab) (= ?x aa))
            (and (= ?y ac) (= ?x aa))
            (and (= ?y ad) (= ?x aa))
            (and (= ?y ae) (= ?x aa))
            (and (= ?y af) (= ?x aa))
            (and (= ?y ag) (= ?x aa))
            (and (= ?y ah) (= ?x aa))
            (and (= ?y ba) (= ?x aa))
            (and (= ?y bb) (= ?x aa))
            (and (= ?y ca) (= ?x aa))
            (and (= ?y cc) (= ?x aa))
            (and (= ?y da) (= ?x aa))
            (and (= ?y dd) (= ?x aa))
            (and (= ?y ea) (= ?x aa))
            (and (= ?y ee) (= ?x aa))
            (and (= ?y fa) (= ?x aa))
            (and (= ?y ff) (= ?x aa))
            (and (= ?y ga) (= ?x aa))
            (and (= ?y gg) (= ?x aa))
            (and (= ?y ha) (= ?x aa))
            (and (= ?y hh) (= ?x aa))
            (and (= ?y aa) (= ?x ab))
            (and (= ?y ab) (= ?x ab))
            (and (= ?y ac) (= ?x ab))
            (and (= ?y ad) (= ?x ab))
            (and (= ?y ae) (= ?x ab))
            (and (= ?y af) (= ?x ab))
            (and (= ?y ag) (= ?x ab))
            (and (= ?y ah) (= ?x ab))
            (and (= ?y ba) (= ?x ab))
            (and (= ?y bb) (= ?x ab))
            (and (= ?y bc) (= ?x ab))
            (and (= ?y cb) (= ?x ab))
            (and (= ?y cd) (= ?x ab))
            (and (= ?y db) (= ?x ab))
            (and (= ?y de) (= ?x ab))
            (and (= ?y eb) (= ?x ab))
            (and (= ?y ef) (= ?x ab))
            (and (= ?y fb) (= ?x ab))
            (and (= ?y fg) (= ?x ab))
            (and (= ?y gb) (= ?x ab))
            (and (= ?y gh) (= ?x ab))
            (and (= ?y hb) (= ?x ab))
            (and (= ?y aa) (= ?x ac))
            (and (= ?y ab) (= ?x ac))
            (and (= ?y ac) (= ?x ac))
            (and (= ?y ad) (= ?x ac))
            (and (= ?y ae) (= ?x ac))
            (and (= ?y af) (= ?x ac))
            (and (= ?y ag) (= ?x ac))
            (and (= ?y ah) (= ?x ac))
            (and (= ?y bb) (= ?x ac))
            (and (= ?y bc) (= ?x ac))
            (and (= ?y bd) (= ?x ac))
            (and (= ?y ca) (= ?x ac))
            (and (= ?y cc) (= ?x ac))
            (and (= ?y ce) (= ?x ac))
            (and (= ?y dc) (= ?x ac))
            (and (= ?y df) (= ?x ac))
            (and (= ?y ec) (= ?x ac))
            (and (= ?y eg) (= ?x ac))
            (and (= ?y fc) (= ?x ac))
            (and (= ?y fh) (= ?x ac))
            (and (= ?y gc) (= ?x ac))
            (and (= ?y hc) (= ?x ac))
            (and (= ?y aa) (= ?x ad))
            (and (= ?y ab) (= ?x ad))
            (and (= ?y ac) (= ?x ad))
            (and (= ?y ad) (= ?x ad))
            (and (= ?y ae) (= ?x ad))
            (and (= ?y af) (= ?x ad))
            (and (= ?y ag) (= ?x ad))
            (and (= ?y ah) (= ?x ad))
            (and (= ?y bc) (= ?x ad))
            (and (= ?y bd) (= ?x ad))
            (and (= ?y be) (= ?x ad))
            (and (= ?y cb) (= ?x ad))
            (and (= ?y cd) (= ?x ad))
            (and (= ?y cf) (= ?x ad))
            (and (= ?y da) (= ?x ad))
            (and (= ?y dd) (= ?x ad))
            (and (= ?y dg) (= ?x ad))
            (and (= ?y ed) (= ?x ad))
            (and (= ?y eh) (= ?x ad))
            (and (= ?y fd) (= ?x ad))
            (and (= ?y gd) (= ?x ad))
            (and (= ?y hd) (= ?x ad))
            (and (= ?y aa) (= ?x ae))
            (and (= ?y ab) (= ?x ae))
            (and (= ?y ac) (= ?x ae))
            (and (= ?y ad) (= ?x ae))
            (and (= ?y ae) (= ?x ae))
            (and (= ?y af) (= ?x ae))
            (and (= ?y ag) (= ?x ae))
            (and (= ?y ah) (= ?x ae))
            (and (= ?y bd) (= ?x ae))
            (and (= ?y be) (= ?x ae))
            (and (= ?y bf) (= ?x ae))
            (and (= ?y cc) (= ?x ae))
            (and (= ?y ce) (= ?x ae))
            (and (= ?y cg) (= ?x ae))
            (and (= ?y db) (= ?x ae))
            (and (= ?y de) (= ?x ae))
            (and (= ?y dh) (= ?x ae))
            (and (= ?y ea) (= ?x ae))
            (and (= ?y ee) (= ?x ae))
            (and (= ?y fe) (= ?x ae))
            (and (= ?y ge) (= ?x ae))
            (and (= ?y he) (= ?x ae))
            (and (= ?y aa) (= ?x af))
            (and (= ?y ab) (= ?x af))
            (and (= ?y ac) (= ?x af))
            (and (= ?y ad) (= ?x af))
            (and (= ?y ae) (= ?x af))
            (and (= ?y af) (= ?x af))
            (and (= ?y ag) (= ?x af))
            (and (= ?y ah) (= ?x af))
            (and (= ?y be) (= ?x af))
            (and (= ?y bf) (= ?x af))
            (and (= ?y bg) (= ?x af))
            (and (= ?y cd) (= ?x af))
            (and (= ?y cf) (= ?x af))
            (and (= ?y ch) (= ?x af))
            (and (= ?y dc) (= ?x af))
            (and (= ?y df) (= ?x af))
            (and (= ?y eb) (= ?x af))
            (and (= ?y ef) (= ?x af))
            (and (= ?y fa) (= ?x af))
            (and (= ?y ff) (= ?x af))
            (and (= ?y gf) (= ?x af))
            (and (= ?y hf) (= ?x af))
            (and (= ?y aa) (= ?x ag))
            (and (= ?y ab) (= ?x ag))
            (and (= ?y ac) (= ?x ag))
            (and (= ?y ad) (= ?x ag))
            (and (= ?y ae) (= ?x ag))
            (and (= ?y af) (= ?x ag))
            (and (= ?y ag) (= ?x ag))
            (and (= ?y ah) (= ?x ag))
            (and (= ?y bf) (= ?x ag))
            (and (= ?y bg) (= ?x ag))
            (and (= ?y bh) (= ?x ag))
            (and (= ?y ce) (= ?x ag))
            (and (= ?y cg) (= ?x ag))
            (and (= ?y dd) (= ?x ag))
            (and (= ?y dg) (= ?x ag))
            (and (= ?y ec) (= ?x ag))
            (and (= ?y eg) (= ?x ag))
            (and (= ?y fb) (= ?x ag))
            (and (= ?y fg) (= ?x ag))
            (and (= ?y ga) (= ?x ag))
            (and (= ?y gg) (= ?x ag))
            (and (= ?y hg) (= ?x ag))
            (and (= ?y aa) (= ?x ah))
            (and (= ?y ab) (= ?x ah))
            (and (= ?y ac) (= ?x ah))
            (and (= ?y ad) (= ?x ah))
            (and (= ?y ae) (= ?x ah))
            (and (= ?y af) (= ?x ah))
            (and (= ?y ag) (= ?x ah))
            (and (= ?y ah) (= ?x ah))
            (and (= ?y bg) (= ?x ah))
            (and (= ?y bh) (= ?x ah))
            (and (= ?y cf) (= ?x ah))
            (and (= ?y ch) (= ?x ah))
            (and (= ?y de) (= ?x ah))
            (and (= ?y dh) (= ?x ah))
            (and (= ?y ed) (= ?x ah))
            (and (= ?y eh) (= ?x ah))
            (and (= ?y fc) (= ?x ah))
            (and (= ?y fh) (= ?x ah))
            (and (= ?y gb) (= ?x ah))
            (and (= ?y gh) (= ?x ah))
            (and (= ?y ha) (= ?x ah))
            (and (= ?y hh) (= ?x ah))
            (and (= ?y aa) (= ?x ba))
            (and (= ?y ab) (= ?x ba))
            (and (= ?y ba) (= ?x ba))
            (and (= ?y bb) (= ?x ba))
            (and (= ?y bc) (= ?x ba))
            (and (= ?y bd) (= ?x ba))
            (and (= ?y be) (= ?x ba))
            (and (= ?y bf) (= ?x ba))
            (and (= ?y bg) (= ?x ba))
            (and (= ?y bh) (= ?x ba))
            (and (= ?y ca) (= ?x ba))
            (and (= ?y cb) (= ?x ba))
            (and (= ?y da) (= ?x ba))
            (and (= ?y dc) (= ?x ba))
            (and (= ?y ea) (= ?x ba))
            (and (= ?y ed) (= ?x ba))
            (and (= ?y fa) (= ?x ba))
            (and (= ?y fe) (= ?x ba))
            (and (= ?y ga) (= ?x ba))
            (and (= ?y gf) (= ?x ba))
            (and (= ?y ha) (= ?x ba))
            (and (= ?y hg) (= ?x ba))
            (and (= ?y aa) (= ?x bb))
            (and (= ?y ab) (= ?x bb))
            (and (= ?y ac) (= ?x bb))
            (and (= ?y ba) (= ?x bb))
            (and (= ?y bb) (= ?x bb))
            (and (= ?y bc) (= ?x bb))
            (and (= ?y bd) (= ?x bb))
            (and (= ?y be) (= ?x bb))
            (and (= ?y bf) (= ?x bb))
            (and (= ?y bg) (= ?x bb))
            (and (= ?y bh) (= ?x bb))
            (and (= ?y ca) (= ?x bb))
            (and (= ?y cb) (= ?x bb))
            (and (= ?y cc) (= ?x bb))
            (and (= ?y db) (= ?x bb))
            (and (= ?y dd) (= ?x bb))
            (and (= ?y eb) (= ?x bb))
            (and (= ?y ee) (= ?x bb))
            (and (= ?y fb) (= ?x bb))
            (and (= ?y ff) (= ?x bb))
            (and (= ?y gb) (= ?x bb))
            (and (= ?y gg) (= ?x bb))
            (and (= ?y hb) (= ?x bb))
            (and (= ?y hh) (= ?x bb))
            (and (= ?y ab) (= ?x bc))
            (and (= ?y ac) (= ?x bc))
            (and (= ?y ad) (= ?x bc))
            (and (= ?y ba) (= ?x bc))
            (and (= ?y bb) (= ?x bc))
            (and (= ?y bc) (= ?x bc))
            (and (= ?y bd) (= ?x bc))
            (and (= ?y be) (= ?x bc))
            (and (= ?y bf) (= ?x bc))
            (and (= ?y bg) (= ?x bc))
            (and (= ?y bh) (= ?x bc))
            (and (= ?y cb) (= ?x bc))
            (and (= ?y cc) (= ?x bc))
            (and (= ?y cd) (= ?x bc))
            (and (= ?y da) (= ?x bc))
            (and (= ?y dc) (= ?x bc))
            (and (= ?y de) (= ?x bc))
            (and (= ?y ec) (= ?x bc))
            (and (= ?y ef) (= ?x bc))
            (and (= ?y fc) (= ?x bc))
            (and (= ?y fg) (= ?x bc))
            (and (= ?y gc) (= ?x bc))
            (and (= ?y gh) (= ?x bc))
            (and (= ?y hc) (= ?x bc))
            (and (= ?y ac) (= ?x bd))
            (and (= ?y ad) (= ?x bd))
            (and (= ?y ae) (= ?x bd))
            (and (= ?y ba) (= ?x bd))
            (and (= ?y bb) (= ?x bd))
            (and (= ?y bc) (= ?x bd))
            (and (= ?y bd) (= ?x bd))
            (and (= ?y be) (= ?x bd))
            (and (= ?y bf) (= ?x bd))
            (and (= ?y bg) (= ?x bd))
            (and (= ?y bh) (= ?x bd))
            (and (= ?y cc) (= ?x bd))
            (and (= ?y cd) (= ?x bd))
            (and (= ?y ce) (= ?x bd))
            (and (= ?y db) (= ?x bd))
            (and (= ?y dd) (= ?x bd))
            (and (= ?y df) (= ?x bd))
            (and (= ?y ea) (= ?x bd))
            (and (= ?y ed) (= ?x bd))
            (and (= ?y eg) (= ?x bd))
            (and (= ?y fd) (= ?x bd))
            (and (= ?y fh) (= ?x bd))
            (and (= ?y gd) (= ?x bd))
            (and (= ?y hd) (= ?x bd))
            (and (= ?y ad) (= ?x be))
            (and (= ?y ae) (= ?x be))
            (and (= ?y af) (= ?x be))
            (and (= ?y ba) (= ?x be))
            (and (= ?y bb) (= ?x be))
            (and (= ?y bc) (= ?x be))
            (and (= ?y bd) (= ?x be))
            (and (= ?y be) (= ?x be))
            (and (= ?y bf) (= ?x be))
            (and (= ?y bg) (= ?x be))
            (and (= ?y bh) (= ?x be))
            (and (= ?y cd) (= ?x be))
            (and (= ?y ce) (= ?x be))
            (and (= ?y cf) (= ?x be))
            (and (= ?y dc) (= ?x be))
            (and (= ?y de) (= ?x be))
            (and (= ?y dg) (= ?x be))
            (and (= ?y eb) (= ?x be))
            (and (= ?y ee) (= ?x be))
            (and (= ?y eh) (= ?x be))
            (and (= ?y fa) (= ?x be))
            (and (= ?y fe) (= ?x be))
            (and (= ?y ge) (= ?x be))
            (and (= ?y he) (= ?x be))
            (and (= ?y ae) (= ?x bf))
            (and (= ?y af) (= ?x bf))
            (and (= ?y ag) (= ?x bf))
            (and (= ?y ba) (= ?x bf))
            (and (= ?y bb) (= ?x bf))
            (and (= ?y bc) (= ?x bf))
            (and (= ?y bd) (= ?x bf))
            (and (= ?y be) (= ?x bf))
            (and (= ?y bf) (= ?x bf))
            (and (= ?y bg) (= ?x bf))
            (and (= ?y bh) (= ?x bf))
            (and (= ?y ce) (= ?x bf))
            (and (= ?y cf) (= ?x bf))
            (and (= ?y cg) (= ?x bf))
            (and (= ?y dd) (= ?x bf))
            (and (= ?y df) (= ?x bf))
            (and (= ?y dh) (= ?x bf))
            (and (= ?y ec) (= ?x bf))
            (and (= ?y ef) (= ?x bf))
            (and (= ?y fb) (= ?x bf))
            (and (= ?y ff) (= ?x bf))
            (and (= ?y ga) (= ?x bf))
            (and (= ?y gf) (= ?x bf))
            (and (= ?y hf) (= ?x bf))
            (and (= ?y af) (= ?x bg))
            (and (= ?y ag) (= ?x bg))
            (and (= ?y ah) (= ?x bg))
            (and (= ?y ba) (= ?x bg))
            (and (= ?y bb) (= ?x bg))
            (and (= ?y bc) (= ?x bg))
            (and (= ?y bd) (= ?x bg))
            (and (= ?y be) (= ?x bg))
            (and (= ?y bf) (= ?x bg))
            (and (= ?y bg) (= ?x bg))
            (and (= ?y bh) (= ?x bg))
            (and (= ?y cf) (= ?x bg))
            (and (= ?y cg) (= ?x bg))
            (and (= ?y ch) (= ?x bg))
            (and (= ?y de) (= ?x bg))
            (and (= ?y dg) (= ?x bg))
            (and (= ?y ed) (= ?x bg))
            (and (= ?y eg) (= ?x bg))
            (and (= ?y fc) (= ?x bg))
            (and (= ?y fg) (= ?x bg))
            (and (= ?y gb) (= ?x bg))
            (and (= ?y gg) (= ?x bg))
            (and (= ?y ha) (= ?x bg))
            (and (= ?y hg) (= ?x bg))
            (and (= ?y ag) (= ?x bh))
            (and (= ?y ah) (= ?x bh))
            (and (= ?y ba) (= ?x bh))
            (and (= ?y bb) (= ?x bh))
            (and (= ?y bc) (= ?x bh))
            (and (= ?y bd) (= ?x bh))
            (and (= ?y be) (= ?x bh))
            (and (= ?y bf) (= ?x bh))
            (and (= ?y bg) (= ?x bh))
            (and (= ?y bh) (= ?x bh))
            (and (= ?y cg) (= ?x bh))
            (and (= ?y ch) (= ?x bh))
            (and (= ?y df) (= ?x bh))
            (and (= ?y dh) (= ?x bh))
            (and (= ?y ee) (= ?x bh))
            (and (= ?y eh) (= ?x bh))
            (and (= ?y fd) (= ?x bh))
            (and (= ?y fh) (= ?x bh))
            (and (= ?y gc) (= ?x bh))
            (and (= ?y gh) (= ?x bh))
            (and (= ?y hb) (= ?x bh))
            (and (= ?y hh) (= ?x bh))
            (and (= ?y aa) (= ?x ca))
            (and (= ?y ac) (= ?x ca))
            (and (= ?y ba) (= ?x ca))
            (and (= ?y bb) (= ?x ca))
            (and (= ?y ca) (= ?x ca))
            (and (= ?y cb) (= ?x ca))
            (and (= ?y cc) (= ?x ca))
            (and (= ?y cd) (= ?x ca))
            (and (= ?y ce) (= ?x ca))
            (and (= ?y cf) (= ?x ca))
            (and (= ?y cg) (= ?x ca))
            (and (= ?y ch) (= ?x ca))
            (and (= ?y da) (= ?x ca))
            (and (= ?y db) (= ?x ca))
            (and (= ?y ea) (= ?x ca))
            (and (= ?y ec) (= ?x ca))
            (and (= ?y fa) (= ?x ca))
            (and (= ?y fd) (= ?x ca))
            (and (= ?y ga) (= ?x ca))
            (and (= ?y ge) (= ?x ca))
            (and (= ?y ha) (= ?x ca))
            (and (= ?y hf) (= ?x ca))
            (and (= ?y ab) (= ?x cb))
            (and (= ?y ad) (= ?x cb))
            (and (= ?y ba) (= ?x cb))
            (and (= ?y bb) (= ?x cb))
            (and (= ?y bc) (= ?x cb))
            (and (= ?y ca) (= ?x cb))
            (and (= ?y cb) (= ?x cb))
            (and (= ?y cc) (= ?x cb))
            (and (= ?y cd) (= ?x cb))
            (and (= ?y ce) (= ?x cb))
            (and (= ?y cf) (= ?x cb))
            (and (= ?y cg) (= ?x cb))
            (and (= ?y ch) (= ?x cb))
            (and (= ?y da) (= ?x cb))
            (and (= ?y db) (= ?x cb))
            (and (= ?y dc) (= ?x cb))
            (and (= ?y eb) (= ?x cb))
            (and (= ?y ed) (= ?x cb))
            (and (= ?y fb) (= ?x cb))
            (and (= ?y fe) (= ?x cb))
            (and (= ?y gb) (= ?x cb))
            (and (= ?y gf) (= ?x cb))
            (and (= ?y hb) (= ?x cb))
            (and (= ?y hg) (= ?x cb))
            (and (= ?y aa) (= ?x cc))
            (and (= ?y ac) (= ?x cc))
            (and (= ?y ae) (= ?x cc))
            (and (= ?y bb) (= ?x cc))
            (and (= ?y bc) (= ?x cc))
            (and (= ?y bd) (= ?x cc))
            (and (= ?y ca) (= ?x cc))
            (and (= ?y cb) (= ?x cc))
            (and (= ?y cc) (= ?x cc))
            (and (= ?y cd) (= ?x cc))
            (and (= ?y ce) (= ?x cc))
            (and (= ?y cf) (= ?x cc))
            (and (= ?y cg) (= ?x cc))
            (and (= ?y ch) (= ?x cc))
            (and (= ?y db) (= ?x cc))
            (and (= ?y dc) (= ?x cc))
            (and (= ?y dd) (= ?x cc))
            (and (= ?y ea) (= ?x cc))
            (and (= ?y ec) (= ?x cc))
            (and (= ?y ee) (= ?x cc))
            (and (= ?y fc) (= ?x cc))
            (and (= ?y ff) (= ?x cc))
            (and (= ?y gc) (= ?x cc))
            (and (= ?y gg) (= ?x cc))
            (and (= ?y hc) (= ?x cc))
            (and (= ?y hh) (= ?x cc))
            (and (= ?y ab) (= ?x cd))
            (and (= ?y ad) (= ?x cd))
            (and (= ?y af) (= ?x cd))
            (and (= ?y bc) (= ?x cd))
            (and (= ?y bd) (= ?x cd))
            (and (= ?y be) (= ?x cd))
            (and (= ?y ca) (= ?x cd))
            (and (= ?y cb) (= ?x cd))
            (and (= ?y cc) (= ?x cd))
            (and (= ?y cd) (= ?x cd))
            (and (= ?y ce) (= ?x cd))
            (and (= ?y cf) (= ?x cd))
            (and (= ?y cg) (= ?x cd))
            (and (= ?y ch) (= ?x cd))
            (and (= ?y dc) (= ?x cd))
            (and (= ?y dd) (= ?x cd))
            (and (= ?y de) (= ?x cd))
            (and (= ?y eb) (= ?x cd))
            (and (= ?y ed) (= ?x cd))
            (and (= ?y ef) (= ?x cd))
            (and (= ?y fa) (= ?x cd))
            (and (= ?y fd) (= ?x cd))
            (and (= ?y fg) (= ?x cd))
            (and (= ?y gd) (= ?x cd))
            (and (= ?y gh) (= ?x cd))
            (and (= ?y hd) (= ?x cd))
            (and (= ?y ac) (= ?x ce))
            (and (= ?y ae) (= ?x ce))
            (and (= ?y ag) (= ?x ce))
            (and (= ?y bd) (= ?x ce))
            (and (= ?y be) (= ?x ce))
            (and (= ?y bf) (= ?x ce))
            (and (= ?y ca) (= ?x ce))
            (and (= ?y cb) (= ?x ce))
            (and (= ?y cc) (= ?x ce))
            (and (= ?y cd) (= ?x ce))
            (and (= ?y ce) (= ?x ce))
            (and (= ?y cf) (= ?x ce))
            (and (= ?y cg) (= ?x ce))
            (and (= ?y ch) (= ?x ce))
            (and (= ?y dd) (= ?x ce))
            (and (= ?y de) (= ?x ce))
            (and (= ?y df) (= ?x ce))
            (and (= ?y ec) (= ?x ce))
            (and (= ?y ee) (= ?x ce))
            (and (= ?y eg) (= ?x ce))
            (and (= ?y fb) (= ?x ce))
            (and (= ?y fe) (= ?x ce))
            (and (= ?y fh) (= ?x ce))
            (and (= ?y ga) (= ?x ce))
            (and (= ?y ge) (= ?x ce))
            (and (= ?y he) (= ?x ce))
            (and (= ?y ad) (= ?x cf))
            (and (= ?y af) (= ?x cf))
            (and (= ?y ah) (= ?x cf))
            (and (= ?y be) (= ?x cf))
            (and (= ?y bf) (= ?x cf))
            (and (= ?y bg) (= ?x cf))
            (and (= ?y ca) (= ?x cf))
            (and (= ?y cb) (= ?x cf))
            (and (= ?y cc) (= ?x cf))
            (and (= ?y cd) (= ?x cf))
            (and (= ?y ce) (= ?x cf))
            (and (= ?y cf) (= ?x cf))
            (and (= ?y cg) (= ?x cf))
            (and (= ?y ch) (= ?x cf))
            (and (= ?y de) (= ?x cf))
            (and (= ?y df) (= ?x cf))
            (and (= ?y dg) (= ?x cf))
            (and (= ?y ed) (= ?x cf))
            (and (= ?y ef) (= ?x cf))
            (and (= ?y eh) (= ?x cf))
            (and (= ?y fc) (= ?x cf))
            (and (= ?y ff) (= ?x cf))
            (and (= ?y gb) (= ?x cf))
            (and (= ?y gf) (= ?x cf))
            (and (= ?y ha) (= ?x cf))
            (and (= ?y hf) (= ?x cf))
            (and (= ?y ae) (= ?x cg))
            (and (= ?y ag) (= ?x cg))
            (and (= ?y bf) (= ?x cg))
            (and (= ?y bg) (= ?x cg))
            (and (= ?y bh) (= ?x cg))
            (and (= ?y ca) (= ?x cg))
            (and (= ?y cb) (= ?x cg))
            (and (= ?y cc) (= ?x cg))
            (and (= ?y cd) (= ?x cg))
            (and (= ?y ce) (= ?x cg))
            (and (= ?y cf) (= ?x cg))
            (and (= ?y cg) (= ?x cg))
            (and (= ?y ch) (= ?x cg))
            (and (= ?y df) (= ?x cg))
            (and (= ?y dg) (= ?x cg))
            (and (= ?y dh) (= ?x cg))
            (and (= ?y ee) (= ?x cg))
            (and (= ?y eg) (= ?x cg))
            (and (= ?y fd) (= ?x cg))
            (and (= ?y fg) (= ?x cg))
            (and (= ?y gc) (= ?x cg))
            (and (= ?y gg) (= ?x cg))
            (and (= ?y hb) (= ?x cg))
            (and (= ?y hg) (= ?x cg))
            (and (= ?y af) (= ?x ch))
            (and (= ?y ah) (= ?x ch))
            (and (= ?y bg) (= ?x ch))
            (and (= ?y bh) (= ?x ch))
            (and (= ?y ca) (= ?x ch))
            (and (= ?y cb) (= ?x ch))
            (and (= ?y cc) (= ?x ch))
            (and (= ?y cd) (= ?x ch))
            (and (= ?y ce) (= ?x ch))
            (and (= ?y cf) (= ?x ch))
            (and (= ?y cg) (= ?x ch))
            (and (= ?y ch) (= ?x ch))
            (and (= ?y dg) (= ?x ch))
            (and (= ?y dh) (= ?x ch))
            (and (= ?y ef) (= ?x ch))
            (and (= ?y eh) (= ?x ch))
            (and (= ?y fe) (= ?x ch))
            (and (= ?y fh) (= ?x ch))
            (and (= ?y gd) (= ?x ch))
            (and (= ?y gh) (= ?x ch))
            (and (= ?y hc) (= ?x ch))
            (and (= ?y hh) (= ?x ch))
            (and (= ?y aa) (= ?x da))
            (and (= ?y ad) (= ?x da))
            (and (= ?y ba) (= ?x da))
            (and (= ?y bc) (= ?x da))
            (and (= ?y ca) (= ?x da))
            (and (= ?y cb) (= ?x da))
            (and (= ?y da) (= ?x da))
            (and (= ?y db) (= ?x da))
            (and (= ?y dc) (= ?x da))
            (and (= ?y dd) (= ?x da))
            (and (= ?y de) (= ?x da))
            (and (= ?y df) (= ?x da))
            (and (= ?y dg) (= ?x da))
            (and (= ?y dh) (= ?x da))
            (and (= ?y ea) (= ?x da))
            (and (= ?y eb) (= ?x da))
            (and (= ?y fa) (= ?x da))
            (and (= ?y fc) (= ?x da))
            (and (= ?y ga) (= ?x da))
            (and (= ?y gd) (= ?x da))
            (and (= ?y ha) (= ?x da))
            (and (= ?y he) (= ?x da))
            (and (= ?y ab) (= ?x db))
            (and (= ?y ae) (= ?x db))
            (and (= ?y bb) (= ?x db))
            (and (= ?y bd) (= ?x db))
            (and (= ?y ca) (= ?x db))
            (and (= ?y cb) (= ?x db))
            (and (= ?y cc) (= ?x db))
            (and (= ?y da) (= ?x db))
            (and (= ?y db) (= ?x db))
            (and (= ?y dc) (= ?x db))
            (and (= ?y dd) (= ?x db))
            (and (= ?y de) (= ?x db))
            (and (= ?y df) (= ?x db))
            (and (= ?y dg) (= ?x db))
            (and (= ?y dh) (= ?x db))
            (and (= ?y ea) (= ?x db))
            (and (= ?y eb) (= ?x db))
            (and (= ?y ec) (= ?x db))
            (and (= ?y fb) (= ?x db))
            (and (= ?y fd) (= ?x db))
            (and (= ?y gb) (= ?x db))
            (and (= ?y ge) (= ?x db))
            (and (= ?y hb) (= ?x db))
            (and (= ?y hf) (= ?x db))
            (and (= ?y ac) (= ?x dc))
            (and (= ?y af) (= ?x dc))
            (and (= ?y ba) (= ?x dc))
            (and (= ?y bc) (= ?x dc))
            (and (= ?y be) (= ?x dc))
            (and (= ?y cb) (= ?x dc))
            (and (= ?y cc) (= ?x dc))
            (and (= ?y cd) (= ?x dc))
            (and (= ?y da) (= ?x dc))
            (and (= ?y db) (= ?x dc))
            (and (= ?y dc) (= ?x dc))
            (and (= ?y dd) (= ?x dc))
            (and (= ?y de) (= ?x dc))
            (and (= ?y df) (= ?x dc))
            (and (= ?y dg) (= ?x dc))
            (and (= ?y dh) (= ?x dc))
            (and (= ?y eb) (= ?x dc))
            (and (= ?y ec) (= ?x dc))
            (and (= ?y ed) (= ?x dc))
            (and (= ?y fa) (= ?x dc))
            (and (= ?y fc) (= ?x dc))
            (and (= ?y fe) (= ?x dc))
            (and (= ?y gc) (= ?x dc))
            (and (= ?y gf) (= ?x dc))
            (and (= ?y hc) (= ?x dc))
            (and (= ?y hg) (= ?x dc))
            (and (= ?y aa) (= ?x dd))
            (and (= ?y ad) (= ?x dd))
            (and (= ?y ag) (= ?x dd))
            (and (= ?y bb) (= ?x dd))
            (and (= ?y bd) (= ?x dd))
            (and (= ?y bf) (= ?x dd))
            (and (= ?y cc) (= ?x dd))
            (and (= ?y cd) (= ?x dd))
            (and (= ?y ce) (= ?x dd))
            (and (= ?y da) (= ?x dd))
            (and (= ?y db) (= ?x dd))
            (and (= ?y dc) (= ?x dd))
            (and (= ?y dd) (= ?x dd))
            (and (= ?y de) (= ?x dd))
            (and (= ?y df) (= ?x dd))
            (and (= ?y dg) (= ?x dd))
            (and (= ?y dh) (= ?x dd))
            (and (= ?y ec) (= ?x dd))
            (and (= ?y ed) (= ?x dd))
            (and (= ?y ee) (= ?x dd))
            (and (= ?y fb) (= ?x dd))
            (and (= ?y fd) (= ?x dd))
            (and (= ?y ff) (= ?x dd))
            (and (= ?y ga) (= ?x dd))
            (and (= ?y gd) (= ?x dd))
            (and (= ?y gg) (= ?x dd))
            (and (= ?y hd) (= ?x dd))
            (and (= ?y hh) (= ?x dd))
            (and (= ?y ab) (= ?x de))
            (and (= ?y ae) (= ?x de))
            (and (= ?y ah) (= ?x de))
            (and (= ?y bc) (= ?x de))
            (and (= ?y be) (= ?x de))
            (and (= ?y bg) (= ?x de))
            (and (= ?y cd) (= ?x de))
            (and (= ?y ce) (= ?x de))
            (and (= ?y cf) (= ?x de))
            (and (= ?y da) (= ?x de))
            (and (= ?y db) (= ?x de))
            (and (= ?y dc) (= ?x de))
            (and (= ?y dd) (= ?x de))
            (and (= ?y de) (= ?x de))
            (and (= ?y df) (= ?x de))
            (and (= ?y dg) (= ?x de))
            (and (= ?y dh) (= ?x de))
            (and (= ?y ed) (= ?x de))
            (and (= ?y ee) (= ?x de))
            (and (= ?y ef) (= ?x de))
            (and (= ?y fc) (= ?x de))
            (and (= ?y fe) (= ?x de))
            (and (= ?y fg) (= ?x de))
            (and (= ?y gb) (= ?x de))
            (and (= ?y ge) (= ?x de))
            (and (= ?y gh) (= ?x de))
            (and (= ?y ha) (= ?x de))
            (and (= ?y he) (= ?x de))
            (and (= ?y ac) (= ?x df))
            (and (= ?y af) (= ?x df))
            (and (= ?y bd) (= ?x df))
            (and (= ?y bf) (= ?x df))
            (and (= ?y bh) (= ?x df))
            (and (= ?y ce) (= ?x df))
            (and (= ?y cf) (= ?x df))
            (and (= ?y cg) (= ?x df))
            (and (= ?y da) (= ?x df))
            (and (= ?y db) (= ?x df))
            (and (= ?y dc) (= ?x df))
            (and (= ?y dd) (= ?x df))
            (and (= ?y de) (= ?x df))
            (and (= ?y df) (= ?x df))
            (and (= ?y dg) (= ?x df))
            (and (= ?y dh) (= ?x df))
            (and (= ?y ee) (= ?x df))
            (and (= ?y ef) (= ?x df))
            (and (= ?y eg) (= ?x df))
            (and (= ?y fd) (= ?x df))
            (and (= ?y ff) (= ?x df))
            (and (= ?y fh) (= ?x df))
            (and (= ?y gc) (= ?x df))
            (and (= ?y gf) (= ?x df))
            (and (= ?y hb) (= ?x df))
            (and (= ?y hf) (= ?x df))
            (and (= ?y ad) (= ?x dg))
            (and (= ?y ag) (= ?x dg))
            (and (= ?y be) (= ?x dg))
            (and (= ?y bg) (= ?x dg))
            (and (= ?y cf) (= ?x dg))
            (and (= ?y cg) (= ?x dg))
            (and (= ?y ch) (= ?x dg))
            (and (= ?y da) (= ?x dg))
            (and (= ?y db) (= ?x dg))
            (and (= ?y dc) (= ?x dg))
            (and (= ?y dd) (= ?x dg))
            (and (= ?y de) (= ?x dg))
            (and (= ?y df) (= ?x dg))
            (and (= ?y dg) (= ?x dg))
            (and (= ?y dh) (= ?x dg))
            (and (= ?y ef) (= ?x dg))
            (and (= ?y eg) (= ?x dg))
            (and (= ?y eh) (= ?x dg))
            (and (= ?y fe) (= ?x dg))
            (and (= ?y fg) (= ?x dg))
            (and (= ?y gd) (= ?x dg))
            (and (= ?y gg) (= ?x dg))
            (and (= ?y hc) (= ?x dg))
            (and (= ?y hg) (= ?x dg))
            (and (= ?y ae) (= ?x dh))
            (and (= ?y ah) (= ?x dh))
            (and (= ?y bf) (= ?x dh))
            (and (= ?y bh) (= ?x dh))
            (and (= ?y cg) (= ?x dh))
            (and (= ?y ch) (= ?x dh))
            (and (= ?y da) (= ?x dh))
            (and (= ?y db) (= ?x dh))
            (and (= ?y dc) (= ?x dh))
            (and (= ?y dd) (= ?x dh))
            (and (= ?y de) (= ?x dh))
            (and (= ?y df) (= ?x dh))
            (and (= ?y dg) (= ?x dh))
            (and (= ?y dh) (= ?x dh))
            (and (= ?y eg) (= ?x dh))
            (and (= ?y eh) (= ?x dh))
            (and (= ?y ff) (= ?x dh))
            (and (= ?y fh) (= ?x dh))
            (and (= ?y ge) (= ?x dh))
            (and (= ?y gh) (= ?x dh))
            (and (= ?y hd) (= ?x dh))
            (and (= ?y hh) (= ?x dh))
            (and (= ?y aa) (= ?x ea))
            (and (= ?y ae) (= ?x ea))
            (and (= ?y ba) (= ?x ea))
            (and (= ?y bd) (= ?x ea))
            (and (= ?y ca) (= ?x ea))
            (and (= ?y cc) (= ?x ea))
            (and (= ?y da) (= ?x ea))
            (and (= ?y db) (= ?x ea))
            (and (= ?y ea) (= ?x ea))
            (and (= ?y eb) (= ?x ea))
            (and (= ?y ec) (= ?x ea))
            (and (= ?y ed) (= ?x ea))
            (and (= ?y ee) (= ?x ea))
            (and (= ?y ef) (= ?x ea))
            (and (= ?y eg) (= ?x ea))
            (and (= ?y eh) (= ?x ea))
            (and (= ?y fa) (= ?x ea))
            (and (= ?y fb) (= ?x ea))
            (and (= ?y ga) (= ?x ea))
            (and (= ?y gc) (= ?x ea))
            (and (= ?y ha) (= ?x ea))
            (and (= ?y hd) (= ?x ea))
            (and (= ?y ab) (= ?x eb))
            (and (= ?y af) (= ?x eb))
            (and (= ?y bb) (= ?x eb))
            (and (= ?y be) (= ?x eb))
            (and (= ?y cb) (= ?x eb))
            (and (= ?y cd) (= ?x eb))
            (and (= ?y da) (= ?x eb))
            (and (= ?y db) (= ?x eb))
            (and (= ?y dc) (= ?x eb))
            (and (= ?y ea) (= ?x eb))
            (and (= ?y eb) (= ?x eb))
            (and (= ?y ec) (= ?x eb))
            (and (= ?y ed) (= ?x eb))
            (and (= ?y ee) (= ?x eb))
            (and (= ?y ef) (= ?x eb))
            (and (= ?y eg) (= ?x eb))
            (and (= ?y eh) (= ?x eb))
            (and (= ?y fa) (= ?x eb))
            (and (= ?y fb) (= ?x eb))
            (and (= ?y fc) (= ?x eb))
            (and (= ?y gb) (= ?x eb))
            (and (= ?y gd) (= ?x eb))
            (and (= ?y hb) (= ?x eb))
            (and (= ?y he) (= ?x eb))
            (and (= ?y ac) (= ?x ec))
            (and (= ?y ag) (= ?x ec))
            (and (= ?y bc) (= ?x ec))
            (and (= ?y bf) (= ?x ec))
            (and (= ?y ca) (= ?x ec))
            (and (= ?y cc) (= ?x ec))
            (and (= ?y ce) (= ?x ec))
            (and (= ?y db) (= ?x ec))
            (and (= ?y dc) (= ?x ec))
            (and (= ?y dd) (= ?x ec))
            (and (= ?y ea) (= ?x ec))
            (and (= ?y eb) (= ?x ec))
            (and (= ?y ec) (= ?x ec))
            (and (= ?y ed) (= ?x ec))
            (and (= ?y ee) (= ?x ec))
            (and (= ?y ef) (= ?x ec))
            (and (= ?y eg) (= ?x ec))
            (and (= ?y eh) (= ?x ec))
            (and (= ?y fb) (= ?x ec))
            (and (= ?y fc) (= ?x ec))
            (and (= ?y fd) (= ?x ec))
            (and (= ?y ga) (= ?x ec))
            (and (= ?y gc) (= ?x ec))
            (and (= ?y ge) (= ?x ec))
            (and (= ?y hc) (= ?x ec))
            (and (= ?y hf) (= ?x ec))
            (and (= ?y ad) (= ?x ed))
            (and (= ?y ah) (= ?x ed))
            (and (= ?y ba) (= ?x ed))
            (and (= ?y bd) (= ?x ed))
            (and (= ?y bg) (= ?x ed))
            (and (= ?y cb) (= ?x ed))
            (and (= ?y cd) (= ?x ed))
            (and (= ?y cf) (= ?x ed))
            (and (= ?y dc) (= ?x ed))
            (and (= ?y dd) (= ?x ed))
            (and (= ?y de) (= ?x ed))
            (and (= ?y ea) (= ?x ed))
            (and (= ?y eb) (= ?x ed))
            (and (= ?y ec) (= ?x ed))
            (and (= ?y ed) (= ?x ed))
            (and (= ?y ee) (= ?x ed))
            (and (= ?y ef) (= ?x ed))
            (and (= ?y eg) (= ?x ed))
            (and (= ?y eh) (= ?x ed))
            (and (= ?y fc) (= ?x ed))
            (and (= ?y fd) (= ?x ed))
            (and (= ?y fe) (= ?x ed))
            (and (= ?y gb) (= ?x ed))
            (and (= ?y gd) (= ?x ed))
            (and (= ?y gf) (= ?x ed))
            (and (= ?y ha) (= ?x ed))
            (and (= ?y hd) (= ?x ed))
            (and (= ?y hg) (= ?x ed))
            (and (= ?y aa) (= ?x ee))
            (and (= ?y ae) (= ?x ee))
            (and (= ?y bb) (= ?x ee))
            (and (= ?y be) (= ?x ee))
            (and (= ?y bh) (= ?x ee))
            (and (= ?y cc) (= ?x ee))
            (and (= ?y ce) (= ?x ee))
            (and (= ?y cg) (= ?x ee))
            (and (= ?y dd) (= ?x ee))
            (and (= ?y de) (= ?x ee))
            (and (= ?y df) (= ?x ee))
            (and (= ?y ea) (= ?x ee))
            (and (= ?y eb) (= ?x ee))
            (and (= ?y ec) (= ?x ee))
            (and (= ?y ed) (= ?x ee))
            (and (= ?y ee) (= ?x ee))
            (and (= ?y ef) (= ?x ee))
            (and (= ?y eg) (= ?x ee))
            (and (= ?y eh) (= ?x ee))
            (and (= ?y fd) (= ?x ee))
            (and (= ?y fe) (= ?x ee))
            (and (= ?y ff) (= ?x ee))
            (and (= ?y gc) (= ?x ee))
            (and (= ?y ge) (= ?x ee))
            (and (= ?y gg) (= ?x ee))
            (and (= ?y hb) (= ?x ee))
            (and (= ?y he) (= ?x ee))
            (and (= ?y hh) (= ?x ee))
            (and (= ?y ab) (= ?x ef))
            (and (= ?y af) (= ?x ef))
            (and (= ?y bc) (= ?x ef))
            (and (= ?y bf) (= ?x ef))
            (and (= ?y cd) (= ?x ef))
            (and (= ?y cf) (= ?x ef))
            (and (= ?y ch) (= ?x ef))
            (and (= ?y de) (= ?x ef))
            (and (= ?y df) (= ?x ef))
            (and (= ?y dg) (= ?x ef))
            (and (= ?y ea) (= ?x ef))
            (and (= ?y eb) (= ?x ef))
            (and (= ?y ec) (= ?x ef))
            (and (= ?y ed) (= ?x ef))
            (and (= ?y ee) (= ?x ef))
            (and (= ?y ef) (= ?x ef))
            (and (= ?y eg) (= ?x ef))
            (and (= ?y eh) (= ?x ef))
            (and (= ?y fe) (= ?x ef))
            (and (= ?y ff) (= ?x ef))
            (and (= ?y fg) (= ?x ef))
            (and (= ?y gd) (= ?x ef))
            (and (= ?y gf) (= ?x ef))
            (and (= ?y gh) (= ?x ef))
            (and (= ?y hc) (= ?x ef))
            (and (= ?y hf) (= ?x ef))
            (and (= ?y ac) (= ?x eg))
            (and (= ?y ag) (= ?x eg))
            (and (= ?y bd) (= ?x eg))
            (and (= ?y bg) (= ?x eg))
            (and (= ?y ce) (= ?x eg))
            (and (= ?y cg) (= ?x eg))
            (and (= ?y df) (= ?x eg))
            (and (= ?y dg) (= ?x eg))
            (and (= ?y dh) (= ?x eg))
            (and (= ?y ea) (= ?x eg))
            (and (= ?y eb) (= ?x eg))
            (and (= ?y ec) (= ?x eg))
            (and (= ?y ed) (= ?x eg))
            (and (= ?y ee) (= ?x eg))
            (and (= ?y ef) (= ?x eg))
            (and (= ?y eg) (= ?x eg))
            (and (= ?y eh) (= ?x eg))
            (and (= ?y ff) (= ?x eg))
            (and (= ?y fg) (= ?x eg))
            (and (= ?y fh) (= ?x eg))
            (and (= ?y ge) (= ?x eg))
            (and (= ?y gg) (= ?x eg))
            (and (= ?y hd) (= ?x eg))
            (and (= ?y hg) (= ?x eg))
            (and (= ?y ad) (= ?x eh))
            (and (= ?y ah) (= ?x eh))
            (and (= ?y be) (= ?x eh))
            (and (= ?y bh) (= ?x eh))
            (and (= ?y cf) (= ?x eh))
            (and (= ?y ch) (= ?x eh))
            (and (= ?y dg) (= ?x eh))
            (and (= ?y dh) (= ?x eh))
            (and (= ?y ea) (= ?x eh))
            (and (= ?y eb) (= ?x eh))
            (and (= ?y ec) (= ?x eh))
            (and (= ?y ed) (= ?x eh))
            (and (= ?y ee) (= ?x eh))
            (and (= ?y ef) (= ?x eh))
            (and (= ?y eg) (= ?x eh))
            (and (= ?y eh) (= ?x eh))
            (and (= ?y fg) (= ?x eh))
            (and (= ?y fh) (= ?x eh))
            (and (= ?y gf) (= ?x eh))
            (and (= ?y gh) (= ?x eh))
            (and (= ?y he) (= ?x eh))
            (and (= ?y hh) (= ?x eh))
            (and (= ?y aa) (= ?x fa))
            (and (= ?y af) (= ?x fa))
            (and (= ?y ba) (= ?x fa))
            (and (= ?y be) (= ?x fa))
            (and (= ?y ca) (= ?x fa))
            (and (= ?y cd) (= ?x fa))
            (and (= ?y da) (= ?x fa))
            (and (= ?y dc) (= ?x fa))
            (and (= ?y ea) (= ?x fa))
            (and (= ?y eb) (= ?x fa))
            (and (= ?y fa) (= ?x fa))
            (and (= ?y fb) (= ?x fa))
            (and (= ?y fc) (= ?x fa))
            (and (= ?y fd) (= ?x fa))
            (and (= ?y fe) (= ?x fa))
            (and (= ?y ff) (= ?x fa))
            (and (= ?y fg) (= ?x fa))
            (and (= ?y fh) (= ?x fa))
            (and (= ?y ga) (= ?x fa))
            (and (= ?y gb) (= ?x fa))
            (and (= ?y ha) (= ?x fa))
            (and (= ?y hc) (= ?x fa))
            (and (= ?y ab) (= ?x fb))
            (and (= ?y ag) (= ?x fb))
            (and (= ?y bb) (= ?x fb))
            (and (= ?y bf) (= ?x fb))
            (and (= ?y cb) (= ?x fb))
            (and (= ?y ce) (= ?x fb))
            (and (= ?y db) (= ?x fb))
            (and (= ?y dd) (= ?x fb))
            (and (= ?y ea) (= ?x fb))
            (and (= ?y eb) (= ?x fb))
            (and (= ?y ec) (= ?x fb))
            (and (= ?y fa) (= ?x fb))
            (and (= ?y fb) (= ?x fb))
            (and (= ?y fc) (= ?x fb))
            (and (= ?y fd) (= ?x fb))
            (and (= ?y fe) (= ?x fb))
            (and (= ?y ff) (= ?x fb))
            (and (= ?y fg) (= ?x fb))
            (and (= ?y fh) (= ?x fb))
            (and (= ?y ga) (= ?x fb))
            (and (= ?y gb) (= ?x fb))
            (and (= ?y gc) (= ?x fb))
            (and (= ?y hb) (= ?x fb))
            (and (= ?y hd) (= ?x fb))
            (and (= ?y ac) (= ?x fc))
            (and (= ?y ah) (= ?x fc))
            (and (= ?y bc) (= ?x fc))
            (and (= ?y bg) (= ?x fc))
            (and (= ?y cc) (= ?x fc))
            (and (= ?y cf) (= ?x fc))
            (and (= ?y da) (= ?x fc))
            (and (= ?y dc) (= ?x fc))
            (and (= ?y de) (= ?x fc))
            (and (= ?y eb) (= ?x fc))
            (and (= ?y ec) (= ?x fc))
            (and (= ?y ed) (= ?x fc))
            (and (= ?y fa) (= ?x fc))
            (and (= ?y fb) (= ?x fc))
            (and (= ?y fc) (= ?x fc))
            (and (= ?y fd) (= ?x fc))
            (and (= ?y fe) (= ?x fc))
            (and (= ?y ff) (= ?x fc))
            (and (= ?y fg) (= ?x fc))
            (and (= ?y fh) (= ?x fc))
            (and (= ?y gb) (= ?x fc))
            (and (= ?y gc) (= ?x fc))
            (and (= ?y gd) (= ?x fc))
            (and (= ?y ha) (= ?x fc))
            (and (= ?y hc) (= ?x fc))
            (and (= ?y he) (= ?x fc))
            (and (= ?y ad) (= ?x fd))
            (and (= ?y bd) (= ?x fd))
            (and (= ?y bh) (= ?x fd))
            (and (= ?y ca) (= ?x fd))
            (and (= ?y cd) (= ?x fd))
            (and (= ?y cg) (= ?x fd))
            (and (= ?y db) (= ?x fd))
            (and (= ?y dd) (= ?x fd))
            (and (= ?y df) (= ?x fd))
            (and (= ?y ec) (= ?x fd))
            (and (= ?y ed) (= ?x fd))
            (and (= ?y ee) (= ?x fd))
            (and (= ?y fa) (= ?x fd))
            (and (= ?y fb) (= ?x fd))
            (and (= ?y fc) (= ?x fd))
            (and (= ?y fd) (= ?x fd))
            (and (= ?y fe) (= ?x fd))
            (and (= ?y ff) (= ?x fd))
            (and (= ?y fg) (= ?x fd))
            (and (= ?y fh) (= ?x fd))
            (and (= ?y gc) (= ?x fd))
            (and (= ?y gd) (= ?x fd))
            (and (= ?y ge) (= ?x fd))
            (and (= ?y hb) (= ?x fd))
            (and (= ?y hd) (= ?x fd))
            (and (= ?y hf) (= ?x fd))
            (and (= ?y ae) (= ?x fe))
            (and (= ?y ba) (= ?x fe))
            (and (= ?y be) (= ?x fe))
            (and (= ?y cb) (= ?x fe))
            (and (= ?y ce) (= ?x fe))
            (and (= ?y ch) (= ?x fe))
            (and (= ?y dc) (= ?x fe))
            (and (= ?y de) (= ?x fe))
            (and (= ?y dg) (= ?x fe))
            (and (= ?y ed) (= ?x fe))
            (and (= ?y ee) (= ?x fe))
            (and (= ?y ef) (= ?x fe))
            (and (= ?y fa) (= ?x fe))
            (and (= ?y fb) (= ?x fe))
            (and (= ?y fc) (= ?x fe))
            (and (= ?y fd) (= ?x fe))
            (and (= ?y fe) (= ?x fe))
            (and (= ?y ff) (= ?x fe))
            (and (= ?y fg) (= ?x fe))
            (and (= ?y fh) (= ?x fe))
            (and (= ?y gd) (= ?x fe))
            (and (= ?y ge) (= ?x fe))
            (and (= ?y gf) (= ?x fe))
            (and (= ?y hc) (= ?x fe))
            (and (= ?y he) (= ?x fe))
            (and (= ?y hg) (= ?x fe))
            (and (= ?y aa) (= ?x ff))
            (and (= ?y af) (= ?x ff))
            (and (= ?y bb) (= ?x ff))
            (and (= ?y bf) (= ?x ff))
            (and (= ?y cc) (= ?x ff))
            (and (= ?y cf) (= ?x ff))
            (and (= ?y dd) (= ?x ff))
            (and (= ?y df) (= ?x ff))
            (and (= ?y dh) (= ?x ff))
            (and (= ?y ee) (= ?x ff))
            (and (= ?y ef) (= ?x ff))
            (and (= ?y eg) (= ?x ff))
            (and (= ?y fa) (= ?x ff))
            (and (= ?y fb) (= ?x ff))
            (and (= ?y fc) (= ?x ff))
            (and (= ?y fd) (= ?x ff))
            (and (= ?y fe) (= ?x ff))
            (and (= ?y ff) (= ?x ff))
            (and (= ?y fg) (= ?x ff))
            (and (= ?y fh) (= ?x ff))
            (and (= ?y ge) (= ?x ff))
            (and (= ?y gf) (= ?x ff))
            (and (= ?y gg) (= ?x ff))
            (and (= ?y hd) (= ?x ff))
            (and (= ?y hf) (= ?x ff))
            (and (= ?y hh) (= ?x ff))
            (and (= ?y ab) (= ?x fg))
            (and (= ?y ag) (= ?x fg))
            (and (= ?y bc) (= ?x fg))
            (and (= ?y bg) (= ?x fg))
            (and (= ?y cd) (= ?x fg))
            (and (= ?y cg) (= ?x fg))
            (and (= ?y de) (= ?x fg))
            (and (= ?y dg) (= ?x fg))
            (and (= ?y ef) (= ?x fg))
            (and (= ?y eg) (= ?x fg))
            (and (= ?y eh) (= ?x fg))
            (and (= ?y fa) (= ?x fg))
            (and (= ?y fb) (= ?x fg))
            (and (= ?y fc) (= ?x fg))
            (and (= ?y fd) (= ?x fg))
            (and (= ?y fe) (= ?x fg))
            (and (= ?y ff) (= ?x fg))
            (and (= ?y fg) (= ?x fg))
            (and (= ?y fh) (= ?x fg))
            (and (= ?y gf) (= ?x fg))
            (and (= ?y gg) (= ?x fg))
            (and (= ?y gh) (= ?x fg))
            (and (= ?y he) (= ?x fg))
            (and (= ?y hg) (= ?x fg))
            (and (= ?y ac) (= ?x fh))
            (and (= ?y ah) (= ?x fh))
            (and (= ?y bd) (= ?x fh))
            (and (= ?y bh) (= ?x fh))
            (and (= ?y ce) (= ?x fh))
            (and (= ?y ch) (= ?x fh))
            (and (= ?y df) (= ?x fh))
            (and (= ?y dh) (= ?x fh))
            (and (= ?y eg) (= ?x fh))
            (and (= ?y eh) (= ?x fh))
            (and (= ?y fa) (= ?x fh))
            (and (= ?y fb) (= ?x fh))
            (and (= ?y fc) (= ?x fh))
            (and (= ?y fd) (= ?x fh))
            (and (= ?y fe) (= ?x fh))
            (and (= ?y ff) (= ?x fh))
            (and (= ?y fg) (= ?x fh))
            (and (= ?y fh) (= ?x fh))
            (and (= ?y gg) (= ?x fh))
            (and (= ?y gh) (= ?x fh))
            (and (= ?y hf) (= ?x fh))
            (and (= ?y hh) (= ?x fh))
            (and (= ?y aa) (= ?x ga))
            (and (= ?y ag) (= ?x ga))
            (and (= ?y ba) (= ?x ga))
            (and (= ?y bf) (= ?x ga))
            (and (= ?y ca) (= ?x ga))
            (and (= ?y ce) (= ?x ga))
            (and (= ?y da) (= ?x ga))
            (and (= ?y dd) (= ?x ga))
            (and (= ?y ea) (= ?x ga))
            (and (= ?y ec) (= ?x ga))
            (and (= ?y fa) (= ?x ga))
            (and (= ?y fb) (= ?x ga))
            (and (= ?y ga) (= ?x ga))
            (and (= ?y gb) (= ?x ga))
            (and (= ?y gc) (= ?x ga))
            (and (= ?y gd) (= ?x ga))
            (and (= ?y ge) (= ?x ga))
            (and (= ?y gf) (= ?x ga))
            (and (= ?y gg) (= ?x ga))
            (and (= ?y gh) (= ?x ga))
            (and (= ?y ha) (= ?x ga))
            (and (= ?y hb) (= ?x ga))
            (and (= ?y ab) (= ?x gb))
            (and (= ?y ah) (= ?x gb))
            (and (= ?y bb) (= ?x gb))
            (and (= ?y bg) (= ?x gb))
            (and (= ?y cb) (= ?x gb))
            (and (= ?y cf) (= ?x gb))
            (and (= ?y db) (= ?x gb))
            (and (= ?y de) (= ?x gb))
            (and (= ?y eb) (= ?x gb))
            (and (= ?y ed) (= ?x gb))
            (and (= ?y fa) (= ?x gb))
            (and (= ?y fb) (= ?x gb))
            (and (= ?y fc) (= ?x gb))
            (and (= ?y ga) (= ?x gb))
            (and (= ?y gb) (= ?x gb))
            (and (= ?y gc) (= ?x gb))
            (and (= ?y gd) (= ?x gb))
            (and (= ?y ge) (= ?x gb))
            (and (= ?y gf) (= ?x gb))
            (and (= ?y gg) (= ?x gb))
            (and (= ?y gh) (= ?x gb))
            (and (= ?y ha) (= ?x gb))
            (and (= ?y hb) (= ?x gb))
            (and (= ?y hc) (= ?x gb))
            (and (= ?y ac) (= ?x gc))
            (and (= ?y bc) (= ?x gc))
            (and (= ?y bh) (= ?x gc))
            (and (= ?y cc) (= ?x gc))
            (and (= ?y cg) (= ?x gc))
            (and (= ?y dc) (= ?x gc))
            (and (= ?y df) (= ?x gc))
            (and (= ?y ea) (= ?x gc))
            (and (= ?y ec) (= ?x gc))
            (and (= ?y ee) (= ?x gc))
            (and (= ?y fb) (= ?x gc))
            (and (= ?y fc) (= ?x gc))
            (and (= ?y fd) (= ?x gc))
            (and (= ?y ga) (= ?x gc))
            (and (= ?y gb) (= ?x gc))
            (and (= ?y gc) (= ?x gc))
            (and (= ?y gd) (= ?x gc))
            (and (= ?y ge) (= ?x gc))
            (and (= ?y gf) (= ?x gc))
            (and (= ?y gg) (= ?x gc))
            (and (= ?y gh) (= ?x gc))
            (and (= ?y hb) (= ?x gc))
            (and (= ?y hc) (= ?x gc))
            (and (= ?y hd) (= ?x gc))
            (and (= ?y ad) (= ?x gd))
            (and (= ?y bd) (= ?x gd))
            (and (= ?y cd) (= ?x gd))
            (and (= ?y ch) (= ?x gd))
            (and (= ?y da) (= ?x gd))
            (and (= ?y dd) (= ?x gd))
            (and (= ?y dg) (= ?x gd))
            (and (= ?y eb) (= ?x gd))
            (and (= ?y ed) (= ?x gd))
            (and (= ?y ef) (= ?x gd))
            (and (= ?y fc) (= ?x gd))
            (and (= ?y fd) (= ?x gd))
            (and (= ?y fe) (= ?x gd))
            (and (= ?y ga) (= ?x gd))
            (and (= ?y gb) (= ?x gd))
            (and (= ?y gc) (= ?x gd))
            (and (= ?y gd) (= ?x gd))
            (and (= ?y ge) (= ?x gd))
            (and (= ?y gf) (= ?x gd))
            (and (= ?y gg) (= ?x gd))
            (and (= ?y gh) (= ?x gd))
            (and (= ?y hc) (= ?x gd))
            (and (= ?y hd) (= ?x gd))
            (and (= ?y he) (= ?x gd))
            (and (= ?y ae) (= ?x ge))
            (and (= ?y be) (= ?x ge))
            (and (= ?y ca) (= ?x ge))
            (and (= ?y ce) (= ?x ge))
            (and (= ?y db) (= ?x ge))
            (and (= ?y de) (= ?x ge))
            (and (= ?y dh) (= ?x ge))
            (and (= ?y ec) (= ?x ge))
            (and (= ?y ee) (= ?x ge))
            (and (= ?y eg) (= ?x ge))
            (and (= ?y fd) (= ?x ge))
            (and (= ?y fe) (= ?x ge))
            (and (= ?y ff) (= ?x ge))
            (and (= ?y ga) (= ?x ge))
            (and (= ?y gb) (= ?x ge))
            (and (= ?y gc) (= ?x ge))
            (and (= ?y gd) (= ?x ge))
            (and (= ?y ge) (= ?x ge))
            (and (= ?y gf) (= ?x ge))
            (and (= ?y gg) (= ?x ge))
            (and (= ?y gh) (= ?x ge))
            (and (= ?y hd) (= ?x ge))
            (and (= ?y he) (= ?x ge))
            (and (= ?y hf) (= ?x ge))
            (and (= ?y af) (= ?x gf))
            (and (= ?y ba) (= ?x gf))
            (and (= ?y bf) (= ?x gf))
            (and (= ?y cb) (= ?x gf))
            (and (= ?y cf) (= ?x gf))
            (and (= ?y dc) (= ?x gf))
            (and (= ?y df) (= ?x gf))
            (and (= ?y ed) (= ?x gf))
            (and (= ?y ef) (= ?x gf))
            (and (= ?y eh) (= ?x gf))
            (and (= ?y fe) (= ?x gf))
            (and (= ?y ff) (= ?x gf))
            (and (= ?y fg) (= ?x gf))
            (and (= ?y ga) (= ?x gf))
            (and (= ?y gb) (= ?x gf))
            (and (= ?y gc) (= ?x gf))
            (and (= ?y gd) (= ?x gf))
            (and (= ?y ge) (= ?x gf))
            (and (= ?y gf) (= ?x gf))
            (and (= ?y gg) (= ?x gf))
            (and (= ?y gh) (= ?x gf))
            (and (= ?y he) (= ?x gf))
            (and (= ?y hf) (= ?x gf))
            (and (= ?y hg) (= ?x gf))
            (and (= ?y aa) (= ?x gg))
            (and (= ?y ag) (= ?x gg))
            (and (= ?y bb) (= ?x gg))
            (and (= ?y bg) (= ?x gg))
            (and (= ?y cc) (= ?x gg))
            (and (= ?y cg) (= ?x gg))
            (and (= ?y dd) (= ?x gg))
            (and (= ?y dg) (= ?x gg))
            (and (= ?y ee) (= ?x gg))
            (and (= ?y eg) (= ?x gg))
            (and (= ?y ff) (= ?x gg))
            (and (= ?y fg) (= ?x gg))
            (and (= ?y fh) (= ?x gg))
            (and (= ?y ga) (= ?x gg))
            (and (= ?y gb) (= ?x gg))
            (and (= ?y gc) (= ?x gg))
            (and (= ?y gd) (= ?x gg))
            (and (= ?y ge) (= ?x gg))
            (and (= ?y gf) (= ?x gg))
            (and (= ?y gg) (= ?x gg))
            (and (= ?y gh) (= ?x gg))
            (and (= ?y hf) (= ?x gg))
            (and (= ?y hg) (= ?x gg))
            (and (= ?y hh) (= ?x gg))
            (and (= ?y ab) (= ?x gh))
            (and (= ?y ah) (= ?x gh))
            (and (= ?y bc) (= ?x gh))
            (and (= ?y bh) (= ?x gh))
            (and (= ?y cd) (= ?x gh))
            (and (= ?y ch) (= ?x gh))
            (and (= ?y de) (= ?x gh))
            (and (= ?y dh) (= ?x gh))
            (and (= ?y ef) (= ?x gh))
            (and (= ?y eh) (= ?x gh))
            (and (= ?y fg) (= ?x gh))
            (and (= ?y fh) (= ?x gh))
            (and (= ?y ga) (= ?x gh))
            (and (= ?y gb) (= ?x gh))
            (and (= ?y gc) (= ?x gh))
            (and (= ?y gd) (= ?x gh))
            (and (= ?y ge) (= ?x gh))
            (and (= ?y gf) (= ?x gh))
            (and (= ?y gg) (= ?x gh))
            (and (= ?y gh) (= ?x gh))
            (and (= ?y hg) (= ?x gh))
            (and (= ?y hh) (= ?x gh))
            (and (= ?y aa) (= ?x ha))
            (and (= ?y ah) (= ?x ha))
            (and (= ?y ba) (= ?x ha))
            (and (= ?y bg) (= ?x ha))
            (and (= ?y ca) (= ?x ha))
            (and (= ?y cf) (= ?x ha))
            (and (= ?y da) (= ?x ha))
            (and (= ?y de) (= ?x ha))
            (and (= ?y ea) (= ?x ha))
            (and (= ?y ed) (= ?x ha))
            (and (= ?y fa) (= ?x ha))
            (and (= ?y fc) (= ?x ha))
            (and (= ?y ga) (= ?x ha))
            (and (= ?y gb) (= ?x ha))
            (and (= ?y ha) (= ?x ha))
            (and (= ?y hb) (= ?x ha))
            (and (= ?y hc) (= ?x ha))
            (and (= ?y hd) (= ?x ha))
            (and (= ?y he) (= ?x ha))
            (and (= ?y hf) (= ?x ha))
            (and (= ?y hg) (= ?x ha))
            (and (= ?y hh) (= ?x ha))
            (and (= ?y ab) (= ?x hb))
            (and (= ?y bb) (= ?x hb))
            (and (= ?y bh) (= ?x hb))
            (and (= ?y cb) (= ?x hb))
            (and (= ?y cg) (= ?x hb))
            (and (= ?y db) (= ?x hb))
            (and (= ?y df) (= ?x hb))
            (and (= ?y eb) (= ?x hb))
            (and (= ?y ee) (= ?x hb))
            (and (= ?y fb) (= ?x hb))
            (and (= ?y fd) (= ?x hb))
            (and (= ?y ga) (= ?x hb))
            (and (= ?y gb) (= ?x hb))
            (and (= ?y gc) (= ?x hb))
            (and (= ?y ha) (= ?x hb))
            (and (= ?y hb) (= ?x hb))
            (and (= ?y hc) (= ?x hb))
            (and (= ?y hd) (= ?x hb))
            (and (= ?y he) (= ?x hb))
            (and (= ?y hf) (= ?x hb))
            (and (= ?y hg) (= ?x hb))
            (and (= ?y hh) (= ?x hb))
            (and (= ?y ac) (= ?x hc))
            (and (= ?y bc) (= ?x hc))
            (and (= ?y cc) (= ?x hc))
            (and (= ?y ch) (= ?x hc))
            (and (= ?y dc) (= ?x hc))
            (and (= ?y dg) (= ?x hc))
            (and (= ?y ec) (= ?x hc))
            (and (= ?y ef) (= ?x hc))
            (and (= ?y fa) (= ?x hc))
            (and (= ?y fc) (= ?x hc))
            (and (= ?y fe) (= ?x hc))
            (and (= ?y gb) (= ?x hc))
            (and (= ?y gc) (= ?x hc))
            (and (= ?y gd) (= ?x hc))
            (and (= ?y ha) (= ?x hc))
            (and (= ?y hb) (= ?x hc))
            (and (= ?y hc) (= ?x hc))
            (and (= ?y hd) (= ?x hc))
            (and (= ?y he) (= ?x hc))
            (and (= ?y hf) (= ?x hc))
            (and (= ?y hg) (= ?x hc))
            (and (= ?y hh) (= ?x hc))
            (and (= ?y ad) (= ?x hd))
            (and (= ?y bd) (= ?x hd))
            (and (= ?y cd) (= ?x hd))
            (and (= ?y dd) (= ?x hd))
            (and (= ?y dh) (= ?x hd))
            (and (= ?y ea) (= ?x hd))
            (and (= ?y ed) (= ?x hd))
            (and (= ?y eg) (= ?x hd))
            (and (= ?y fb) (= ?x hd))
            (and (= ?y fd) (= ?x hd))
            (and (= ?y ff) (= ?x hd))
            (and (= ?y gc) (= ?x hd))
            (and (= ?y gd) (= ?x hd))
            (and (= ?y ge) (= ?x hd))
            (and (= ?y ha) (= ?x hd))
            (and (= ?y hb) (= ?x hd))
            (and (= ?y hc) (= ?x hd))
            (and (= ?y hd) (= ?x hd))
            (and (= ?y he) (= ?x hd))
            (and (= ?y hf) (= ?x hd))
            (and (= ?y hg) (= ?x hd))
            (and (= ?y hh) (= ?x hd))
            (and (= ?y ae) (= ?x he))
            (and (= ?y be) (= ?x he))
            (and (= ?y ce) (= ?x he))
            (and (= ?y da) (= ?x he))
            (and (= ?y de) (= ?x he))
            (and (= ?y eb) (= ?x he))
            (and (= ?y ee) (= ?x he))
            (and (= ?y eh) (= ?x he))
            (and (= ?y fc) (= ?x he))
            (and (= ?y fe) (= ?x he))
            (and (= ?y fg) (= ?x he))
            (and (= ?y gd) (= ?x he))
            (and (= ?y ge) (= ?x he))
            (and (= ?y gf) (= ?x he))
            (and (= ?y ha) (= ?x he))
            (and (= ?y hb) (= ?x he))
            (and (= ?y hc) (= ?x he))
            (and (= ?y hd) (= ?x he))
            (and (= ?y he) (= ?x he))
            (and (= ?y hf) (= ?x he))
            (and (= ?y hg) (= ?x he))
            (and (= ?y hh) (= ?x he))
            (and (= ?y af) (= ?x hf))
            (and (= ?y bf) (= ?x hf))
            (and (= ?y ca) (= ?x hf))
            (and (= ?y cf) (= ?x hf))
            (and (= ?y db) (= ?x hf))
            (and (= ?y df) (= ?x hf))
            (and (= ?y ec) (= ?x hf))
            (and (= ?y ef) (= ?x hf))
            (and (= ?y fd) (= ?x hf))
            (and (= ?y ff) (= ?x hf))
            (and (= ?y fh) (= ?x hf))
            (and (= ?y ge) (= ?x hf))
            (and (= ?y gf) (= ?x hf))
            (and (= ?y gg) (= ?x hf))
            (and (= ?y ha) (= ?x hf))
            (and (= ?y hb) (= ?x hf))
            (and (= ?y hc) (= ?x hf))
            (and (= ?y hd) (= ?x hf))
            (and (= ?y he) (= ?x hf))
            (and (= ?y hf) (= ?x hf))
            (and (= ?y hg) (= ?x hf))
            (and (= ?y hh) (= ?x hf))
            (and (= ?y ag) (= ?x hg))
            (and (= ?y ba) (= ?x hg))
            (and (= ?y bg) (= ?x hg))
            (and (= ?y cb) (= ?x hg))
            (and (= ?y cg) (= ?x hg))
            (and (= ?y dc) (= ?x hg))
            (and (= ?y dg) (= ?x hg))
            (and (= ?y ed) (= ?x hg))
            (and (= ?y eg) (= ?x hg))
            (and (= ?y fe) (= ?x hg))
            (and (= ?y fg) (= ?x hg))
            (and (= ?y gf) (= ?x hg))
            (and (= ?y gg) (= ?x hg))
            (and (= ?y gh) (= ?x hg))
            (and (= ?y ha) (= ?x hg))
            (and (= ?y hb) (= ?x hg))
            (and (= ?y hc) (= ?x hg))
            (and (= ?y hd) (= ?x hg))
            (and (= ?y he) (= ?x hg))
            (and (= ?y hf) (= ?x hg))
            (and (= ?y hg) (= ?x hg))
            (and (= ?y hh) (= ?x hg))
            (and (= ?y aa) (= ?x hh))
            (and (= ?y ah) (= ?x hh))
            (and (= ?y bb) (= ?x hh))
            (and (= ?y bh) (= ?x hh))
            (and (= ?y cc) (= ?x hh))
            (and (= ?y ch) (= ?x hh))
            (and (= ?y dd) (= ?x hh))
            (and (= ?y dh) (= ?x hh))
            (and (= ?y ee) (= ?x hh))
            (and (= ?y eh) (= ?x hh))
            (and (= ?y ff) (= ?x hh))
            (and (= ?y fh) (= ?x hh))
            (and (= ?y gg) (= ?x hh))
            (and (= ?y gh) (= ?x hh))
            (and (= ?y ha) (= ?x hh))
            (and (= ?y hb) (= ?x hh))
            (and (= ?y hc) (= ?x hh))
            (and (= ?y hd) (= ?x hh))
            (and (= ?y he) (= ?x hh))
            (and (= ?y hf) (= ?x hh))
            (and (= ?y hg) (= ?x hh))
            (and (= ?y hh) (= ?x hh))

        )
    )

(:action Move
  :parameters (?x ?y)
        :precondition (and
            (not (inconsistent))
            (and 
    (KBquery_Queen ?x)
    (KBquery_inline ?x ?y)
    (not (KBquery_Figure ?y))
  )
        )
  :effect (and
    (not (Queen ?x))
    (Queen ?y)
  )
)

)
