(define (problem BLOCKS-4-0)
(:domain BLOCKS)
(:objects B D A C - block pr2 - robot)
(:INIT (CLEAR C) (CLEAR A) (CLEAR B) (CLEAR D) (ONTABLE C) (ONTABLE A)
 (ONTABLE B) (ONTABLE D))
(:goal (AND (ON D C) (ON C B) (ON B A)))
)
