(define (problem BLOCKS-6-1)
(:domain BLOCKS)
(:objects B E A C D F - block pr2 - robot)
(:INIT (CLEAR A) (CLEAR B) (CLEAR E) (CLEAR C) (CLEAR D) (ONTABLE F)
 (ONTABLE B) (ONTABLE E) (ONTABLE C) (ONTABLE D) (ON A F))
(:goal (AND (ON E F) (ON F C) (ON C B) (ON B A) (ON A D)))
)
