(define (problem pipes_problem)
(:domain pipes)
(:init
       (nextto aa ab)
       (nextto aa ba)
       (nextto ab ac)
       (nextto ba ca)
       (nextto ac ad)
       (nextto ca da)
       (nextto ad ae)
       (nextto da ea)
       (nextto ae af)
       (nextto ea fa)
       (nextto af ag)
       (nextto fa ga)
       (nextto ba bb)
       (nextto ab bb)
       (nextto bb bc)
       (nextto bb cb)
       (nextto bc bd)
       (nextto cb db)
       (nextto bd be)
       (nextto db eb)
       (nextto be bf)
       (nextto eb fb)
       (nextto bf bg)
       (nextto fb gb)
       (nextto ca cb)
       (nextto ac bc)
       (nextto cb cc)
       (nextto bc cc)
       (nextto cc cd)
       (nextto cc dc)
       (nextto cd ce)
       (nextto dc ec)
       (nextto ce cf)
       (nextto ec fc)
       (nextto cf cg)
       (nextto fc gc)
       (nextto da db)
       (nextto ad bd)
       (nextto db dc)
       (nextto bd cd)
       (nextto dc dd)
       (nextto cd dd)
       (nextto dd de)
       (nextto dd ed)
       (nextto de df)
       (nextto ed fd)
       (nextto df dg)
       (nextto fd gd)
       (nextto ea eb)
       (nextto ae be)
       (nextto eb ec)
       (nextto be ce)
       (nextto ec ed)
       (nextto ce de)
       (nextto ed ee)
       (nextto de ee)
       (nextto ee ef)
       (nextto ee fe)
       (nextto ef eg)
       (nextto fe ge)
       (nextto fa fb)
       (nextto af bf)
       (nextto fb fc)
       (nextto bf cf)
       (nextto fc fd)
       (nextto cf df)
       (nextto fd fe)
       (nextto df ef)
       (nextto fe ff)
       (nextto ef ff)
       (nextto ff fg)
       (nextto ff gf)
       (nextto ga gb)
       (nextto ag bg)
       (nextto gb gc)
       (nextto bg cg)
       (nextto gc gd)
       (nextto cg dg)
       (nextto gd ge)
       (nextto dg eg)
       (nextto ge gf)
       (nextto eg fg)
       (nextto gf gg)
       (nextto fg gg)
       (nextto aa bb)
       (nextto ab bc)
       (nextto ac bd)
       (nextto ad be)
       (nextto ae bf)
       (nextto af bg)
       (nextto ab ba)
       (nextto ac bb)
       (nextto ad bc)
       (nextto ae bd)
       (nextto af be)
       (nextto ag bf)
       (nextto ba cb)
       (nextto bb cc)
       (nextto bc cd)
       (nextto bd ce)
       (nextto be cf)
       (nextto bf cg)
       (nextto bb ca)
       (nextto bc cb)
       (nextto bd cc)
       (nextto be cd)
       (nextto bf ce)
       (nextto bg cf)
       (nextto ca db)
       (nextto cb dc)
       (nextto cc dd)
       (nextto cd de)
       (nextto ce df)
       (nextto cf dg)
       (nextto cb da)
       (nextto cc db)
       (nextto cd dc)
       (nextto ce dd)
       (nextto cf de)
       (nextto cg df)
       (nextto da eb)
       (nextto db ec)
       (nextto dc ed)
       (nextto dd ee)
       (nextto de ef)
       (nextto df eg)
       (nextto db ea)
       (nextto dc eb)
       (nextto dd ec)
       (nextto de ed)
       (nextto df ee)
       (nextto dg ef)
       (nextto ea fb)
       (nextto eb fc)
       (nextto ec fd)
       (nextto ed fe)
       (nextto ee ff)
       (nextto ef fg)
       (nextto eb fa)
       (nextto ec fb)
       (nextto ed fc)
       (nextto ee fd)
       (nextto ef fe)
       (nextto eg ff)
       (nextto fa gb)
       (nextto fb gc)
       (nextto fc gd)
       (nextto fd ge)
       (nextto fe gf)
       (nextto ff gg)
       (nextto fb ga)
       (nextto fc gb)
       (nextto fd gc)
       (nextto fe gd)
       (nextto ff ge)
       (nextto fg gf)
       (robotat auv aa)
       (connectedto pipecc pipecd)
       (connectedto pipede pipeee)
       (locatedat pipefc fc)
       (connectedto pipecg pipedf)
       (connectedto pipede pipedf)
       (connectedto pipeee pipefd)
       (locatedat mineef ef)
       (connectedto pipefc pipefd)
       (connectedto pipegb pipegc)
       (locatedat walldd dd)
       (connectedto pipecd pipede)
       (locatedat walldb db)
       (locatedat pipedf df)
       (locatedat pipebg bg)
       (locatedat wallcb cb)
       (locatedat wallbb bb)
       (locatedat pipecc cc)
       (locatedat pipegc gc)
       (locatedat walldc dc)
       (locatedat pipeee ee)
       (locatedat pipede de)
       (locatedat wallab ab)
       (connectedto pipebg pipecg)
       (locatedat pipefd fd)
       (locatedat pipecg cg)
       (locatedat pipecd cd)
       (locatedat pipegb gb)
       (connectedto pipefc pipegc)
       (robot auv)
       (wp aa)
       (wp gd)
       (wp ae)
       (rustypipe pipegc)
       (wp gg)
       (wp fc)
       (wp fg)
       (wp ea)
       (wp bb)
       (wp ac)
       (wp eg)
       (wp ee)
       (wp dg)
       (wp db)
       (wp be)
       (wp gc)
       (mediumriskpipe pipede)
       (wp gb)
       (pipe pipegb)
       (rustypipe pipecc)
       (pipe pipedf)
       (protectedstructure walldc)
       (wp bd)
       (wp cg)
       (pipe pipeee)
       (wp ge)
       (pipe pipebg)
       (wp ce)
       (wp ff)
       (wp cf)
       (wp ad)
       (wp de)
       (protectedstructure wallab)
       (protectedstructure wallcb)
       (wp ab)
       (pipe pipecd)
       (wp dc)
       (wp ca)
       (wp fb)
       (mediumriskpipe pipefd)
       (wp cb)
       (wp fd)
       (wp gf)
       (protectedstructure walldd)
       (wp eb)
       (wp bg)
       (wp ga)
       (wp bf)
       (mine mineef)
       (pipe pipefc)
       (wp ed)
       (wp cd)
       (wp bc)
       (wp fe)
       (wp ef)
       (wp af)
       (unsupportedpipe pipecg)
       (wp cc)
       (wp da)
       (wp dd)
       (protectedstructure walldb)
       (wp ba)
       (wp ec)
       (wp fa)
       (wp ag)
       (wp df)
       (protectedstructure wallbb))
(:goal (and (robotat auv aa) (forall (?wp - object) (AUX19 ?wp)) (not (DATALOG_INCONSISTENT))))
)