(define (problem pipes_problem)
	(:domain pipes)
	(:objects dd de df dg pipecg pipegc wallbb pipegb pipecc pipecd ea eb ec ed ee aa ef ab ac eg ad ae af ag pipedf wallcb pipede fa fb fc fd ba fe bb ff fg bc bd be auv bf bg mineef walldd walldb walldc pipeee ga gb gc gd ca ge cb gf cc gg cd ce cf cg pipebg pipefc wallab pipefd da db dc 
 )
	(:init
		(nextTo aa ab)
		(nextTo aa ba)
		(nextTo ab ac)
		(nextTo ba ca)
		(nextTo ac ad)
		(nextTo ca da)
		(nextTo ad ae)
		(nextTo da ea)
		(nextTo ae af)
		(nextTo ea fa)
		(nextTo af ag)
		(nextTo fa ga)
		(nextTo ba bb)
		(nextTo ab bb)
		(nextTo bb bc)
		(nextTo bb cb)
		(nextTo bc bd)
		(nextTo cb db)
		(nextTo bd be)
		(nextTo db eb)
		(nextTo be bf)
		(nextTo eb fb)
		(nextTo bf bg)
		(nextTo fb gb)
		(nextTo ca cb)
		(nextTo ac bc)
		(nextTo cb cc)
		(nextTo bc cc)
		(nextTo cc cd)
		(nextTo cc dc)
		(nextTo cd ce)
		(nextTo dc ec)
		(nextTo ce cf)
		(nextTo ec fc)
		(nextTo cf cg)
		(nextTo fc gc)
		(nextTo da db)
		(nextTo ad bd)
		(nextTo db dc)
		(nextTo bd cd)
		(nextTo dc dd)
		(nextTo cd dd)
		(nextTo dd de)
		(nextTo dd ed)
		(nextTo de df)
		(nextTo ed fd)
		(nextTo df dg)
		(nextTo fd gd)
		(nextTo ea eb)
		(nextTo ae be)
		(nextTo eb ec)
		(nextTo be ce)
		(nextTo ec ed)
		(nextTo ce de)
		(nextTo ed ee)
		(nextTo de ee)
		(nextTo ee ef)
		(nextTo ee fe)
		(nextTo ef eg)
		(nextTo fe ge)
		(nextTo fa fb)
		(nextTo af bf)
		(nextTo fb fc)
		(nextTo bf cf)
		(nextTo fc fd)
		(nextTo cf df)
		(nextTo fd fe)
		(nextTo df ef)
		(nextTo fe ff)
		(nextTo ef ff)
		(nextTo ff fg)
		(nextTo ff gf)
		(nextTo ga gb)
		(nextTo ag bg)
		(nextTo gb gc)
		(nextTo bg cg)
		(nextTo gc gd)
		(nextTo cg dg)
		(nextTo gd ge)
		(nextTo dg eg)
		(nextTo ge gf)
		(nextTo eg fg)
		(nextTo gf gg)
		(nextTo fg gg)
		(nextTo aa bb)
		(nextTo ab bc)
		(nextTo ac bd)
		(nextTo ad be)
		(nextTo ae bf)
		(nextTo af bg)
		(nextTo ab ba)
		(nextTo ac bb)
		(nextTo ad bc)
		(nextTo ae bd)
		(nextTo af be)
		(nextTo ag bf)
		(nextTo ba cb)
		(nextTo bb cc)
		(nextTo bc cd)
		(nextTo bd ce)
		(nextTo be cf)
		(nextTo bf cg)
		(nextTo bb ca)
		(nextTo bc cb)
		(nextTo bd cc)
		(nextTo be cd)
		(nextTo bf ce)
		(nextTo bg cf)
		(nextTo ca db)
		(nextTo cb dc)
		(nextTo cc dd)
		(nextTo cd de)
		(nextTo ce df)
		(nextTo cf dg)
		(nextTo cb da)
		(nextTo cc db)
		(nextTo cd dc)
		(nextTo ce dd)
		(nextTo cf de)
		(nextTo cg df)
		(nextTo da eb)
		(nextTo db ec)
		(nextTo dc ed)
		(nextTo dd ee)
		(nextTo de ef)
		(nextTo df eg)
		(nextTo db ea)
		(nextTo dc eb)
		(nextTo dd ec)
		(nextTo de ed)
		(nextTo df ee)
		(nextTo dg ef)
		(nextTo ea fb)
		(nextTo eb fc)
		(nextTo ec fd)
		(nextTo ed fe)
		(nextTo ee ff)
		(nextTo ef fg)
		(nextTo eb fa)
		(nextTo ec fb)
		(nextTo ed fc)
		(nextTo ee fd)
		(nextTo ef fe)
		(nextTo eg ff)
		(nextTo fa gb)
		(nextTo fb gc)
		(nextTo fc gd)
		(nextTo fd ge)
		(nextTo fe gf)
		(nextTo ff gg)
		(nextTo fb ga)
		(nextTo fc gb)
		(nextTo fd gc)
		(nextTo fe gd)
		(nextTo ff ge)
		(nextTo fg gf)
		(robotAt auv aa)
		(connectedTo pipecc pipecd)
		(connectedTo pipede pipeee)
		(locatedAt fc pipefc)
		(connectedTo pipecg pipedf)
		(connectedTo pipede pipedf)
		(connectedTo pipeee pipefd)
		(locatedAt ef mineef)
		(connectedTo pipefc pipefd)
		(connectedTo pipegb pipegc)
		(locatedAt dd walldd)
		(connectedTo pipecd pipede)
		(locatedAt db walldb)
		(locatedAt df pipedf)
		(locatedAt bg pipebg)
		(locatedAt cb wallcb)
		(locatedAt bb wallbb)
		(locatedAt cc pipecc)
		(locatedAt gc pipegc)
		(locatedAt dc walldc)
		(locatedAt ee pipeee)
		(locatedAt de pipede)
		(locatedAt ab wallab)
		(connectedTo pipebg pipecg)
		(locatedAt fd pipefd)
		(locatedAt cg pipecg)
		(locatedAt cd pipecd)
		(locatedAt gb pipegb)
		(connectedTo pipefc pipegc)
		(Robot auv)
		(WP aa)
		(WP gd)
		(WP ae)
		(RustyPipe pipegc)
		(WP gg)
		(WP fc)
		(WP fg)
		(WP ea)
		(WP bb)
		(WP ac)
		(WP eg)
		(WP ee)
		(WP dg)
		(WP db)
		(WP be)
		(WP gc)
		(MediumRiskPipe pipede)
		(WP gb)
		(Pipe pipegb)
		(RustyPipe pipecc)
		(Pipe pipedf)
		(ProtectedStructure walldc)
		(WP bd)
		(WP cg)
		(Pipe pipeee)
		(WP ge)
		(Pipe pipebg)
		(WP ce)
		(WP ff)
		(WP cf)
		(WP ad)
		(WP de)
		(ProtectedStructure wallab)
		(ProtectedStructure wallcb)
		(WP ab)
		(Pipe pipecd)
		(WP dc)
		(WP ca)
		(WP fb)
		(MediumRiskPipe pipefd)
		(WP cb)
		(WP fd)
		(WP gf)
		(ProtectedStructure walldd)
		(WP eb)
		(WP bg)
		(WP ga)
		(WP bf)
		(Mine mineef)
		(Pipe pipefc)
		(WP ed)
		(WP cd)
		(WP bc)
		(WP fe)
		(WP ef)
		(WP af)
		(UnsupportedPipe pipecg)
		(WP cc)
		(WP da)
		(WP dd)
		(ProtectedStructure walldb)
		(WP ba)
		(WP ec)
		(WP fa)
		(WP ag)
		(WP df)
		(ProtectedStructure wallbb)
	)
	(:goal (and
		(robotAt auv aa) 
		(forall (?wp) (or 
			(not (mko (Risk ?wp)))  
			(mko (Covered ?wp))
			)
		)
		)
	)
)
