(define (problem pipes_problem)
	(:domain pipes)
	(:objects aa ab ac ad ae af ag auv ba bb bc bd be bf bg ca cb cc cd ce cf cg da db dc dd de df dg ea eb ec ed ee ef eg fa fb fc fd fe ff fg ga gb gc gd ge gf gg mineef pipebg pipecc pipecd pipecg pipede pipedf pipeee pipefc pipefd pipegb pipegc wallab wallbb wallcb walldb walldc walldd )
	(:init
		(nextTo aa ab)
		(nextTo aa ba)
		(nextTo ab ac)
		(nextTo ba ca)
		(nextTo ac ad)
		(nextTo ca da)
		(nextTo ad ae)
		(nextTo da ea)
		(nextTo ae af)
		(nextTo ea fa)
		(nextTo af ag)
		(nextTo fa ga)
		(nextTo ba bb)
		(nextTo ab bb)
		(nextTo bb bc)
		(nextTo bb cb)
		(nextTo bc bd)
		(nextTo cb db)
		(nextTo bd be)
		(nextTo db eb)
		(nextTo be bf)
		(nextTo eb fb)
		(nextTo bf bg)
		(nextTo fb gb)
		(nextTo ca cb)
		(nextTo ac bc)
		(nextTo cb cc)
		(nextTo bc cc)
		(nextTo cc cd)
		(nextTo cc dc)
		(nextTo cd ce)
		(nextTo dc ec)
		(nextTo ce cf)
		(nextTo ec fc)
		(nextTo cf cg)
		(nextTo fc gc)
		(nextTo da db)
		(nextTo ad bd)
		(nextTo db dc)
		(nextTo bd cd)
		(nextTo dc dd)
		(nextTo cd dd)
		(nextTo dd de)
		(nextTo dd ed)
		(nextTo de df)
		(nextTo ed fd)
		(nextTo df dg)
		(nextTo fd gd)
		(nextTo ea eb)
		(nextTo ae be)
		(nextTo eb ec)
		(nextTo be ce)
		(nextTo ec ed)
		(nextTo ce de)
		(nextTo ed ee)
		(nextTo de ee)
		(nextTo ee ef)
		(nextTo ee fe)
		(nextTo ef eg)
		(nextTo fe ge)
		(nextTo fa fb)
		(nextTo af bf)
		(nextTo fb fc)
		(nextTo bf cf)
		(nextTo fc fd)
		(nextTo cf df)
		(nextTo fd fe)
		(nextTo df ef)
		(nextTo fe ff)
		(nextTo ef ff)
		(nextTo ff fg)
		(nextTo ff gf)
		(nextTo ga gb)
		(nextTo ag bg)
		(nextTo gb gc)
		(nextTo bg cg)
		(nextTo gc gd)
		(nextTo cg dg)
		(nextTo gd ge)
		(nextTo dg eg)
		(nextTo ge gf)
		(nextTo eg fg)
		(nextTo gf gg)
		(nextTo fg gg)
		(nextTo aa bb)
		(nextTo ab bc)
		(nextTo ac bd)
		(nextTo ad be)
		(nextTo ae bf)
		(nextTo af bg)
		(nextTo ab ba)
		(nextTo ac bb)
		(nextTo ad bc)
		(nextTo ae bd)
		(nextTo af be)
		(nextTo ag bf)
		(nextTo ba cb)
		(nextTo bb cc)
		(nextTo bc cd)
		(nextTo bd ce)
		(nextTo be cf)
		(nextTo bf cg)
		(nextTo bb ca)
		(nextTo bc cb)
		(nextTo bd cc)
		(nextTo be cd)
		(nextTo bf ce)
		(nextTo bg cf)
		(nextTo ca db)
		(nextTo cb dc)
		(nextTo cc dd)
		(nextTo cd de)
		(nextTo ce df)
		(nextTo cf dg)
		(nextTo cb da)
		(nextTo cc db)
		(nextTo cd dc)
		(nextTo ce dd)
		(nextTo cf de)
		(nextTo cg df)
		(nextTo da eb)
		(nextTo db ec)
		(nextTo dc ed)
		(nextTo dd ee)
		(nextTo de ef)
		(nextTo df eg)
		(nextTo db ea)
		(nextTo dc eb)
		(nextTo dd ec)
		(nextTo de ed)
		(nextTo df ee)
		(nextTo dg ef)
		(nextTo ea fb)
		(nextTo eb fc)
		(nextTo ec fd)
		(nextTo ed fe)
		(nextTo ee ff)
		(nextTo ef fg)
		(nextTo eb fa)
		(nextTo ec fb)
		(nextTo ed fc)
		(nextTo ee fd)
		(nextTo ef fe)
		(nextTo eg ff)
		(nextTo fa gb)
		(nextTo fb gc)
		(nextTo fc gd)
		(nextTo fd ge)
		(nextTo fe gf)
		(nextTo ff gg)
		(nextTo fb ga)
		(nextTo fc gb)
		(nextTo fd gc)
		(nextTo fe gd)
		(nextTo ff ge)
		(nextTo fg gf)
		(MediumRiskPipe pipede)
		(MediumRiskPipe pipefd)
		(Mine mineef)
		(Pipe pipebg)
		(Pipe pipecd)
		(Pipe pipedf)
		(Pipe pipeee)
		(Pipe pipefc)
		(Pipe pipegb)
		(ProtectedStructure wallab)
		(ProtectedStructure wallbb)
		(ProtectedStructure wallcb)
		(ProtectedStructure walldb)
		(ProtectedStructure walldc)
		(ProtectedStructure walldd)
		(Robot auv)
		(RustyPipe pipecc)
		(RustyPipe pipegc)
		(UnsupportedPipe pipecg)
		(WP aa)
		(WP ab)
		(WP ac)
		(WP ad)
		(WP ae)
		(WP af)
		(WP ag)
		(WP ba)
		(WP bb)
		(WP bc)
		(WP bd)
		(WP be)
		(WP bf)
		(WP bg)
		(WP ca)
		(WP cb)
		(WP cc)
		(WP cd)
		(WP ce)
		(WP cf)
		(WP cg)
		(WP da)
		(WP db)
		(WP dc)
		(WP dd)
		(WP de)
		(WP df)
		(WP dg)
		(WP ea)
		(WP eb)
		(WP ec)
		(WP ed)
		(WP ee)
		(WP ef)
		(WP eg)
		(WP fa)
		(WP fb)
		(WP fc)
		(WP fd)
		(WP fe)
		(WP ff)
		(WP fg)
		(WP ga)
		(WP gb)
		(WP gc)
		(WP gd)
		(WP ge)
		(WP gf)
		(WP gg)
		(connectedTo pipebg pipecg)
		(connectedTo pipecd pipecc)
		(connectedTo pipecg pipedf)
		(connectedTo pipede pipecd)
		(connectedTo pipedf pipede)
		(connectedTo pipeee pipede)
		(connectedTo pipefc pipefd)
		(connectedTo pipefd pipeee)
		(connectedTo pipegb pipegc)
		(connectedTo pipegc pipefc)
		(locatedAt mineef ef)
		(locatedAt pipebg bg)
		(locatedAt pipecc cc)
		(locatedAt pipecd cd)
		(locatedAt pipecg cg)
		(locatedAt pipede de)
		(locatedAt pipedf df)
		(locatedAt pipeee ee)
		(locatedAt pipefc fc)
		(locatedAt pipefd fd)
		(locatedAt pipegb gb)
		(locatedAt pipegc gc)
		(locatedAt wallab ab)
		(locatedAt wallbb bb)
		(locatedAt wallcb cb)
		(locatedAt walldb db)
		(locatedAt walldc dc)
		(locatedAt walldd dd)
		(robotAt auv aa)
	)
	(:goal (and
		(robotAt auv aa) 
		(forall (?wp) (or 
			(not (mko (Risk ?wp)))  
			(mko (Covered ?wp))
			)
		)
		)
	)
)
