(define (domain drone)
	(:requirements :strips :equality :disjunctive-preconditions :derived-predicates :negative-preconditions :conditional-effects :existential-preconditions)


	(:predicates 
    (false)
    (true)
    (inconsistent)
		(environment ?x ?y)
		(Rain ?x)
		(Drone ?x)
		(WetDrone ?x)
		(LowVisibility ?x)
		(near ?x ?y)
		(veryClose ?x ?y)
		(Human ?x)
		(MovingObject ?x)
		(Objectx ?x)
		(RiskOfPhysicalDamage ?x)
	  (Tree ?x)
	  (KBquery_XveryCloseY ?x ?y)
	  (KBquery_WetDrone ?x)
	  (KBquery_Objectx ?x)
	  (KBquery_AvoidCondition ?x ?y)
	)

    (:derived (true)
        (not (false))
    )

    (:derived (inconsistent) 
        (or (Drone eb) (Drone db) (Drone dc) (WetDrone eb) (WetDrone ea) (WetDrone dc) (Drone ea) (WetDrone db))
    )

    (:derived (KBquery_WetDrone ?x)
        (or

            (and (= ?x aa) (or (WetDrone aa) (Drone aa)))
            (and (= ?x ab) (or (WetDrone ab) (Drone ab)))
            (and (= ?x ac) (or (Drone ac) (WetDrone ac)))
            (and (= ?x ad) (or (Drone ad) (WetDrone ad)))
            (and (= ?x ae) (or (Drone ae) (WetDrone ae)))
            (and (= ?x af) (or (WetDrone af) (Drone af)))
            (and (= ?x ba) (or (WetDrone ba) (Drone ba)))
            (and (= ?x bb) (or (Drone bb) (WetDrone bb)))
            (and (= ?x bc) (or (Drone bc) (WetDrone bc)))
            (and (= ?x bd) (or (WetDrone bd) (Drone bd)))
            (and (= ?x be) (or (WetDrone be) (Drone be)))
            (and (= ?x bf) (or (WetDrone bf) (Drone bf)))
            (and (= ?x ca) (or (Drone ca) (WetDrone ca)))
            (and (= ?x cb) (or (Drone cb) (WetDrone cb)))
            (and (= ?x cc) (or (WetDrone cc) (Drone cc)))
            (and (= ?x cd) (or (WetDrone cd) (Drone cd)))
            (and (= ?x ce) (or (WetDrone ce) (Drone ce)))
            (and (= ?x cf) (or (WetDrone cf) (Drone cf)))
            (and (= ?x da) (or (Drone da) (WetDrone da)))
            (and (= ?x dd) (or (WetDrone dd) (Drone dd)))
            (and (= ?x de) (or (WetDrone de) (Drone de)))
            (and (= ?x df) (or (WetDrone df) (Drone df)))
            (and (= ?x ec) (or (Drone ec) (WetDrone ec)))
            (and (= ?x ed) (or (WetDrone ed) (Drone ed)))
            (and (= ?x ee) (or (WetDrone ee) (Drone ee)))
            (and (= ?x ef) (or (Drone ef) (WetDrone ef)))
            (and (= ?x fa) (or (Drone fa) (WetDrone fa)))
            (and (= ?x fb) (or (WetDrone fb) (Drone fb)))
            (and (= ?x fc) (or (Drone fc) (WetDrone fc)))
            (and (= ?x fd) (or (WetDrone fd) (Drone fd)))
            (and (= ?x fe) (or (WetDrone fe) (Drone fe)))
            (and (= ?x ff) (or (Drone ff) (WetDrone ff)))

        )
    )

    (:derived (KBquery_Objectx ?x)
        (or

            (and (= ?x aa) (or (WetDrone aa) (Drone aa)))
            (= ?x ab)
            (and (= ?x ac) (or (Drone ac) (WetDrone ac)))
            (= ?x ad)
            (and (= ?x ae) (or (Drone ae) (WetDrone ae)))
            (and (= ?x af) (or (WetDrone af) (Drone af)))
            (= ?x ba)
            (and (= ?x bb) (or (Drone bb) (WetDrone bb)))
            (= ?x bc)
            (and (= ?x bd) (or (WetDrone bd) (Drone bd)))
            (and (= ?x be) (or (WetDrone be) (Drone be)))
            (= ?x bf)
            (and (= ?x ca) (or (Drone ca) (WetDrone ca)))
            (and (= ?x cb) (or (Drone cb) (WetDrone cb)))
            (and (= ?x cc) (or (WetDrone cc) (Drone cc)))
            (and (= ?x cd) (or (WetDrone cd) (Drone cd)))
            (and (= ?x ce) (or (WetDrone ce) (Drone ce)))
            (and (= ?x cf) (or (WetDrone cf) (Drone cf)))
            (and (= ?x da) (or (Drone da) (WetDrone da)))
            (= ?x db)
            (= ?x dc)
            (and (= ?x dd) (or (WetDrone dd) (Drone dd)))
            (and (= ?x de) (or (WetDrone de) (Drone de)))
            (and (= ?x df) (or (WetDrone df) (Drone df)))
            (= ?x ea)
            (= ?x eb)
            (and (= ?x ec) (or (Drone ec) (WetDrone ec)))
            (and (= ?x ed) (or (WetDrone ed) (Drone ed)))
            (and (= ?x ee) (or (WetDrone ee) (Drone ee)))
            (and (= ?x ef) (or (Drone ef) (WetDrone ef)))
            (and (= ?x fa) (or (Drone fa) (WetDrone fa)))
            (and (= ?x fb) (or (WetDrone fb) (Drone fb)))
            (and (= ?x fc) (or (Drone fc) (WetDrone fc)))
            (and (= ?x fd) (or (WetDrone fd) (Drone fd)))
            (and (= ?x fe) (or (WetDrone fe) (Drone fe)))
            (and (= ?x ff) (or (Drone ff) (WetDrone ff)))

        )
    )

    (:derived (KBquery_XveryCloseY ?x ?y)
        (or

            (and (= ?y ab) (= ?x aa) (or (WetDrone aa) (Drone aa)))
            (and (= ?y ba) (= ?x aa) (or (WetDrone aa) (Drone aa)))
            (and (= ?y aa) (= ?x ab) (or (WetDrone ab) (Drone ab)))
            (and (= ?y ac) (= ?x ab) (or (WetDrone ab) (Drone ab)))
            (and (= ?y bb) (= ?x ab) (or (WetDrone ab) (Drone ab)))
            (and (= ?y ab) (= ?x ac) (or (Drone ac) (WetDrone ac)))
            (and (= ?y ad) (= ?x ac) (or (Drone ac) (WetDrone ac)))
            (and (= ?y bc) (= ?x ac) (or (Drone ac) (WetDrone ac)))
            (and (= ?y ac) (= ?x ad) (or (Drone ad) (WetDrone ad)))
            (and (= ?y ae) (= ?x ad) (or (Drone ad) (WetDrone ad)))
            (and (= ?y bd) (= ?x ad) (or (Drone ad) (WetDrone ad)))
            (and (= ?y ad) (= ?x ae) (or (Drone ae) (WetDrone ae)))
            (and (= ?y af) (= ?x ae) (or (Drone ae) (WetDrone ae)))
            (and (= ?y be) (= ?x ae) (or (Drone ae) (WetDrone ae)))
            (and (= ?y ae) (= ?x af) (or (WetDrone af) (Drone af)))
            (and (= ?y bf) (= ?x af) (or (WetDrone af) (Drone af)))
            (and (= ?y aa) (= ?x ba) (or (WetDrone ba) (Drone ba)))
            (and (= ?y bb) (= ?x ba) (or (WetDrone ba) (Drone ba)))
            (and (= ?y ca) (= ?x ba) (or (WetDrone ba) (Drone ba)))
            (and (= ?y ab) (= ?x bb) (or (Drone bb) (WetDrone bb)))
            (and (= ?y ba) (= ?x bb) (or (Drone bb) (WetDrone bb)))
            (and (= ?y bc) (= ?x bb) (or (Drone bb) (WetDrone bb)))
            (and (= ?y cb) (= ?x bb) (or (Drone bb) (WetDrone bb)))
            (and (= ?y ac) (= ?x bc) (or (Drone bc) (WetDrone bc)))
            (and (= ?y bb) (= ?x bc) (or (Drone bc) (WetDrone bc)))
            (and (= ?y bd) (= ?x bc) (or (Drone bc) (WetDrone bc)))
            (and (= ?y cc) (= ?x bc) (or (Drone bc) (WetDrone bc)))
            (and (= ?y ad) (= ?x bd) (or (WetDrone bd) (Drone bd)))
            (and (= ?y bc) (= ?x bd) (or (WetDrone bd) (Drone bd)))
            (and (= ?y be) (= ?x bd) (or (WetDrone bd) (Drone bd)))
            (and (= ?y cd) (= ?x bd) (or (WetDrone bd) (Drone bd)))
            (and (= ?y ae) (= ?x be) (or (WetDrone be) (Drone be)))
            (and (= ?y bd) (= ?x be) (or (WetDrone be) (Drone be)))
            (and (= ?y bf) (= ?x be) (or (WetDrone be) (Drone be)))
            (and (= ?y ce) (= ?x be) (or (WetDrone be) (Drone be)))
            (and (= ?y af) (= ?x bf) (or (WetDrone bf) (Drone bf)))
            (and (= ?y be) (= ?x bf) (or (WetDrone bf) (Drone bf)))
            (and (= ?y cf) (= ?x bf) (or (WetDrone bf) (Drone bf)))
            (and (= ?y ba) (= ?x ca) (or (Drone ca) (WetDrone ca)))
            (and (= ?y cb) (= ?x ca) (or (Drone ca) (WetDrone ca)))
            (and (= ?y da) (= ?x ca) (or (Drone ca) (WetDrone ca)))
            (and (= ?y bb) (= ?x cb) (or (Drone cb) (WetDrone cb)))
            (and (= ?y ca) (= ?x cb) (or (Drone cb) (WetDrone cb)))
            (and (= ?y cc) (= ?x cb) (or (Drone cb) (WetDrone cb)))
            (and (= ?y db) (= ?x cb) (or (Drone cb) (WetDrone cb)))
            (and (= ?y bc) (= ?x cc) (or (WetDrone cc) (Drone cc)))
            (and (= ?y cb) (= ?x cc) (or (WetDrone cc) (Drone cc)))
            (and (= ?y cd) (= ?x cc) (or (WetDrone cc) (Drone cc)))
            (and (= ?y dc) (= ?x cc) (or (WetDrone cc) (Drone cc)))
            (and (= ?y bd) (= ?x cd) (or (WetDrone cd) (Drone cd)))
            (and (= ?y cc) (= ?x cd) (or (WetDrone cd) (Drone cd)))
            (and (= ?y ce) (= ?x cd) (or (WetDrone cd) (Drone cd)))
            (and (= ?y dd) (= ?x cd) (or (WetDrone cd) (Drone cd)))
            (and (= ?y be) (= ?x ce) (or (WetDrone ce) (Drone ce)))
            (and (= ?y cd) (= ?x ce) (or (WetDrone ce) (Drone ce)))
            (and (= ?y cf) (= ?x ce) (or (WetDrone ce) (Drone ce)))
            (and (= ?y de) (= ?x ce) (or (WetDrone ce) (Drone ce)))
            (and (= ?y bf) (= ?x cf) (or (WetDrone cf) (Drone cf)))
            (and (= ?y ce) (= ?x cf) (or (WetDrone cf) (Drone cf)))
            (and (= ?y df) (= ?x cf) (or (WetDrone cf) (Drone cf)))
            (and (= ?y ca) (= ?x da) (or (Drone da) (WetDrone da)))
            (and (= ?y db) (= ?x da) (or (Drone da) (WetDrone da)))
            (and (= ?y ea) (= ?x da) (or (Drone da) (WetDrone da)))
 
            (and (= ?y cd) (= ?x dd) (or (WetDrone dd) (Drone dd)))
            (and (= ?y dc) (= ?x dd) (or (WetDrone dd) (Drone dd)))
            (and (= ?y de) (= ?x dd) (or (WetDrone dd) (Drone dd)))
            (and (= ?y ed) (= ?x dd) (or (WetDrone dd) (Drone dd)))
            (and (= ?y ce) (= ?x de) (or (WetDrone de) (Drone de)))
            (and (= ?y dd) (= ?x de) (or (WetDrone de) (Drone de)))
            (and (= ?y df) (= ?x de) (or (WetDrone de) (Drone de)))
            (and (= ?y ee) (= ?x de) (or (WetDrone de) (Drone de)))
            (and (= ?y cf) (= ?x df) (or (WetDrone df) (Drone df)))
            (and (= ?y de) (= ?x df) (or (WetDrone df) (Drone df)))
            (and (= ?y ef) (= ?x df) (or (WetDrone df) (Drone df)))
 
            (and (= ?y dc) (= ?x ec) (or (Drone ec) (WetDrone ec)))
            (and (= ?y eb) (= ?x ec) (or (Drone ec) (WetDrone ec)))
            (and (= ?y ed) (= ?x ec) (or (Drone ec) (WetDrone ec)))
            (and (= ?y fc) (= ?x ec) (or (Drone ec) (WetDrone ec)))
            (and (= ?y dd) (= ?x ed) (or (WetDrone ed) (Drone ed)))
            (and (= ?y ec) (= ?x ed) (or (WetDrone ed) (Drone ed)))
            (and (= ?y ee) (= ?x ed) (or (WetDrone ed) (Drone ed)))
            (and (= ?y fd) (= ?x ed) (or (WetDrone ed) (Drone ed)))
            (and (= ?y de) (= ?x ee) (or (WetDrone ee) (Drone ee)))
            (and (= ?y ed) (= ?x ee) (or (WetDrone ee) (Drone ee)))
            (and (= ?y ef) (= ?x ee) (or (WetDrone ee) (Drone ee)))
            (and (= ?y fe) (= ?x ee) (or (WetDrone ee) (Drone ee)))
            (and (= ?y df) (= ?x ef) (or (Drone ef) (WetDrone ef)))
            (and (= ?y ee) (= ?x ef) (or (Drone ef) (WetDrone ef)))
            (and (= ?y ff) (= ?x ef) (or (Drone ef) (WetDrone ef)))
            (and (= ?y ea) (= ?x fa) (or (Drone fa) (WetDrone fa)))
            (and (= ?y fb) (= ?x fa) (or (Drone fa) (WetDrone fa)))
            (and (= ?y eb) (= ?x fb) (or (WetDrone fb) (Drone fb)))
            (and (= ?y fa) (= ?x fb) (or (WetDrone fb) (Drone fb)))
            (and (= ?y fc) (= ?x fb) (or (WetDrone fb) (Drone fb)))
            (and (= ?y ec) (= ?x fc) (or (Drone fc) (WetDrone fc)))
            (and (= ?y fb) (= ?x fc) (or (Drone fc) (WetDrone fc)))
            (and (= ?y fd) (= ?x fc) (or (Drone fc) (WetDrone fc)))
            (and (= ?y ed) (= ?x fd) (or (WetDrone fd) (Drone fd)))
            (and (= ?y fc) (= ?x fd) (or (WetDrone fd) (Drone fd)))
            (and (= ?y fe) (= ?x fd) (or (WetDrone fd) (Drone fd)))
            (and (= ?y ee) (= ?x fe) (or (WetDrone fe) (Drone fe)))
            (and (= ?y fd) (= ?x fe) (or (WetDrone fe) (Drone fe)))
            (and (= ?y ff) (= ?x fe) (or (WetDrone fe) (Drone fe)))
            (and (= ?y ef) (= ?x ff) (or (Drone ff) (WetDrone ff)))
            (and (= ?y fe) (= ?x ff) (or (Drone ff) (WetDrone ff)))

        )
    )

    (:derived (KBquery_AvoidCondition ?x ?y)
        (or

            (and (= ?y ab) (= ?x aa) (or (and (Drone aa) (Drone ab)) (and (WetDrone ab) (Drone aa)) (and (WetDrone aa) (Drone ab)) (and (WetDrone ab) (WetDrone aa))))
            (and (= ?y ba) (= ?x aa) (or (and (WetDrone aa) (Drone ba)) (and (WetDrone aa) (WetDrone ba)) (and (Drone aa) (WetDrone ba)) (and (Drone aa) (Drone ba))))
            (and (= ?y bb) (= ?x aa) (or (and (WetDrone aa) (WetDrone bb)) (and (Drone aa) (WetDrone bb)) (and (Drone bb) (WetDrone aa)) (and (Drone bb) (Drone aa))))
            (and (= ?y aa) (= ?x ab) (or (and (Drone aa) (Drone ab)) (and (WetDrone ab) (Drone aa)) (and (WetDrone aa) (Drone ab)) (and (WetDrone ab) (WetDrone aa))))
            (and (= ?y ac) (= ?x ab) (or (and (WetDrone ab) (WetDrone ac)) (and (Drone ac) (Drone ab)) (and (WetDrone ac) (Drone ab)) (and (WetDrone ab) (Drone ac))))
            (and (= ?y ba) (= ?x ab) (or (and (WetDrone ab) (Drone ba)) (and (Drone ab) (WetDrone ba)) (and (Drone ba) (Drone ab)) (and (WetDrone ab) (WetDrone ba))))
            (and (= ?y bb) (= ?x ab) (or (and (Drone bb) (Drone ab)) (and (WetDrone bb) (WetDrone ab)) (and (WetDrone bb) (Drone ab)) (and (WetDrone ab) (Drone bb))))
            (and (= ?y bc) (= ?x ab) (or (and (Drone bc) (Drone ab)) (and (WetDrone ab) (Drone bc)) (and (WetDrone bc) (Drone ab)) (and (WetDrone ab) (WetDrone bc))))
            (and (= ?y ab) (= ?x ac) (or (and (WetDrone ab) (WetDrone ac)) (and (Drone ac) (Drone ab)) (and (WetDrone ac) (Drone ab)) (and (WetDrone ab) (Drone ac))))
            (and (= ?y ad) (= ?x ac) (or (and (Drone ad) (Drone ac)) (and (WetDrone ad) (Drone ac)) (and (Drone ad) (WetDrone ac)) (and (WetDrone ad) (WetDrone ac))))
            (and (= ?y bb) (= ?x ac) (or (and (Drone bb) (Drone ac)) (and (WetDrone bb) (Drone ac)) (and (Drone bb) (WetDrone ac)) (and (WetDrone bb) (WetDrone ac))))
            (and (= ?y bc) (= ?x ac) (or (and (WetDrone bc) (Drone ac)) (and (WetDrone bc) (WetDrone ac)) (and (WetDrone ac) (Drone bc)) (and (Drone ac) (Drone bc))))
            (and (= ?y bd) (= ?x ac) (or (and (WetDrone bd) (WetDrone ac)) (and (Drone ac) (Drone bd)) (and (WetDrone bd) (Drone ac)) (and (WetDrone ac) (Drone bd))))
            (and (= ?y ac) (= ?x ad) (or (and (Drone ad) (Drone ac)) (and (WetDrone ad) (Drone ac)) (and (Drone ad) (WetDrone ac)) (and (WetDrone ad) (WetDrone ac))))
            (and (= ?y ae) (= ?x ad) (or (and (Drone ad) (Drone ae)) (and (Drone ad) (WetDrone ae)) (and (WetDrone ad) (Drone ae)) (and (WetDrone ad) (WetDrone ae))))
            (and (= ?y bc) (= ?x ad) (or (and (Drone ad) (WetDrone bc)) (and (WetDrone ad) (Drone bc)) (and (WetDrone ad) (WetDrone bc)) (and (Drone ad) (Drone bc))))
            (and (= ?y bd) (= ?x ad) (or (and (WetDrone ad) (Drone bd)) (and (Drone ad) (WetDrone bd)) (and (WetDrone ad) (WetDrone bd)) (and (Drone ad) (Drone bd))))
            (and (= ?y be) (= ?x ad) (or (and (Drone ad) (Drone be)) (and (WetDrone be) (WetDrone ad)) (and (WetDrone be) (Drone ad)) (and (WetDrone ad) (Drone be))))
            (and (= ?y ad) (= ?x ae) (or (and (Drone ad) (Drone ae)) (and (Drone ad) (WetDrone ae)) (and (WetDrone ad) (Drone ae)) (and (WetDrone ad) (WetDrone ae))))
            (and (= ?y af) (= ?x ae) (or (and (WetDrone af) (Drone ae)) (and (Drone af) (Drone ae)) (and (WetDrone ae) (WetDrone af)) (and (Drone af) (WetDrone ae))))
            (and (= ?y bd) (= ?x ae) (or (and (Drone bd) (WetDrone ae)) (and (WetDrone bd) (WetDrone ae)) (and (WetDrone bd) (Drone ae)) (and (Drone ae) (Drone bd))))
            (and (= ?y be) (= ?x ae) (or (and (WetDrone be) (WetDrone ae)) (and (Drone be) (Drone ae)) (and (WetDrone be) (Drone ae)) (and (Drone be) (WetDrone ae))))
            (and (= ?y bf) (= ?x ae) (or (and (Drone ae) (Drone bf)) (and (WetDrone ae) (Drone bf)) (and (WetDrone ae) (WetDrone bf)) (and (Drone ae) (WetDrone bf))))
            (and (= ?y ae) (= ?x af) (or (and (WetDrone af) (Drone ae)) (and (Drone af) (Drone ae)) (and (WetDrone ae) (WetDrone af)) (and (Drone af) (WetDrone ae))))
            (and (= ?y be) (= ?x af) (or (and (Drone af) (Drone be)) (and (Drone af) (WetDrone be)) (and (WetDrone af) (Drone be)) (and (WetDrone be) (WetDrone af))))
            (and (= ?y bf) (= ?x af) (or (and (WetDrone af) (Drone bf)) (and (WetDrone af) (WetDrone bf)) (and (Drone af) (WetDrone bf)) (and (Drone af) (Drone bf))))
            (and (= ?y aa) (= ?x ba) (or (and (WetDrone aa) (Drone ba)) (and (WetDrone aa) (WetDrone ba)) (and (Drone aa) (WetDrone ba)) (and (Drone aa) (Drone ba))))
            (and (= ?y ab) (= ?x ba) (or (and (WetDrone ab) (Drone ba)) (and (Drone ab) (WetDrone ba)) (and (Drone ba) (Drone ab)) (and (WetDrone ba) (WetDrone ab))))
            (and (= ?y bb) (= ?x ba) (or (and (Drone bb) (Drone ba)) (and (Drone ba) (WetDrone bb)) (and (WetDrone bb) (WetDrone ba)) (and (Drone bb) (WetDrone ba))))
            (and (= ?y ca) (= ?x ba) (or (and (Drone ca) (WetDrone ba)) (and (WetDrone ca) (Drone ba)) (and (WetDrone ca) (WetDrone ba)) (and (Drone ca) (Drone ba))))
            (and (= ?y cb) (= ?x ba) (or (and (WetDrone ba) (WetDrone cb)) (and (Drone cb) (WetDrone ba)) (and (Drone ba) (WetDrone cb)) (and (Drone ba) (Drone cb))))
            (and (= ?y aa) (= ?x bb) (or (and (WetDrone aa) (WetDrone bb)) (and (WetDrone bb) (Drone aa)) (and (WetDrone aa) (Drone bb)) (and (Drone bb) (Drone aa))))
            (and (= ?y ab) (= ?x bb) (or (and (Drone bb) (Drone ab)) (and (WetDrone bb) (WetDrone ab)) (and (WetDrone bb) (Drone ab)) (and (WetDrone ab) (Drone bb))))
            (and (= ?y ac) (= ?x bb) (or (and (Drone bb) (Drone ac)) (and (WetDrone bb) (Drone ac)) (and (Drone bb) (WetDrone ac)) (and (WetDrone bb) (WetDrone ac))))
            (and (= ?y ba) (= ?x bb) (or (and (Drone bb) (Drone ba)) (and (Drone ba) (WetDrone bb)) (and (WetDrone bb) (WetDrone ba)) (and (Drone bb) (WetDrone ba))))
            (and (= ?y bc) (= ?x bb) (or (and (Drone bb) (Drone bc)) (and (WetDrone bb) (Drone bc)) (and (Drone bb) (WetDrone bc)) (and (WetDrone bb) (WetDrone bc))))
            (and (= ?y ca) (= ?x bb) (or (and (WetDrone ca) (Drone bb)) (and (WetDrone ca) (WetDrone bb)) (and (Drone ca) (Drone bb)) (and (Drone ca) (WetDrone bb))))
            (and (= ?y cb) (= ?x bb) (or (and (Drone cb) (WetDrone bb)) (and (WetDrone cb) (Drone bb)) (and (WetDrone bb) (WetDrone cb)) (and (Drone cb) (Drone bb))))
            (and (= ?y cc) (= ?x bb) (or (and (WetDrone cc) (WetDrone bb)) (and (WetDrone cc) (Drone bb)) (and (WetDrone bb) (Drone cc)) (and (Drone bb) (Drone cc))))
            (and (= ?y ab) (= ?x bc) (or (and (Drone bc) (Drone ab)) (and (WetDrone ab) (Drone bc)) (and (WetDrone bc) (Drone ab)) (and (WetDrone ab) (WetDrone bc))))
            (and (= ?y ac) (= ?x bc) (or (and (WetDrone bc) (Drone ac)) (and (WetDrone bc) (WetDrone ac)) (and (WetDrone ac) (Drone bc)) (and (Drone bc) (Drone ac))))
            (and (= ?y ad) (= ?x bc) (or (and (Drone ad) (WetDrone bc)) (and (WetDrone ad) (Drone bc)) (and (WetDrone ad) (WetDrone bc)) (and (Drone ad) (Drone bc))))
            (and (= ?y bb) (= ?x bc) (or (and (Drone bb) (Drone bc)) (and (WetDrone bb) (Drone bc)) (and (Drone bb) (WetDrone bc)) (and (WetDrone bb) (WetDrone bc))))
            (and (= ?y bd) (= ?x bc) (or (and (Drone bc) (Drone bd)) (and (WetDrone bc) (WetDrone bd)) (and (WetDrone bc) (Drone bd)) (and (WetDrone bd) (Drone bc))))
            (and (= ?y cb) (= ?x bc) (or (and (Drone cb) (Drone bc)) (and (Drone cb) (WetDrone bc)) (and (WetDrone cb) (Drone bc)) (and (WetDrone bc) (WetDrone cb))))
            (and (= ?y cc) (= ?x bc) (or (and (Drone cc) (WetDrone bc)) (and (WetDrone cc) (Drone bc)) (and (WetDrone bc) (WetDrone cc)) (and (Drone cc) (Drone bc))))
            (and (= ?y cd) (= ?x bc) (or (and (Drone bc) (Drone cd)) (and (WetDrone cd) (Drone bc)) (and (WetDrone bc) (WetDrone cd)) (and (WetDrone bc) (Drone cd))))
            (and (= ?y ac) (= ?x bd) (or (and (WetDrone bd) (WetDrone ac)) (and (Drone ac) (Drone bd)) (and (WetDrone bd) (Drone ac)) (and (WetDrone ac) (Drone bd))))
            (and (= ?y ad) (= ?x bd) (or (and (WetDrone ad) (Drone bd)) (and (Drone ad) (WetDrone bd)) (and (WetDrone ad) (WetDrone bd)) (and (Drone ad) (Drone bd))))
            (and (= ?y ae) (= ?x bd) (or (and (WetDrone ae) (Drone bd)) (and (WetDrone bd) (WetDrone ae)) (and (Drone ae) (WetDrone bd)) (and (Drone ae) (Drone bd))))
            (and (= ?y bc) (= ?x bd) (or (and (Drone bc) (Drone bd)) (and (WetDrone bc) (WetDrone bd)) (and (WetDrone bc) (Drone bd)) (and (WetDrone bd) (Drone bc))))
            (and (= ?y be) (= ?x bd) (or (and (Drone be) (Drone bd)) (and (Drone be) (WetDrone bd)) (and (WetDrone be) (WetDrone bd)) (and (WetDrone be) (Drone bd))))
            (and (= ?y cc) (= ?x bd) (or (and (WetDrone cc) (Drone bd)) (and (Drone cc) (WetDrone bd)) (and (WetDrone cc) (WetDrone bd)) (and (Drone cc) (Drone bd))))
            (and (= ?y cd) (= ?x bd) (or (and (WetDrone bd) (Drone cd)) (and (Drone cd) (Drone bd)) (and (WetDrone cd) (WetDrone bd)) (and (WetDrone cd) (Drone bd))))
            (and (= ?y ce) (= ?x bd) (or (and (Drone bd) (Drone ce)) (and (WetDrone ce) (Drone bd)) (and (WetDrone bd) (WetDrone ce)) (and (WetDrone bd) (Drone ce))))
            (and (= ?y ad) (= ?x be) (or (and (Drone ad) (Drone be)) (and (WetDrone be) (WetDrone ad)) (and (WetDrone be) (Drone ad)) (and (WetDrone ad) (Drone be))))
            (and (= ?y ae) (= ?x be) (or (and (WetDrone be) (WetDrone ae)) (and (Drone be) (Drone ae)) (and (WetDrone be) (Drone ae)) (and (Drone be) (WetDrone ae))))
            (and (= ?y af) (= ?x be) (or (and (Drone af) (Drone be)) (and (Drone af) (WetDrone be)) (and (WetDrone af) (Drone be)) (and (WetDrone be) (WetDrone af))))
            (and (= ?y bd) (= ?x be) (or (and (Drone be) (Drone bd)) (and (Drone be) (WetDrone bd)) (and (WetDrone be) (WetDrone bd)) (and (WetDrone be) (Drone bd))))
            (and (= ?y bf) (= ?x be) (or (and (Drone be) (WetDrone bf)) (and (WetDrone be) (WetDrone bf)) (and (WetDrone be) (Drone bf)) (and (Drone be) (Drone bf))))
            (and (= ?y cd) (= ?x be) (or (and (Drone be) (Drone cd)) (and (Drone be) (WetDrone cd)) (and (WetDrone be) (Drone cd)) (and (WetDrone be) (WetDrone cd))))
            (and (= ?y ce) (= ?x be) (or (and (WetDrone be) (WetDrone ce)) (and (Drone be) (Drone ce)) (and (Drone be) (WetDrone ce)) (and (WetDrone be) (Drone ce))))
            (and (= ?y cf) (= ?x be) (or (and (WetDrone be) (Drone cf)) (and (WetDrone cf) (WetDrone be)) (and (Drone be) (Drone cf)) (and (WetDrone cf) (Drone be))))
            (and (= ?y ae) (= ?x bf) (or (and (Drone ae) (Drone bf)) (and (WetDrone ae) (Drone bf)) (and (WetDrone ae) (WetDrone bf)) (and (Drone ae) (WetDrone bf))))
            (and (= ?y af) (= ?x bf) (or (and (WetDrone af) (Drone bf)) (and (WetDrone bf) (WetDrone af)) (and (Drone af) (WetDrone bf)) (and (Drone af) (Drone bf))))
            (and (= ?y be) (= ?x bf) (or (and (Drone be) (WetDrone bf)) (and (WetDrone be) (WetDrone bf)) (and (WetDrone be) (Drone bf)) (and (Drone be) (Drone bf))))
            (and (= ?y ce) (= ?x bf) (or (and (Drone ce) (Drone bf)) (and (Drone ce) (WetDrone bf)) (and (WetDrone ce) (WetDrone bf)) (and (WetDrone ce) (Drone bf))))
            (and (= ?y cf) (= ?x bf) (or (and (Drone cf) (Drone bf)) (and (Drone cf) (WetDrone bf)) (and (WetDrone cf) (WetDrone bf)) (and (WetDrone cf) (Drone bf))))
            (and (= ?y ba) (= ?x ca) (or (and (Drone ca) (WetDrone ba)) (and (WetDrone ca) (Drone ba)) (and (WetDrone ca) (WetDrone ba)) (and (Drone ca) (Drone ba))))
            (and (= ?y bb) (= ?x ca) (or (and (WetDrone ca) (Drone bb)) (and (WetDrone ca) (WetDrone bb)) (and (Drone ca) (Drone bb)) (and (Drone ca) (WetDrone bb))))
            (and (= ?y cb) (= ?x ca) (or (and (WetDrone ca) (Drone cb)) (and (Drone ca) (Drone cb)) (and (Drone ca) (WetDrone cb)) (and (WetDrone ca) (WetDrone cb))))
            (and (= ?y da) (= ?x ca) (or (and (WetDrone ca) (WetDrone da)) (and (WetDrone ca) (Drone da)) (and (Drone ca) (Drone da)) (and (Drone ca) (WetDrone da))))
            (and (= ?y ba) (= ?x cb) (or (and (WetDrone ba) (WetDrone cb)) (and (Drone cb) (WetDrone ba)) (and (Drone ba) (WetDrone cb)) (and (Drone ba) (Drone cb))))
            (and (= ?y bb) (= ?x cb) (or (and (Drone cb) (WetDrone bb)) (and (WetDrone cb) (Drone bb)) (and (WetDrone bb) (WetDrone cb)) (and (Drone cb) (Drone bb))))
            (and (= ?y bc) (= ?x cb) (or (and (Drone cb) (Drone bc)) (and (Drone cb) (WetDrone bc)) (and (Drone bc) (WetDrone cb)) (and (WetDrone bc) (WetDrone cb))))
            (and (= ?y ca) (= ?x cb) (or (and (WetDrone ca) (Drone cb)) (and (Drone ca) (Drone cb)) (and (Drone ca) (WetDrone cb)) (and (WetDrone ca) (WetDrone cb))))
            (and (= ?y cc) (= ?x cb) (or (and (Drone cb) (Drone cc)) (and (Drone cc) (WetDrone cb)) (and (WetDrone cc) (WetDrone cb)) (and (Drone cb) (WetDrone cc))))
            (and (= ?y da) (= ?x cb) (or (and (Drone cb) (WetDrone da)) (and (WetDrone cb) (Drone da)) (and (Drone cb) (Drone da)) (and (WetDrone cb) (WetDrone da))))
            (and (= ?y bb) (= ?x cc) (or (and (WetDrone cc) (Drone bb)) (and (WetDrone bb) (Drone cc)) (and (Drone bb) (Drone cc)) (and (WetDrone bb) (WetDrone cc))))
            (and (= ?y bc) (= ?x cc) (or (and (Drone cc) (WetDrone bc)) (and (WetDrone cc) (Drone bc)) (and (WetDrone bc) (WetDrone cc)) (and (Drone cc) (Drone bc))))
            (and (= ?y bd) (= ?x cc) (or (and (WetDrone cc) (Drone bd)) (and (Drone cc) (WetDrone bd)) (and (WetDrone cc) (WetDrone bd)) (and (Drone cc) (Drone bd))))
            (and (= ?y cb) (= ?x cc) (or (and (Drone cc) (Drone cb)) (and (Drone cc) (WetDrone cb)) (and (WetDrone cc) (WetDrone cb)) (and (Drone cb) (WetDrone cc))))
            (and (= ?y cd) (= ?x cc) (or (and (Drone cc) (WetDrone cd)) (and (Drone cc) (Drone cd)) (and (WetDrone cc) (Drone cd)) (and (WetDrone cd) (WetDrone cc))))
            (and (= ?y dd) (= ?x cc) (or (and (WetDrone dd) (Drone cc)) (and (WetDrone cc) (Drone dd)) (and (Drone cc) (Drone dd)) (and (WetDrone cc) (WetDrone dd))))
            (and (= ?y bc) (= ?x cd) (or (and (Drone bc) (Drone cd)) (and (WetDrone cd) (Drone bc)) (and (WetDrone bc) (WetDrone cd)) (and (WetDrone bc) (Drone cd))))
            (and (= ?y bd) (= ?x cd) (or (and (Drone cd) (Drone bd)) (and (WetDrone bd) (Drone cd)) (and (WetDrone cd) (Drone bd)) (and (WetDrone cd) (WetDrone bd))))
            (and (= ?y be) (= ?x cd) (or (and (Drone be) (Drone cd)) (and (Drone be) (WetDrone cd)) (and (WetDrone be) (Drone cd)) (and (WetDrone be) (WetDrone cd))))
            (and (= ?y cc) (= ?x cd) (or (and (Drone cc) (WetDrone cd)) (and (Drone cc) (Drone cd)) (and (WetDrone cc) (Drone cd)) (and (WetDrone cd) (WetDrone cc))))
            (and (= ?y ce) (= ?x cd) (or (and (WetDrone cd) (WetDrone ce)) (and (WetDrone cd) (Drone ce)) (and (WetDrone ce) (Drone cd)) (and (Drone cd) (Drone ce))))
            (and (= ?y dd) (= ?x cd) (or (and (WetDrone dd) (Drone cd)) (and (Drone dd) (Drone cd)) (and (WetDrone dd) (WetDrone cd)) (and (Drone dd) (WetDrone cd))))
            (and (= ?y de) (= ?x cd) (or (and (WetDrone cd) (Drone de)) (and (Drone de) (Drone cd)) (and (WetDrone de) (Drone cd)) (and (WetDrone de) (WetDrone cd))))
            (and (= ?y bd) (= ?x ce) (or (and (Drone bd) (Drone ce)) (and (WetDrone ce) (Drone bd)) (and (WetDrone bd) (WetDrone ce)) (and (WetDrone bd) (Drone ce))))
            (and (= ?y be) (= ?x ce) (or (and (WetDrone be) (WetDrone ce)) (and (Drone be) (Drone ce)) (and (Drone be) (WetDrone ce)) (and (WetDrone be) (Drone ce))))
            (and (= ?y bf) (= ?x ce) (or (and (WetDrone ce) (Drone bf)) (and (Drone ce) (WetDrone bf)) (and (WetDrone ce) (WetDrone bf)) (and (Drone ce) (Drone bf))))
            (and (= ?y cd) (= ?x ce) (or (and (Drone cd) (Drone ce)) (and (WetDrone cd) (Drone ce)) (and (WetDrone ce) (Drone cd)) (and (WetDrone cd) (WetDrone ce))))
            (and (= ?y cf) (= ?x ce) (or (and (WetDrone cf) (WetDrone ce)) (and (Drone cf) (WetDrone ce)) (and (WetDrone cf) (Drone ce)) (and (Drone cf) (Drone ce))))
            (and (= ?y dd) (= ?x ce) (or (and (WetDrone dd) (Drone ce)) (and (Drone dd) (WetDrone ce)) (and (WetDrone ce) (WetDrone dd)) (and (Drone dd) (Drone ce))))
            (and (= ?y de) (= ?x ce) (or (and (WetDrone de) (Drone ce)) (and (WetDrone de) (WetDrone ce)) (and (Drone de) (Drone ce)) (and (WetDrone ce) (Drone de))))
            (and (= ?y df) (= ?x ce) (or (and (WetDrone ce) (Drone df)) (and (WetDrone ce) (WetDrone df)) (and (Drone ce) (Drone df)) (and (WetDrone df) (Drone ce))))
            (and (= ?y be) (= ?x cf) (or (and (WetDrone be) (Drone cf)) (and (WetDrone cf) (WetDrone be)) (and (Drone be) (Drone cf)) (and (WetDrone cf) (Drone be))))
            (and (= ?y bf) (= ?x cf) (or (and (Drone cf) (Drone bf)) (and (Drone cf) (WetDrone bf)) (and (WetDrone cf) (WetDrone bf)) (and (WetDrone cf) (Drone bf))))
            (and (= ?y ce) (= ?x cf) (or (and (WetDrone cf) (WetDrone ce)) (and (Drone cf) (WetDrone ce)) (and (WetDrone cf) (Drone ce)) (and (Drone cf) (Drone ce))))
            (and (= ?y de) (= ?x cf) (or (and (WetDrone cf) (WetDrone de)) (and (WetDrone cf) (Drone de)) (and (Drone cf) (Drone de)) (and (Drone cf) (WetDrone de))))
            (and (= ?y df) (= ?x cf) (or (and (Drone cf) (Drone df)) (and (WetDrone cf) (WetDrone df)) (and (Drone cf) (WetDrone df)) (and (WetDrone cf) (Drone df))))
            (and (= ?y ca) (= ?x da) (or (and (WetDrone ca) (WetDrone da)) (and (WetDrone ca) (Drone da)) (and (Drone ca) (Drone da)) (and (Drone ca) (WetDrone da))))
            (and (= ?y cb) (= ?x da) (or (and (Drone cb) (WetDrone da)) (and (WetDrone cb) (Drone da)) (and (Drone cb) (Drone da)) (and (WetDrone cb) (WetDrone da))))
 
            (and (= ?y cc) (= ?x dd) (or (and (WetDrone dd) (Drone cc)) (and (WetDrone cc) (Drone dd)) (and (Drone cc) (Drone dd)) (and (WetDrone cc) (WetDrone dd))))
            (and (= ?y cd) (= ?x dd) (or (and (WetDrone dd) (Drone cd)) (and (Drone dd) (Drone cd)) (and (WetDrone dd) (WetDrone cd)) (and (Drone dd) (WetDrone cd))))
            (and (= ?y ce) (= ?x dd) (or (and (WetDrone dd) (Drone ce)) (and (Drone dd) (WetDrone ce)) (and (WetDrone ce) (WetDrone dd)) (and (Drone dd) (Drone ce))))
            (and (= ?y de) (= ?x dd) (or (and (Drone dd) (Drone de)) (and (WetDrone dd) (WetDrone de)) (and (Drone de) (WetDrone dd)) (and (WetDrone de) (Drone dd))))
            (and (= ?y ec) (= ?x dd) (or (and (WetDrone ec) (Drone dd)) (and (WetDrone ec) (WetDrone dd)) (and (Drone ec) (WetDrone dd)) (and (Drone ec) (Drone dd))))
            (and (= ?y ed) (= ?x dd) (or (and (WetDrone dd) (Drone ed)) (and (Drone dd) (WetDrone ed)) (and (WetDrone dd) (WetDrone ed)) (and (Drone dd) (Drone ed))))
            (and (= ?y ee) (= ?x dd) (or (and (Drone ee) (Drone dd)) (and (WetDrone ee) (Drone dd)) (and (Drone ee) (WetDrone dd)) (and (WetDrone dd) (WetDrone ee))))
            (and (= ?y cd) (= ?x de) (or (and (WetDrone cd) (Drone de)) (and (Drone de) (Drone cd)) (and (WetDrone de) (Drone cd)) (and (WetDrone de) (WetDrone cd))))
            (and (= ?y ce) (= ?x de) (or (and (WetDrone de) (Drone ce)) (and (WetDrone de) (WetDrone ce)) (and (Drone de) (Drone ce)) (and (WetDrone ce) (Drone de))))
            (and (= ?y cf) (= ?x de) (or (and (WetDrone cf) (WetDrone de)) (and (WetDrone cf) (Drone de)) (and (Drone cf) (Drone de)) (and (Drone cf) (WetDrone de))))
            (and (= ?y dd) (= ?x de) (or (and (Drone dd) (Drone de)) (and (WetDrone dd) (WetDrone de)) (and (Drone de) (WetDrone dd)) (and (WetDrone de) (Drone dd))))
            (and (= ?y df) (= ?x de) (or (and (Drone de) (Drone df)) (and (WetDrone de) (Drone df)) (and (WetDrone df) (Drone de)) (and (WetDrone de) (WetDrone df))))
            (and (= ?y ed) (= ?x de) (or (and (WetDrone de) (WetDrone ed)) (and (Drone de) (WetDrone ed)) (and (WetDrone de) (Drone ed)) (and (Drone de) (Drone ed))))
            (and (= ?y ee) (= ?x de) (or (and (WetDrone ee) (WetDrone de)) (and (Drone de) (WetDrone ee)) (and (Drone ee) (Drone de)) (and (Drone ee) (WetDrone de))))
            (and (= ?y ef) (= ?x de) (or (and (WetDrone de) (WetDrone ef)) (and (WetDrone ef) (Drone de)) (and (WetDrone de) (Drone ef)) (and (Drone ef) (Drone de))))
            (and (= ?y ce) (= ?x df) (or (and (WetDrone ce) (Drone df)) (and (WetDrone ce) (WetDrone df)) (and (Drone ce) (Drone df)) (and (WetDrone df) (Drone ce))))
            (and (= ?y cf) (= ?x df) (or (and (Drone cf) (Drone df)) (and (WetDrone cf) (WetDrone df)) (and (Drone cf) (WetDrone df)) (and (WetDrone cf) (Drone df))))
            (and (= ?y de) (= ?x df) (or (and (Drone de) (Drone df)) (and (WetDrone de) (Drone df)) (and (WetDrone df) (Drone de)) (and (WetDrone de) (WetDrone df))))
            (and (= ?y ee) (= ?x df) (or (and (Drone ee) (WetDrone df)) (and (WetDrone ee) (Drone df)) (and (Drone ee) (Drone df)) (and (WetDrone df) (WetDrone ee))))
            (and (= ?y ef) (= ?x df) (or (and (WetDrone df) (Drone ef)) (and (Drone ef) (Drone df)) (and (WetDrone ef) (Drone df)) (and (WetDrone ef) (WetDrone df))))
 
            (and (= ?y dd) (= ?x ec) (or (and (WetDrone ec) (Drone dd)) (and (WetDrone ec) (WetDrone dd)) (and (Drone ec) (WetDrone dd)) (and (Drone ec) (Drone dd))))
            (and (= ?y ed) (= ?x ec) (or (and (Drone ec) (WetDrone ed)) (and (WetDrone ec) (Drone ed)) (and (Drone ec) (Drone ed)) (and (WetDrone ec) (WetDrone ed))))
            (and (= ?y fb) (= ?x ec) (or (and (WetDrone ec) (Drone fb)) (and (WetDrone fb) (WetDrone ec)) (and (Drone ec) (Drone fb)) (and (WetDrone fb) (Drone ec))))
            (and (= ?y fc) (= ?x ec) (or (and (WetDrone ec) (Drone fc)) (and (Drone ec) (WetDrone fc)) (and (Drone ec) (Drone fc)) (and (WetDrone ec) (WetDrone fc))))
            (and (= ?y fd) (= ?x ec) (or (and (WetDrone ec) (WetDrone fd)) (and (Drone ec) (WetDrone fd)) (and (Drone fd) (Drone ec)) (and (Drone fd) (WetDrone ec))))
            (and (= ?y dd) (= ?x ed) (or (and (Drone ed) (WetDrone dd)) (and (Drone dd) (WetDrone ed)) (and (WetDrone dd) (WetDrone ed)) (and (Drone dd) (Drone ed))))
            (and (= ?y de) (= ?x ed) (or (and (WetDrone de) (WetDrone ed)) (and (Drone de) (WetDrone ed)) (and (WetDrone de) (Drone ed)) (and (Drone de) (Drone ed))))
            (and (= ?y ec) (= ?x ed) (or (and (Drone ec) (WetDrone ed)) (and (WetDrone ec) (Drone ed)) (and (Drone ec) (Drone ed)) (and (WetDrone ec) (WetDrone ed))))
            (and (= ?y ee) (= ?x ed) (or (and (WetDrone ed) (WetDrone ee)) (and (Drone ed) (WetDrone ee)) (and (Drone ee) (WetDrone ed)) (and (Drone ee) (Drone ed))))
            (and (= ?y fc) (= ?x ed) (or (and (WetDrone fc) (Drone ed)) (and (Drone ed) (Drone fc)) (and (WetDrone ed) (Drone fc)) (and (WetDrone fc) (WetDrone ed))))
            (and (= ?y fd) (= ?x ed) (or (and (WetDrone fd) (Drone ed)) (and (WetDrone fd) (WetDrone ed)) (and (Drone fd) (WetDrone ed)) (and (Drone fd) (Drone ed))))
            (and (= ?y fe) (= ?x ed) (or (and (Drone ed) (WetDrone fe)) (and (Drone ed) (Drone fe)) (and (WetDrone fe) (WetDrone ed)) (and (Drone fe) (WetDrone ed))))
            (and (= ?y dd) (= ?x ee) (or (and (Drone ee) (WetDrone dd)) (and (Drone ee) (Drone dd)) (and (WetDrone dd) (WetDrone ee)) (and (WetDrone ee) (Drone dd))))
            (and (= ?y de) (= ?x ee) (or (and (WetDrone ee) (WetDrone de)) (and (Drone de) (WetDrone ee)) (and (Drone ee) (Drone de)) (and (Drone ee) (WetDrone de))))
            (and (= ?y df) (= ?x ee) (or (and (Drone ee) (WetDrone df)) (and (WetDrone ee) (Drone df)) (and (Drone ee) (Drone df)) (and (WetDrone df) (WetDrone ee))))
            (and (= ?y ed) (= ?x ee) (or (and (WetDrone ed) (WetDrone ee)) (and (Drone ed) (WetDrone ee)) (and (Drone ee) (WetDrone ed)) (and (Drone ee) (Drone ed))))
            (and (= ?y ef) (= ?x ee) (or (and (Drone ef) (WetDrone ee)) (and (Drone ee) (WetDrone ef)) (and (WetDrone ee) (WetDrone ef)) (and (Drone ee) (Drone ef))))
            (and (= ?y fd) (= ?x ee) (or (and (Drone fd) (WetDrone ee)) (and (WetDrone fd) (WetDrone ee)) (and (Drone ee) (WetDrone fd)) (and (Drone ee) (Drone fd))))
            (and (= ?y fe) (= ?x ee) (or (and (Drone fe) (WetDrone ee)) (and (Drone ee) (WetDrone fe)) (and (Drone ee) (Drone fe)) (and (WetDrone fe) (WetDrone ee))))
            (and (= ?y ff) (= ?x ee) (or (and (WetDrone ee) (WetDrone ff)) (and (WetDrone ee) (Drone ff)) (and (Drone ee) (WetDrone ff)) (and (Drone ee) (Drone ff))))
            (and (= ?y de) (= ?x ef) (or (and (WetDrone de) (WetDrone ef)) (and (WetDrone ef) (Drone de)) (and (WetDrone de) (Drone ef)) (and (Drone ef) (Drone de))))
            (and (= ?y df) (= ?x ef) (or (and (WetDrone df) (Drone ef)) (and (Drone ef) (Drone df)) (and (WetDrone ef) (Drone df)) (and (WetDrone ef) (WetDrone df))))
            (and (= ?y ee) (= ?x ef) (or (and (Drone ef) (WetDrone ee)) (and (Drone ee) (WetDrone ef)) (and (WetDrone ee) (WetDrone ef)) (and (Drone ee) (Drone ef))))
            (and (= ?y fe) (= ?x ef) (or (and (Drone fe) (WetDrone ef)) (and (WetDrone ef) (WetDrone fe)) (and (Drone ef) (Drone fe)) (and (Drone ef) (WetDrone fe))))
            (and (= ?y ff) (= ?x ef) (or (and (WetDrone ff) (WetDrone ef)) (and (Drone ff) (WetDrone ef)) (and (Drone ff) (Drone ef)) (and (Drone ef) (WetDrone ff))))
            (and (= ?y fb) (= ?x fa) (or (and (WetDrone fa) (WetDrone fb)) (and (Drone fb) (Drone fa)) (and (WetDrone fb) (Drone fa)) (and (Drone fb) (WetDrone fa))))
            (and (= ?y ec) (= ?x fb) (or (and (WetDrone ec) (Drone fb)) (and (WetDrone fb) (WetDrone ec)) (and (Drone ec) (Drone fb)) (and (WetDrone fb) (Drone ec))))
            (and (= ?y fa) (= ?x fb) (or (and (WetDrone fa) (WetDrone fb)) (and (Drone fb) (Drone fa)) (and (WetDrone fb) (Drone fa)) (and (Drone fb) (WetDrone fa))))
            (and (= ?y fc) (= ?x fb) (or (and (Drone fb) (WetDrone fc)) (and (WetDrone fb) (Drone fc)) (and (WetDrone fb) (WetDrone fc)) (and (Drone fb) (Drone fc))))
            (and (= ?y ec) (= ?x fc) (or (and (WetDrone ec) (Drone fc)) (and (Drone ec) (WetDrone fc)) (and (Drone ec) (Drone fc)) (and (WetDrone ec) (WetDrone fc))))
            (and (= ?y ed) (= ?x fc) (or (and (WetDrone fc) (WetDrone ed)) (and (WetDrone ed) (Drone fc)) (and (WetDrone fc) (Drone ed)) (and (Drone ed) (Drone fc))))
            (and (= ?y fb) (= ?x fc) (or (and (Drone fb) (WetDrone fc)) (and (WetDrone fb) (Drone fc)) (and (WetDrone fb) (WetDrone fc)) (and (Drone fb) (Drone fc))))
            (and (= ?y fd) (= ?x fc) (or (and (Drone fd) (WetDrone fc)) (and (WetDrone fd) (Drone fc)) (and (WetDrone fd) (WetDrone fc)) (and (Drone fd) (Drone fc))))
            (and (= ?y ec) (= ?x fd) (or (and (WetDrone ec) (WetDrone fd)) (and (Drone ec) (WetDrone fd)) (and (Drone fd) (Drone ec)) (and (Drone fd) (WetDrone ec))))
            (and (= ?y ed) (= ?x fd) (or (and (WetDrone fd) (Drone ed)) (and (WetDrone fd) (WetDrone ed)) (and (Drone fd) (WetDrone ed)) (and (Drone fd) (Drone ed))))
            (and (= ?y ee) (= ?x fd) (or (and (Drone fd) (WetDrone ee)) (and (WetDrone fd) (WetDrone ee)) (and (Drone ee) (WetDrone fd)) (and (Drone ee) (Drone fd))))
            (and (= ?y fc) (= ?x fd) (or (and (Drone fd) (WetDrone fc)) (and (WetDrone fd) (Drone fc)) (and (WetDrone fd) (WetDrone fc)) (and (Drone fd) (Drone fc))))
            (and (= ?y fe) (= ?x fd) (or (and (WetDrone fd) (Drone fe)) (and (Drone fd) (Drone fe)) (and (WetDrone fd) (WetDrone fe)) (and (Drone fd) (WetDrone fe))))
            (and (= ?y ed) (= ?x fe) (or (and (Drone ed) (WetDrone fe)) (and (Drone ed) (Drone fe)) (and (WetDrone fe) (WetDrone ed)) (and (Drone fe) (WetDrone ed))))
            (and (= ?y ee) (= ?x fe) (or (and (Drone fe) (WetDrone ee)) (and (Drone ee) (WetDrone fe)) (and (Drone ee) (Drone fe)) (and (WetDrone fe) (WetDrone ee))))
            (and (= ?y ef) (= ?x fe) (or (and (Drone ef) (WetDrone fe)) (and (WetDrone ef) (WetDrone fe)) (and (Drone fe) (WetDrone ef)) (and (Drone ef) (Drone fe))))
            (and (= ?y fd) (= ?x fe) (or (and (WetDrone fd) (Drone fe)) (and (Drone fd) (Drone fe)) (and (WetDrone fd) (WetDrone fe)) (and (Drone fd) (WetDrone fe))))
            (and (= ?y ff) (= ?x fe) (or (and (WetDrone fe) (WetDrone ff)) (and (Drone fe) (WetDrone ff)) (and (Drone ff) (WetDrone fe)) (and (Drone ff) (Drone fe))))
            (and (= ?y ee) (= ?x ff) (or (and (WetDrone ee) (WetDrone ff)) (and (WetDrone ee) (Drone ff)) (and (Drone ee) (WetDrone ff)) (and (Drone ee) (Drone ff))))
            (and (= ?y ef) (= ?x ff) (or (and (WetDrone ff) (WetDrone ef)) (and (Drone ff) (WetDrone ef)) (and (Drone ff) (Drone ef)) (and (Drone ef) (WetDrone ff))))
            (and (= ?y fe) (= ?x ff) (or (and (WetDrone fe) (WetDrone ff)) (and (Drone fe) (WetDrone ff)) (and (Drone ff) (Drone fe)) (and (Drone ff) (WetDrone fe))))

        )
    )

	(:action Move
	  :parameters (?x ?y)
        :precondition (and
            (not (inconsistent))
            (and 
	    (KBquery_XveryCloseY ?x ?y)
	    (not (KBquery_Objectx ?y))
	  )
        )
	  :effect (and
	    (when
	      (not (KBquery_WetDrone ?x))
	      (and (not (Drone ?x)) (Drone ?y))
	    )
	    (when
	      (KBquery_WetDrone ?x)
	      (and (not (WetDrone ?x)) (not (Drone ?x)) (WetDrone ?y))
	    )
	  )
	)
)
